### ISSUE TITLE
STextシナリオ「金竜の陰謀」

### ISSUE THREAD

**Issue by olreia** [snext1220/snext-management#10]
こんにちわ、ちゃなです。
ドラゴンモードシナリオ「金竜の陰謀」、1版が完成しましたことをご報告いたします。何卒ご査収ください。

※シーン0からの遷移が実績の関係で確認できておりません。
（Playgroundで動かすと、プロローグの記載が抜けて実行されます）

※BGMはオリジナルを1曲用いています。

宜しくお願いします！

[TGD.zip](https://github.com/snext1220/snext-management/files/2848850/TGD.zip)

**Comment by Salvadors-cabin** [comment]
ちゃなさん、ありがとうございます！
取り急ぎGitHUB環境にアップしました。以下のリンクからテストプレイできます。
https://snext1220.github.io/stext/index.html?id=plot

後日プレイさせていただきますね。
よろしくお願いしますー。

**Comment by snext1220** [comment]
サルバさん＞
Upありがとうございます！
こちらですが、idをタイトルに合わせてgoldに変更させていただきましたので、報告です。
https://snext1220.github.io/stext/index.html?id=gold

ちゃなさん＞
改めてシナリオ第一稿お疲れ様でした！
こちらでも謹んで拝読してまいりますね。

> プロローグの記載が抜けて実行されます

恐らく以下記載が悪さをしているものと思われます。
GBATでは不要なので、削除でお願いします（マニュアルの説明不足ですみません；）
```
<scene id="0">
<![CDATA[
```

なお、もう一点、scene0 にて気付いた点です。
 stars="0,0,0,0,0,0,0"は初期値なので、恐らくご不要かと思われます。
＃別なご意図があるようであれば無視してください。

**Comment by olreia** [comment]
＞王様
ありがとうございます！プロローグと星のかけら、修正しました。
[TGD36.zip](https://github.com/snext1220/snext-management/files/2849678/TGD36.zip)

**Comment by Salvadors-cabin** [comment]
みなさん、どうもありがとうございます！
GitHUBのシナリオを更新しました。
https://snext1220.github.io/stext/index.html?id=gold

よろしくお願いしますー

**Comment by snext1220** [comment]
テストプレイ中です。
とりあえず気付いた点をメモ書き、引き続き追記していきます。

---
・scene0
ドラゴンスレーヤー ⇒ ドラゴンスレイヤー
※致命的ではありませんが、あまり伸ばし表記を見たことがないので。

・scene0
${if}の閉じがないようです。

・全体
戦利品：reward
ステータス画面：掃討数
不揃い？
パラメーターの説明がないので、最初に補足があっても？
※そもそも戦利品としては違和感があるので、free2属性で自動加算すべき？

・scene17
無限に星のかけらを入手できる？

**Comment by olreia** [comment]
おお、早い！ありがとうございます。

スレーヤー＞すみません、誤植ですね。失礼しました。

${if}＞修正しました。が、テストプレイ環境ではうまく機能しているか今一つわからないので、後ほどご確認いただければありがたいです。

reward＞すみません。ここはもともと、敵を倒すために自動的にFREE2に1を加える処理にするつもりでした。しかし、うまく機能しなかったので、苦肉の策として手動にしたものです。戦闘処理をした際にFREE2を+1する構文についてご教示いただければ幸いです。

無限に星のかけら＞仕様です。一応、「機会があればまた見に来るとしよう」がフリになっています。ただし、最初はUN-CURSEから使わなければならず、訪れるたびにFREE1が増えてしまうリスクがあります。……と言っておきながら、FREE1が関与するシーンも実は魔法で回避できてしまいますね。。そのシーンは魔法禁止とします。
[TGD37.zip](https://github.com/snext1220/snext-management/files/2855654/TGD37.zip)


今後ともよろしくお願いいたします。

**Comment by snext1220** [comment]
早速の修正ありがとうございます！
ポチポチと進めておりますため、小出しのコメントになってしまい恐縮ですが、引き続きよろしくお願いいたしますm(_ _)m

reward＞現時点の構成ですと、enemies属性を指定しているシーンで、合わせて「@free2:1」のようにするのが手っ取り早そうです（戦闘前にfree2が加算されてしまいますが、戦闘回避などがなければ実質の問題はないかと）。
＃もし戦闘後であることを保証するならば、戦闘勝利**後**のシーンを加え、そちらで「@free2:1」としても良いのですが、影響も大きいのであまりお勧めは^^;

無限に＞あ、無限に行き来していると、現実に戻った時に大ダメージで即死ということですか！（後半プレイで漸くご意図を理解できました。。失礼しました^^;）

では、また進め、気付いた点がありましたら書き込みたいと思います～

### 追記

先ほど、テストプレイ終了しました！
前半はキャラの種族所以か苦労し、後半死にまくりでｗ苦戦しましたが、まずは無事クリアです。
ホント、種族によって難易度が変化するというのは面白いアイデアですよね（dwarf-male-oldでは結局詰んだので、また挑戦してみたいと思います）。ちなみに、elf-female-adultでは前半はかなりラクに行けました。

後半はゲームブックらしい駆け引きが堪らないですね！
正解ルートに辿り着くまでにボコボコにされていましたｗ
あとからプレイされる方は、中盤で一度バックアップを取った方が無難、かもしれませんｗ

そして、最後がまた、、、いい！！！
まだ終わらないぜエンディングは、まさに連作ならではの余韻ですね～
素晴らしいシナリオをありがとうございました！

**Comment by olreia** [comment]
ご笑覧いただきありがとうございます！

・Free2の処理を修正しました。rewardはかわって、ランダムで星のかけらが手に入るようになっています。

老男ドワーフ引いちゃいましたか。。。彼だけはメジャーなクリアルートが使えないんですよね。別ルートを示唆する記載をちょっとだけ修正しています。
[TGD38.zip](https://github.com/snext1220/snext-management/files/2860578/TGD38.zip)


エンディングは、マーベルヒーロー映画を意識してみました。。

**Comment by Salvadors-cabin** [comment]
「金竜の陰謀」プレイしました。
偽のペンタウァから脱出できずに迷いましたが、よく文章を読むとヒントが隠されていて、それに従って職業を変えていくと進めることができました。
巧妙なつくりに驚きましたよ。

金竜との戦いも文章中にヒントが隠されていて、何とかクリアできました。
途中死んだかと思うシーンもあり、ドキドキでした。
重厚な作品ありがとうございます！

製作中の私の拙作「ドラゴンネゴシエーター」も同じくペンタウァで探索するストーリーで、王城や魔法学院を訪れるシーンがあります。
ソーサリアンを原作とするシナリオ同士、偶然ながら共通する部分が見られてシリーズ感を感じてしまいました。
魔法学院のエルフを「司書」と表現したのはよいですね。「ネゴシエーター」では「案内嬢」と表現していたのでパクらせてもらおうかと思っています（笑）。

最後になりましたが、最新ファイルTGD38をGitHUBにアップしました。
http://localhost/stext-master/index.html?id=gold

よろしくお願いします。

**Comment by olreia** [comment]
サルバさん、有難うございます！
司書はなんとなくのイメージです。天才肌のエスターに比べて、エスメレーは努力家タイプなのかな、と。

**Comment by cocotori** [comment]
プレイさせていただきました！

誰が悪者なのかわからずさまよう感じ、いいですね。
ドラゴン戦の、単に戦闘能力が高いだけでなく
決まった手順で攻撃しないといけない仕組みが、
強敵感を感じさせていいなと思いました。

執筆、お疲れ様です！

一点、誤字っぽいもののご連絡です。
シーン43：司会　→　視界　でしょうか？

![default](https://user-images.githubusercontent.com/42885160/52952785-019cb100-33c9-11e9-9daf-b6b0e695a8b9.jpg)

また、シーン53以降のボス戦bgmが
わたしの環境では再生されないようでした。
みなさんの環境ではいかがでしたでしょうか・・・？
（Win 10  Chrome）

**Comment by olreia** [comment]
プレイ有難うございます！
幻惑の霧に包まれた街並みを感じていただけたら幸いです。

＞誤字
ご指摘ありがとうございます。修正しました。

それと、ラスボスの倒し方についてのヒントを少し付け足しました。これまでの原稿だとどうしても試行錯誤が必要になりますので。。

＞音楽
私も鳴りませんでした。ラスボスの曲はオリジナルですので、テストプレイ環境では鳴らないのでしょうか？


[TGD40.zip](https://github.com/snext1220/snext-management/files/2876132/TGD40.zip)

**Comment by toki-sor1** [comment]
ちゃなさん、執筆＆修正お疲れ様です！
現在、感想文をまとめているところなのですが、先にBGMの件についてお伝えしますね。
BGMが鳴らないのは、どうも設定に「@」が入っているのが原因のようでした。
```
<scene id="53" bgm="『@』Breakers">
```
こちらはオリジナル曲ですので、「@」はなくても大丈夫です。
「@」を消してテストしたところ、無事BGMが再生されました。

**Comment by olreia** [comment]
あら、そうなのですか！
有難うございます。
取り急ぎ修正しましたのでテストいただければ幸いです。
[TGD41.zip](https://github.com/snext1220/snext-management/files/2877692/TGD41.zip)

**Comment by toki-sor1** [comment]
こちらこそ、早速の修正ありがとうございます！
TGD41.zip解凍後のscenario.xmlをローカル環境にて起動し、該当シーン（Scene53～）でBGMが正常に流れているのを確認致しました。

**Comment by Salvadors-cabin** [comment]
遅ればせながらTGD41をGitHUBテスト環境にアップしました。
https://snext1220.github.io/stext/index.html?id=gold

ご確認ください。

**Comment by toki-sor1** [comment]
改めて、「金竜の陰謀」ご執筆お疲れ様です＆完成おめでとうございます！
前作「災厄の夜 - テンペスト・ナイト -」が、遊び易さとパラグラフの関係性、選択肢の意味等、
ゲームブックのことを学ぶ切っ掛けとなったシナリオでしたので、今作の物語やシステム、そして、
どんなことを学べるのだろうと期待に胸を躍らせていました！
今作も一足早く遊ばせていただき、ありがとうございます！

今作は職業システムを盛り込んだシナリオとお聞きしていましたが、実際に遊ばせていただき、
今までSTextではフレーバー的な存在だった「職業」が、一つのシステムとしてシナリオ内に
組み込まれているところに感激しました！
原作でもシナリオによっては職業が超重要だったりして、そういう意味でも原作を再現されていて
本当に素晴らしいです……！

前半パートの「転職を駆使して現状を打開する」というところも、ヒントを得て「この職業でも
いけるかな？」と試して選択肢が増えた時はニヤリとしましたし、種族等による転職制限で
一筋縄ではいかない時に、アレコレと試してみるのもとても楽しかったです！
転職にデメリットがなく、気軽に変更できるところもストレスフリーで良いですね。
（最初に女DWARFでスタートしましたが、現状を打開できずバッドエンドになり、再スタートの
男WIZARDでエンディングまで行けましたｗ）

後半パートはドラゴンモードの主役とも言えるドラゴンとの熱いバトル！
原作では幻影として登場していたゴールドドラゴンですが、今作ではご本竜登場ということで、
実力も大きさも異なっているというところに驚くと共にとても納得していましたｗ

大迫力のバトルは、STextの戦闘ルールを取り入れつつ、決められた手順で攻撃する必要がある、
というものでしたね。
戦闘ルールは、あくまでも自身への被ダメージのみに止め、ゴールドドラゴンへの与ダメージの、
「選択肢を選ぶ順番に委ねられ、HPMPがある限りは何度でも一からやり直せる」というところは、
ゲームブックの「試行錯誤しながら選択肢を選ぶ楽しみ」に特化している印象を受けました！
ゴールドドラゴンの強大さを演出しつつ、全体的に快適に遊べる構成……お見事です……！

ストーリーも、解放条件シナリオの設定と、既存シナリオの設定が調和し、更には「時を越えた
協力者」へと繋がっていて、本当に多くのシナリオ要素が含まれていて驚き、ニヤリとしました！

静まり返った無気味なペンタウァを特技を活かして探索し、ようやく目を覚ました『あなた』に
突き付けられた数々の真実は、そのどれもが衝撃的でゾクゾク！
前半パートの雰囲気から一転、後半パートは手に汗握るほどの白熱した戦闘の描写、そして登場人物の
格好良さに痺れました……！　いい……！！

ゴールドドラゴンの語りからは、このドラゴンスレイヤーシリーズのドラゴンが遥か昔はどのような
存在だったのかを窺い知ることができ、ゴールドドラゴンが抱く複雑な感情に、今作は敵という立場
ではありましたが、討伐後には何とも言えない寂しさも感じましたね。
同時に新たな「ドラゴンの在り方」も学ぶことができ、とても充実した時間でございました！
この度は、素敵なシナリオをご執筆いただき、本当にありがとうございました！

シナリオを遊ばせていただき、下記に気付いたことをまとめました。
既に修正済みのものや、私が勘違いしているもの、ちゃなさんの方針に合わない意見等はスルーして
やってくださいませ。

お忙しいところ恐縮ですが、引き続きよろしくお願い致します！

---

- 各シーンで「ドラゴンスレーヤー」と「ドラゴンスレイヤー」が混在しているようです。

- Scene0
【2/20追加  ここから】
GBATによるシナリオ作成では、新構文のCDATAの表記は不要と先のリオさんの書き込みにありましたね；
私の確認不足で見当違いなことを書き込み、ご迷惑をお掛けしてしまい、大変申し訳ありません……；；
【ここまで】

注意書きに記されている解放条件となる実績が、本来のものとは違うようです。
（注意書きと選択肢のリンクで新構文と旧構文が混在）
お手数ですが、修正をお願い致します。
```
${if !(r1056:slayer&r01:tempest)}%red%このシナリオを解放するには、Scenario 4「災厄の夜　-テンペスト・ナイト-」の実績（新たなる夜明け）、及びScenario 7「その名はドラゴンスレイヤー」の実績（娘を助けて武器屋を通常営業に戻した）を取得している必要があります！%/%
${/if}

[冒険に出発する](2 "r1056:slayer&r01:tempest")
</scene>
```

- Scene28
「状況は芳しくありません。ルワンはペンタウァの危機にかこつけて、邪なる神具を持ち込みました。彼が王城で唱えた呪文は、防御壁を作るものではなく、ペンタウァの民を異世界に幽閉する『禁呪文ったのです。』

- Scene45
「この時を待っていた。王都の混乱に乗じてペンタウァを掌握する絶好の機会をな。さあ、儂の前にひざまづくのだ、ソーサ『ア』リアンよ。さすれば、ザガの脅威からペンタウァの民を守ってやらんでもない」

- Scene63　BGM（battle01d）の再生時間が短いので、1回のみ再生する仕様でも大丈夫でしたら、「se（効果音）」として再生しても良いかもしれません。
  - その場合、SORCERIAN Text Original Sound（https://soundcloud.com/venus-az/sets/sorcerian-text-original-sounds/s-2tzI5 ）にログイン後、「battle01d」をダウンロードしていただき、シナリオフォルダの「BGMフォルダ内」に「se」というフォルダを作成後、「battle01d.mp3」を入れます（bgmフォルダ内の画像参照）。
それから、scenario.xmlを下記のように設定する必要があります。
```
<scene id="63" se="battle01d" end="good">
```
![image](https://user-images.githubusercontent.com/42646342/53100119-8ffc6880-356a-11e9-8364-9df217c9832d.png)
　※どうもse扱いだと、STextデフォルト曲でもフォルダ内にmp3ファイルを入れないとダメなようです

**Comment by toki-sor1** [comment]
連続投稿、失礼します。

「金竜の陰謀」Scene63では、end属性が「good」となっており、
実際に問題なくエンディングとして「最初から冒険に挑戦する」と表示されているのですが、
マニュアルには「happy」と「bad」の2種類が載っているのみで、今後もしかしたら不具合が
出る可能性もありますので、「happy」に修正していただいた方が良いかもしれません。

現在、「happy」に該当するエンディングはScene63のみということで、
もし「battle01dをseとして再生するように修正した場合（https://github.com/snext1220/snext-management/issues/10#issuecomment-465593990 ）」には、
happyエンドBGMを下記の１または２のように指定しても良いかもしれません。
```
１　<bgm main="@town02" bad="@town01">
２　<bgm main="@town02" happy="@none" bad="@town01">
```

**Comment by snext1220** [comment]
こちらもご確認お疲れ様です。以下簡単ながら補足です。

> どうもse扱いだと、STextデフォルト曲でもフォルダ～～

はい、あくまで標準**BGM**としての認識なので、SEとして扱う場合はそのようにお願いします。
用途が多い場合には、SEからも標準BGMを参照するよう改定できればと思いますが、おそらく対象がbattle01dだけなので悩ましい...；

> 「金竜の陰謀」Scene63では、end属性が「good」となっており、

仰る通り、現時点ではたまたま動いている状態ですね。。^^;
＃bgm属性がなくなった場合、楽曲の切り替えに失敗するかと思います。

seの扱いについては @toki-sor1 さんのご対応で行けるかと思います（ありがとうございます！）

**Comment by toki-sor1** [comment]
お疲れ様です！　こちらこそ補足ありがとうございました！

> はい、あくまで標準**BGM**としての認識なので、SEとして扱う場合はそのようにお願いします。

なるほど、標準BGMは「BGMとして設定した時のみMP3ファイルを入れなくても良い」ということなのですね（battle01dをSEとして設定した時に鳴らなかったので『あれ？』となってましたｗ）。

> 用途が多い場合には、SEからも標準BGMを参照するよう改定できればと思いますが、おそらく対象がbattle01dだけなので悩ましい...；

そうですね、再生時間が短い曲は今のところbattle01dだけなので、現状ではそのままの仕様でも良いかなと思います。

> 仰る通り、現時点ではたまたま動いている状態ですね。。^^;

以前もend属性についての話題が挙がっていたことがあり、私が把握していないだけなのかもとマニュアルを確認していましたｗ
補足していただき、助かりました！

**Comment by olreia** [comment]
ときのじさん、有難うございます！なんかもう、作者として伝えたかったことを何もかも受け取っていただけて、感無量です……！

誤植チェックも有難うございました。ドラスレの表記ゆれ、まだありましたね。申し訳ありません。一応全文検索で修正したので、たぶん大丈夫だと思います。

BGMも最後は無音にしてSEとして鳴らすようにしてみました。
エンディング後に何かスパイスの利いた音楽が欲しいなあと思ってたら、ちょうどbattle01dがあったんですよねー。私も自動ループなのが気になっていました。ご教示ありがとうございます。
これで如何でしょうか？

[TGD42.zip](https://github.com/snext1220/snext-management/files/2889616/TGD42.zip)

**Comment by toki-sor1** [comment]
ご返信ありがとうございます！
感想文を綴る時は、作品や設定の解釈等が違っていたらどうしようとソワソワしているので、ちゃなさんのお言葉にホッとしました～！

実はソーサリアンコンプリート発売日にソーサリアンBGMメドレーを脳内で再生していて、その時に「砂漠（呪われたオアシス）」を再生していたら「あっ！」となったのですが、「Breakers」は「砂漠」のメロディ（というのでしょうか？）のアレンジ要素も含んでいるように感じました！　胸熱です……！！（音楽知識に乏しいので、もし勘違いでしたら申し訳ありません……！）

シナリオの修正お疲れ様です！　ありがとうございました！
エンディングの自動ループについても、提案がお役に立ったようで良かったです～！
それでは、添付のデータを確認させていただき、気付いた点を挙げますね。
（ドラゴンスレイヤー等の表記ゆれや誤字の修正は、ばっちりでした！）

---

- シナリオフォルダ内のフォルダ名について
誤：「BGM」　→　正：「bgm」
こちらの表記ミスでした……；；
正しいフォルダ名から間違ったフォルダ名に変更させてしまい、申し訳ありません……！

- Scene63（エンディングについて１）
今回のデータでは、「battle01d」がse（効果音）として正常に再生されていました！
しかし、こちらがエンディングの修正について分割して投稿してしまい、修正箇所が紛らわしいことになっていました……す、すみません……；；
改めて、修正箇所について一つにまとめます。

- Scene63（エンディングについて２）
@snext1220 さんから補足（https://github.com/snext1220/snext-management/issues/10#issuecomment-465825423 ）していただきましたが、end属性は「happy」と「bad」の2種類のみなので、Scene 63のend属性は「happy」への修正をお願い致します。
```
<scene id="63" se="battle01d" end="happy">
```
- end属性をhappyに修正後（エンディングについて３）
  - 現在、`<bgm main="@town02" happy="@field04" bad="@town01">`とご指定いただいておりますが、Scene63で「@field04（BGM）」と「battle01d（効果音）」が同時に再生されると、どちらも聞き取り辛くなってしまうようです。
  - もし「battle01d（効果音）」のみ再生されるように設定する場合には、happyエンドBGMを下記の１または２のように指定しても良いかもしれません。
（どちらの設定でもhappy endのBGMは聞こえなくなります）
```
１　<bgm main="@town02" bad="@town01">
２　<bgm main="@town02" happy="@none" bad="@town01">
```
紛らわしい書き方や表記ミスなど、ご迷惑をお掛けしてしまい申し訳ありません；；
ご不明な点等ありましたら、気兼ねなくお訊ねくださいませ。
引き続きよろしくお願い致します。

**Comment by snext1220** [comment]
@toki-sor1 さん、ご確認有難うございます！
一点のみ、些細ではありますが、補足です。

bgm要素については、以下でお願いします（以前の投稿で気づかず、失礼しました；）。
`<bgm main="@town02" happy="@none" bad="@town01">`

happy属性なしの場合は、既定値のhappy.mp3を探しに行き、存在しないはずなので無音にはなりますが、内部的にはエラーが発生します（ユーザーには見えないエラーなので、避けておくに越したことはない、というレベルです）。

**Comment by olreia** [comment]
ご指摘ありがとうございます。
フォルダ名を小文字にし、ついでに王様と被っているエスメレーの台詞を一か所だけ直しました。
他のところは修正されているかと思いますが、ご確認いただければ幸いです。

[TGD43.zip](https://github.com/snext1220/snext-management/files/2897888/TGD43.zip)

「Breakers」は、実はその昔に作曲の授業で制作した習作です。音源はPC8801で、テープレコーダーに吹き込んでいたものをこのたび廃物利用させていただきました。
なので、もともとソーサリアンとは何の関係もありませんでしたし、ボス戦の曲としてはどうかなーとも思っていたのですが……言われてみると、「砂漠」とちょっと似てますね！
当時ソーサリアンの楽曲は暗記するほど聞きこんでいたので、無意識に寄せてしまったのかもしれません。ちょっとした奇跡を感じますね。。

**Comment by toki-sor1** [comment]
@snext1220 さん＞

補足ありがとうございます……！
こちらこそ仕様の把握ができておらず、申し訳ありません；；
今回のケースでは、happyエンドが存在しているので、happy BGMの指定を消す方法（１）は、適切ではなかったのですね；；（逆を言えば、happyエンドが存在していない場合は、１の指定も可能なのかな、と理解しました）
以後気をつけます！！

@olreia さん＞

早速のシナリオ修正ありがとうございます！　お疲れ様です！
最新ファイルを確認しましたが、こちらScene63の演出もバッチリでした！
しかし、happyエンドのBGMについて、私がシステムの仕様を把握できておらず、誤った情報を書き込んでしまい、ご迷惑をお掛けして申し訳ありませんでした；；

> 「Breakers」は、実はその昔に作曲の授業で制作した習作です。

おおっ、「Breakers」は昔お作りになった曲だったのですね！
「Breakers」の熱くも何処か物寂し気なメロディーが、今作のゴールドドラゴン戦の雰囲気とゴールドドラゴンの設定にとてもよくマッチしていたので、てっきり今作の描き下ろしだとばかり思ってました……！
ひぃん、盛大に勘違いしていてお恥ずかしい限りなのですが（汗）、しかし、シナリオのお話と共に、こうして「Breakers」の制作秘話や、当時のちゃなさんのお話をお聞きすることができたのは、とても嬉しいです！
お忙しい中、貴重なお話どうもありがとうございました！！

---
遅ればせながら、InfoTGD.txtにてシナリオ紹介文等も事前にご準備いただき、ありがとうございます！
情報もまとめられていて分かり易く、とても助かります～。
**シナリオ紹介文について**一点気付いたことがありますので、下記にまとめますね。

Scene0の紹介部分のテキストが400文字以上になっている為、シナリオ紹介文として使用するには文字数が少し多そうかな、と感じました。
既存シナリオの紹介文との兼ね合いもあり、シナリオ紹介文用にもう少し短く250文字程度までにまとめていただいた方が良いかもしれません（※Scene0のテキストは文字数調整不要です）。

お手数をお掛けして申し訳ありませんが、よろしくお願い致します。

**Comment by snext1220** [comment]
@toki-sor1 さん：

> 逆を言えば、happyエンドが存在していない場合は、１の指定も可能なのかな～～

はい、ご認識のとおりでございます！

> Scene0の紹介部分のテキストが400文字以上になっている為、～～

ご案内ありがとうございます。
こちら補足で、New SiteではGitHubからの投稿を案内しておりますが、そちらでは文字数などの制約も明記されているため、以降は、こちらをご案内戴いた方が良いかもしれません。

＃今回、ゲストさん投稿で細かな点の指摘が結構力業になってしまったので；New Site、マニュアル＆以下のIssueにて反映し、なるべく人力を減らしていければと。
https://github.com/snext1220/stext/issues/97
「この辺は何とかしてほしい」など、お気づきの点は、引き続きご意見どうぞよろしくお願いします！

**Comment by olreia** [comment]
ご指摘ありがとうございます。
咲華さんが前説を修正してるのを見てたのに、自分のことはすっかり忘れていました。すみません。
InfoTGDに前説を記載し、TGD44のScene0はそのまま本編の最初のパラグラフにしていただく形で、よろしいでしょうか？

ついでに、とあるシーンを一言だけ修正しました。

[TGD44.zip](https://github.com/snext1220/snext-management/files/2905935/TGD44.zip)

**Comment by toki-sor1** [comment]
@snext1220 さん＞

end属性についてのお返事、シナリオ投稿についての補足ありがとうございます！

> こちら補足で、New SiteではGitHubからの投稿を案内しておりますが、そちらでは文字数などの制約も明記されているため、以降は、こちらをご案内戴いた方が良いかもしれません。

確認しました！　「GitHubからの投稿」は、ログインこそ必要なものの、ファイルサイズの制限もないので、専用フォームからの投稿よりも便利な印象ですね！
今後はゲスト様にこちらをご案内したいと思います～。

> ＃今回、ゲストさん投稿で細かな点の指摘が結構力業になってしまったので；New Site、マニュアル＆以下のIssueにて反映し、なるべく人力を減らしていければと。

確かに……。要確認の箇所など、同一内容であっても都度書き込みとなってしまい、皆さんにお手数をお掛けしてしまったので（汗）、それらが集約された「ここさえ見ればOK！」というページは必要ですよね；
snext1220/stext#97
上記Issueによる書き込みでは、GitHubのwikiが苦手とする部分（最新の書き込みなどが把握し難い等）も補えますので、今後は上記Issueを活用＆ゲスト様にご案内できればと思います。

---
@olreia さん＞

修正ありがとうございます＆お疲れ様です！
こちらこそ前説の長さについて失念し、ご案内が遅くなってしまい申し訳ありませんでした；

最新ファイル、確認しました！　正常に動作しています！
前説の文字数もばっちりです、ありがとうございました～！

> InfoTGDに前説を記載し、TGD44のScene0はそのまま本編の最初のパラグラフにしていただく形で、よろしいでしょうか？
ついでに、とあるシーンを一言だけ修正しました。

はい、前説はサイトのシナリオ紹介文として反映させていただき、Scene0はそのまま本編の最初のパラグラフとして反映させていただきますね！
（前説については、サイト反映時にもしかしたら改行が入ることがあるかもしれません。その場合はサイト編集時に調整しますので、こちらにお任せくださいませ～）

**Comment by Salvadors-cabin** [comment]
皆さん、お疲れ様です。
「金竜の陰謀」公開予定日を連絡しておきます。

3/17 STextウェブサイトでシナリオ紹介を公開 
3/25 シナリオ公開
※予定は変更になるかもしれませんのでご了承願います。
　また、日程のご希望があれば連絡くださいー

最新のTGD44をGitHUBテスト環境にアップしました。
https://snext1220.github.io/stext/index.html?id=gold

よろしくお願いします。

**Comment by snext1220** [comment]
金竜のサイト紹介用に、原作キャプをとってみました。
もし宜しければご利用ください。

![無題](https://user-images.githubusercontent.com/27911337/54484311-0315a800-48a7-11e9-9922-57d286b823ea.png)

**Comment by Salvadors-cabin** [comment]
お疲れ様です。
「金竜の陰謀」紹介文をSTextサイトに公開しましたのでご確認ください。
https://www.web-deli.com/sorcerian/text/

＞リオさん
キャプチャ画像ありがとうございました。
GitHUB環境のstext.xml、キャプチャ画像(intro.png)も更新済です。

では、公開日までよろしくお願いしますー

**Comment by toki-sor1** [comment]
＞ @Salvadors-cabin さん、 @snext1220 さん

STextサイト更新お疲れ様です＆ありがとうございます！
また、キャプチャ画像もありがとうございました！
サイトを確認し、正常に表示されているのを確認しました！

＞ @olreia さん

申し訳ありません……！
こちらの確認不足で、一点修正箇所を見落としていました；；
**Scene 0** に表示される注意文で指定している解放条件（実績）を、下記 **（r1056:slayer&amp;r01:tempest）** のように修正していただけますと助かります；；
```
${if !(r1056:slayer&amp;r01:tempest)}%red%このシナリオを解放するには、Scenario 4「災厄の夜　-テンペスト・ナイト-」の実績（新たなる夜明け）、及びScenario 7「その名はドラゴンスレイヤー」の実績（娘を助けて武器屋を通常営業に戻した）を取得している必要があります！%/%
${/if}
```
シナリオ公開の間近になっての修正依頼、大変申し訳ありません……！
お手数をお掛けしてしまい恐縮ですが、よろしくお願い致しますm(_ _;)m

**Comment by olreia** [comment]
紹介文と画像をありがとうございました！

解放条件がコピペミスになっていたようです。申し訳ありません。
こちらで大丈夫でしょうか？
[TGD45.zip](https://github.com/snext1220/snext-management/files/2975334/TGD45.zip)

**Comment by toki-sor1** [comment]
お手数をお掛けして申し訳ありません。
TGD45.zipダウンロード後、シナリオを拝見致しました。

すみません、先日の修正についてなのですが、xmlファイルの修正を想定した修正文だったため、 **gbatファイル（xmlファイル変換前）の段階での修正文とは異なっていました；**
（gbatファイル変換前から『amp;』があると、xmlファイルに変換した後に『amp;amp;』と二重になってしまうようで……　※添付画像参照）

![image](https://user-images.githubusercontent.com/42646342/54513001-5700b980-4999-11e9-9e97-0e232f8f62e0.png)

お忙しい中、何度もお手を煩わせてしまい、申し訳ありません……！
**変換前のgbatファイル** に下記の文をコピー＆ペーストしていただき、その後 xmlファイルに変換していただけますでしょうか；
よろしくお願い致しますm(_ _;)m
```
${if !(r1056:slayer&r01:tempest)}%red%このシナリオを解放するには、Scenario 4「災厄の夜　-テンペスト・ナイト-」の実績（新たなる夜明け）、及びScenario 7「その名はドラゴンスレイヤー」の実績（娘を助けて武器屋を通常営業に戻した）を取得している必要があります！%/%
${/if}
```

**Comment by olreia** [comment]
ああっ、すみません！
なんとなくおかしいなあ……と思いつつ、確認を怠ってしまいました。
何度もお手数をお掛けして申し訳ありません。
こちらでよろしいでしょうか？
（私がXMLファイルを見るとampが入っていないようなのですが……）

[TGD46.zip](https://github.com/snext1220/snext-management/files/2978545/TGD46.zip)

**Comment by toki-sor1** [comment]
＞ @olreia さん

こちらこそ何度もお手数をお掛けしてしまい、本当に申し訳ありません；；
TGD46.zip内のデータを拝見し、解放条件の注意書きも実績の有無で表示／非表示になることを確認致しました！
お忙しい中、ご対応いただきありがとうございました！m(_ _)m

> （私がXMLファイルを見るとampが入っていないようなのですが……）

おおうっ、確か以前も同じようなことがありましたね；
私の環境下では、メモ帳でも他エディタでも「amp」と表示されているのですが、うーん、環境による違いなのでしょうかね……？

「amp」については、リオさんが解説されているIssue（https://github.com/snext1220/snext-management/issues/7#issuecomment-465823018 ）がありました～。
文字の表示／非表示については私にも原因が分からずなのですが（す、すみません；）、「amp」についてはこちらのIssueをご参照くださいませ～。

＞ @Salvadors-cabin さん

シナリオ公開前の最終更新時に、最新版scenario.xml（TGD46.xml）の反映をよろしくお願い致します！m(_ _)m

**Comment by snext1220** [comment]
`&amp;` については、一般的なテキストエディターであればそのまま表示されるはずですが、（たとえば）XML対応のエディター、あるいはブラウザーなどから参照すると、解釈された結果として「`&`」と見える可能性があります。確実に生のテキストを確認されるならば、メモ帳などのテキストエディターから開いていただけると幸いですm(_ _)m

**Comment by toki-sor1** [comment]
おお、エディターやブラウザ側が「これは表示する必要ないなー」って判断して、ampを&としてしか表示しなかったりすることもあるのですね〜、なるほど……！（早速iPhoneで表示されなくて、こちらをわたわた修正してました）
疑問が解けてスッキリです！ ご解説ありがとうございます！！

**Comment by Salvadors-cabin** [comment]
お疲れ様です。

最新ファイル(TGD46)に更新しましたのでご確認願います。

■GitHUBテスト環境
https://snext1220.github.io/stext/
※プルダウンメニューから「金竜の陰謀」を選択。

■本番環境
https://www.web-deli.com/sorcerian/text/game.aspx?id=gold
※STextサイトからの公開は3/25に予定しています。

よろしくお願いしますー

**Comment by toki-sor1** [comment]
皆さん、お疲れ様です！

＞ @Salvadors-cabin さん

最新ファイルの更新＆ご案内ありがとうございます！
シナリオは、正常に動作していました！
25日はよろしくお願い致します！

---

＞ @olreia さん

シナリオ公開間近に急な修正依頼をしてしまいましたが（大汗）、お忙しい中、迅速にご対応いただき、本当にありがとうございました……！
シナリオ解放条件周りも正常に表示され、エンディングまでプレイできましたことをご報告致します～。

明日は「金竜の陰謀」の公開日の予定となっています。
状況にもよりますが、今までのシナリオ公開時と同じく、大体20～22時頃に王さまbotから告知を行っておりますっ。
ちゃなさんのご都合の良いタイミングにTwitterを覗いていただけましたら幸いです～！

この度は「金竜の陰謀」のご執筆ありがとうございました！！

**Comment by cocotori** [comment]
> ちゃなさん

大変お返事遅くなってすみません・・・！
メモに入っていた

＞cocotori様
エンディングで少々遊んでしまいました。まずいようでしたら修正しますのでご用命ください。

の件ですが、全く問題ありません。うまくつないで頂いてありがたいです。
連作っぽさが出ていいですね・・・！

**Comment by Salvadors-cabin** [comment]
お疲れ様です。
先ほど「金竜の陰謀」を公開しました！
https://www.web-deli.com/sorcerian/text/

よろしくお願いしますー
