### ISSUE TITLE
STextシナリオ「黄泉へ送るレクイエム」

### ISSUE THREAD

**Issue by snext1220** [snext1220/snext-management#11]
感想等の投稿用にスレを立てておきました。
お気づきの点など合わせて、こちらにお願いします。

**Comment by snext1220** [comment]
シナリオ拝見しまして、気付いた点のメモ書きです。
取り急ぎなので、素っ気ない箇条書きになってしまい恐縮ですが、ご確認ください～
＃細かな属性の意味は、こちらを参照下さい。https://sorcerian.hateblo.jp/entry/2018/11/01/211745

+ items、enemies、licence
ダミーのデータが残っているようです。

+ 全体
markdownでは空行で段落を表しますので、段落単位で空行を入れて戴くと、若干見やすくレイアウトされるかもしれません。

+ 全体「hpを●○減らす」など
シーンごとにhp属性がありますので、こちらをご利用いただくと、減算が自動化されます。宜しければご利用ください。

※New Playgroundであれば、個々の項目（レベル）ダブルクリックで、ヘルプページを確認戴けます（一部未対応あり）

+ scene12など
水色の髪（ミドルヘア） ルビ構文がありますので宜しければご利用ください。

+ scene 55、56
end属性ヌケ？

+ scene67
bgm属性 end02 → @end02

+ scene67
「ーーーーーー」→「---」（Markdown罫線）

**Comment by toki-sor1** [comment]
「黄泉へ送るレクイエム」ご執筆お疲れ様でした＆完成おめでとうございます！
あらすじやタイトルをお聞きしてから、どんな物語なのかなと思いを馳せておりましたので、
早速プレイさせていただきました！
一足早くプレイさせていただき、本当にありがとうございます！

今作は原作シナリオ「暗黒の魔道士」クリア後の物語で、ブルードラゴンを筆頭に、悪名高い
ゲディス、そして原作由来のモンスターやアイテムが登場していましたね。
SText初登場となる吟遊詩人のレーナちゃん＆剣士のソティさんが『貴方』と関わり、
「暗黒の魔道士」の舞台で共に新たな物語を彩る様子は、新しさの中に懐かしさも感じて
心が躍りました！

又、作中に「少女は英雄を語りて」の設定（要素）も多く取り入れていただき、始終幸せを
噛み締めておりました！
実績と共に設定をご活用いただき、ありがとうございました！！

1シーン毎の文章量も読み易くまとめられていて、ダイスを振る際のルールもシンプルなので、
物語に集中することができ、非常にテンポ良く遊ぶことができました（シリアスの中でさりげなく
コミカルなシーンが含まれていて、その度にクスッとしておりましたｗ）。

選択肢のあるシーンも、文章中にヒントが書かれていたり、試してみたいと思うコミカルな選択肢を
選んだ後に軌道修正してくれたりと、プレイヤーへの細やかな配慮や優しさを感じました！

バッドエンドも「うわああやってしまった……！　ごめんなさい！」と土下座したくなるものから、
すぅと消えるように終わるもの等、様々な展開があってバッドエンド回収も捗りましたねｗ

レーナちゃんの優しさや行動力に心打たれ、ソティさんを利用するゲディスの卑劣さに歯噛みし、
ブルードラゴンにめちゃくちゃ驚き、ソティさんのレーナちゃんを想う気持ちに胸を熱くし、
そして最後にタイトルの意味を理解して、一つの大きな冒険を終えた達成感を得ると共に、
とても晴れやかな気持ちになりました！
レーナちゃんの「吟遊詩人」という職業が、ゲーム性にもストーリーにも最大限に活かされている
ところも素敵でしたね！

ドラゴンモードは、各執筆者様の「ドラゴン」の描き方を拝見できるところも魅力で、今作は
ブルードラゴンの描き方にも注目しながら拝読していました。
そしてブルードラゴンの設定・エンディング前のやり取り・エンディングと、今作の「ドラゴンと
ソーサリアン（人間）」の関係を拝見し、私の中でまた一つ世界が拡がり、「ドラゴン」という
存在の更なる魅力に気付くことができました！

この度は、素敵なシナリオをご執筆いただき、本当にありがとうございました！
ドラゴンというテーマの奥深さはまさに「沼」ですね……！

シナリオを遊ばせていただき、下記に気付いたことをまとめました。
既に修正済みのものや、私が勘違いしているもの、咲華さんの方針に合わない意見等はスルーして
やってくださいね。

お忙しいところ恐縮ですが、引き続きよろしくお願い致します！

---

- 「r01～r05」までの実績が各Scene内に設定されていないようです（現バージョンでは取得不可）。

- Scene7
  選択肢の「2～5」と「1か6」は、右と左のダイスでどちらの数値を参照するのか等の説明があると、更に分かり易いかもしれません。

- Scene15　空白があるようです。
  「信じてもらえないかもしれないのですが、どうやらソティは邪悪な魔導士の思念体に憑り『　』つかれているようなのです。

- Scene15　「Scene18」へ進める選択肢が無いようです。

- Scene22
  本文の指示と選択肢で表記が若干異なっているのですが、どちらかに統一した方が見易い（意図が分かり易い）かもしれません。
＜ダイスを振って、１『－』３か４『－』６かで判定してください＞

  こちらについても、右と左のダイスでどちらの数値を参照するのか等の説明があると、更に分かり易いかもしれません。

- Scene40、Scene 42
  右と左のダイスでどちらの数値を参照するのか等の説明があると、更に分かり易いかもしれません。

- Scene47、Scene61　時機→直（じき）？
  『この音とあの太陽の石が共鳴しておる。身体がもう少し弱れば『時機』浄化されるであろう』
  『大丈夫だ。魔力が切れただけで『時機』に回復する。我も魔力を送るが故安心するがよい』
    ※Scene50の「時機に彼を封じた魔導士の子孫」の『時機』はそのままで。

- Scene52
  右と左のダイスでどちらの数値を参照するのか等の説明があると、更に分かり易いかもしれません。

**Comment by Salvadors-cabin** [comment]
「黄泉へ送るレクイエム」をGitHUBテスト環境にアップしました。
https://snext1220.github.io/stext/index.html?id=requiem

＞咲華さん
DMでも連絡しましたが、解放条件の記述を修正しました。
最新のファイルを添付します。
[scenario.zip](https://github.com/snext1220/snext-management/files/2872636/scenario.zip)

**Comment by AyakaLinkyo** [comment]
ご指摘、ご感想ありがとうございます！
ドラゴンとの在り方については書いている間ずっと悩んでおり、書き終えた後も皆さんに受け入れていただけるか不安だったのですが、そう言っていただけてとても嬉しいです。

遅くなってしまいましたが、ご指摘いただいていた部分を修正させていただきました。
お忙しいところ恐れいりますが、よろしくお願いいたします。

[scenario.zip](https://github.com/snext1220/snext-management/files/2881007/scenario.zip)

**Comment by toki-sor1** [comment]
こちらこそ、お返事ありがとうございます！
咲華さんにとって「黄泉へと送るレクイエム」は、シナリオのご執筆中に悩まれ、そして導き出した「ドラゴンとの在り方、その答え」でもあるのですね。
私の感想が咲華さんの不安を打ち消す要因の一つであったこと、とても嬉しいです！

早速シナリオも修正いただき、ありがとうございます！　お疲れ様です！
現在、私のシナリオ確認環境に問題があるのかを確認中なので、下記の箇所については確認後に改めてお知らせ致しますね。
（下記以外の確認済み修正箇所は、問題ありませんでした！）

- 動作、表記の確認中
  -  Scene0の新構文
  - 「r01～r05」までの実績が各Scene内に設定されていないようです（現バージョンでは取得不可）。
---
ご不便をお掛けしてしまい申し訳ありませんが、お先にwikiの【シナリオ公開前の準備】（https://bit.ly/2Sznoog ）をご参照いただき、シナリオの紹介文等の準備をお願いできますでしょうか？

（紹介文や画像等は、こちらに書き込んでいただいたり、ファイルを添付していただいたり、サルバさんにお送りいただいたりと、咲華さんのご都合の良い方法にてお願い致します）

ご不明な点などございましたら、気兼ねなくお問い合わせください。
お忙しいところ恐縮ですが、引き続きよろしくお願い致します。

**Comment by toki-sor1** [comment]
連続投稿、失礼致します。

> 現在、私のシナリオ確認環境に問題があるのかを確認中なので、下記の箇所については確認後に改めてお知らせ致しますね。

こちらの件ですが、メンバーさんと確認したところ、Scene0の新構文については問題ありませんでした。
実績については、「r01～r05」までの実績が各Scene内に設定されていないようでした。

お手数をお掛けして申し訳ありませんが、「r01～r05の実績を取得するシーンに実績の指定」をお願い致します。
```
<scene id="○○" result="r01">
```

**Comment by toki-sor1** [comment]
か、重ねてすみません……私自身、シナリオの確認で失念していた箇所があり、大変恐縮なのですが……加筆をお願いしてもよろしいでしょうか？（汗）

エンディングが綺麗に終わっていたので、爽やかな気持ちでテストプレイを終えていたのですが、ドラゴンモードではキングドラゴンを斃すまでペンタウァは混乱の最中にあるので、現状のエンディングに「ペンタウァが未だ平和ではない様子」や「まだドラゴンが残っている」等の要素を加筆（修正）していただけますと助かります……！（大汗）

こちらの確認不足でご迷惑をお掛けしてしまい、申し訳ありません……！  本当に情けない限りで……；；
公開日が迫る中での加筆（修正）のお願いとなってしまい、大変恐縮ではございますが、どうかよろしくお願い致します；；

**Comment by snext1220** [comment]
お疲れ様です。

> Scene0の新構文

につきまして、若干理解しづらい点がありましたので（スタッフ内のＤでも議論いただきありがとうございました）、共有のため、 #7 で補足説明させていただき来ました。ご確認くださいませm(_ _)m

**Comment by AyakaLinkyo** [comment]
お疲れ様です！
シナリオの紹介文に関してと、実績の追加は後程あげさせていただきます。

エンディングの加筆なのですが、下記のようにしてみました。
いかがでしょうか？



それから数日が過ぎた。

―――ん？

未だに混乱が続いているペンタウァで依頼をこないている貴方のもとへ一通の封筒が届いた。


拝啓　ソーサリアン様

以前は助けていただき本当にありがとうございました。

私もソティも今では体調もよくなり、何事もなく暮らすことが出来ています。

さて、あの日から考えていたことがようやく実行させていただくことが出来ましたので手紙を出させていただきました。
償いの大きな一歩になれると、そう信じています。
そして未だ平和が戻らないペンタウァの方々の力になれればと願っています。

そこに是非、貴方様にお越しいただきたいです。

御都合が合いましたらよろしくお願いいたします。


レーナ



その手紙と一緒に、演奏会の招待状も入っている。

ペラリ

―――ん？

一枚、紙が床に落ちた。

何かと思い拾うと、そこには……


『ブルードラゴンさんのいる、黄泉まで届くように奏でます』


―――そうか。

それはきっと、彼も喜ぶだろう。


貴方はその紙を招待状に挟むと、椅子に座り、引き出しから便箋を出した。
そして、ペンを握り、便箋に走らせる。



手紙ありがとう。演奏会を楽しみにしています―――




TRUEEND
黄泉へ送るレクイエム

**Comment by toki-sor1** [comment]
皆さん、お疲れ様です！

**＞リオさん**
[CDATA[～]]について、ご丁寧なご解説ありがとうございました！
仕様を#7 にて確認致しました！　なるほど、そういうことだったのですね！
ちゃなさんの「金竜」でもこちらに関係する修正点を挙げておりましたので、GBATの仕様に合わせて修正点の説明を修正しました。

こちらこそGBAT2SText、New Playgroundの仕様を把握しておらず、お騒がせしてしまい申し訳ありませんでした；；

**＞咲華さん**
ご多忙中に加筆をお願いする事態となり、ご迷惑をお掛けしてどうもすみません……！
早速のご対応ありがとうございました……！！

エンディングの加筆部分を拝読しました！　内容ばっちりです、ありがとうございます！！
拝読していて気付いた下記の一点のみ、ご確認をお願い致します。

- 未だに混乱が続いているペンタウァで依頼をこな『い』ている貴方のもとへ一通の封筒が届いた。

シナリオ紹介文、実績の追加についても承知しました！
引き続きよろしくお願い致しますm(_ _)m

**Comment by AyakaLinkyo** [comment]
実績r01～r05を取得できるように修正しました。
また先ほどのエンディングも加筆させていただいたものに差し替えました。

よろしくお願いいたします！
[scenario.zip](https://github.com/snext1220/snext-management/files/2889664/scenario.zip)

**Comment by AyakaLinkyo** [comment]
連続投稿失礼します。
シナリオ紹介文等、こちらに載せさせていただきます。

＜シナリオ紹介文＞
―――悪魔に魂を売り渡した暗黒の魔道士がいた。
彼は悪しき力を使って、黄泉の国から邪悪なモンスター達を召喚し、ペンタウァの王国を我が物にしようと国はずれの洞窟にて企んでいた。
しかしそれはソーサリアンと魔導士のライバルだった男性によって阻止され、召喚されていたモンスターたちも黄泉の国へと再び送られた。

それから年月は経ち。
奇しくもその洞窟近くにて多くの邪悪なモンスター達の目撃が相次いで報告されるようになった。中には怪我人も出ている。
何の前触れもなく急なことで対処も討伐も間に合っていない。不思議なことにモンスターたちは倒せど倒せど一向に減らないという。しかも中にはあの「狂暴かつ邪悪な青竜」までもが潜んでいるという噂だ。

幸いにも死人はまだ出ていないが、このままではペンタウァの人々の命が危ない。
更になんと少し前、洞窟に若い剣士の男性が、その少し後に娘が、それぞれ入っていったとの情報も入ってきていた。

ソーサリアンよ、名だたる勇者よ。
急に現れ出したモンスター達の討伐、及び原因の追究を至急お願いする。
剣士と娘が入っていったとの情報が事実だった場合、彼らの保護も頼みたい。
ペンタウァの人々の平穏をどうか取り戻してくれ―――！


＜シナリオ情報＞
＊分類：暗黒の魔導士、ダンジョン探索
＊シリーズ：連作ドラゴンモード
＊シーン数：68
＊難易度：おまかせします💦個人的には2～3くらいだと感じております。
＊公開日：2019/02/25
＊作者より
ゲームブックシナリオを書くのは初めてで、終始ワクワクドキドキしながら作っていました。
この竜を選んだのは私がソーサリアンにハマったきっかけの竜であり、シナリオだったからです。
別名「暗黒の魔導士・後伝」……になっていたら嬉しい限りです。
こんなドラゴンとソーサリアンの関係もいかがでしょうか？


よろしくお願いいたします～
※画像はこちらに添付させていただきます
![intro](https://user-images.githubusercontent.com/26947882/53178645-999ed280-3635-11e9-901f-c2d4966c58e1.png)

**Comment by snext1220** [comment]
@AyakaLinkyo さん＞修正、紹介文等ありがとうございます！

さて、シナリオ／紹介文について、最後の最後まで恐縮ですが、いくつかお願い＆申し送りでございます。

+ 紹介文ですが、すみません、現状500文字以上になっているようでして、他シナリオとのバランス的にもう少し短くしておきたく。250文字程度までに収めて戴いても宜しいでしょうか。
+ items、enemies、licenceにダミーが残っているようです。特にlicenceはエンディング後にダミーデータが出力されてしまうため、削除をお願いいたします。
+ hp属性で「-1」して戴いていますが（ありがとうございます！）、本文が「hpを1減らす」のようになっているところがあり、手動で減らすのかと誤解されそうに思えました。一部は、「～減った」のようにされているので、統一戴いた方が良いかもしれません。
+ 難易度は結構適当なのですがｗ、他シナとの兼ね合いで「2」で設定させて戴きますね。

ざざっと拝見したため、十分に細部確認できていない可能性がありますが；；、25日正式公開しましたら、またTLの方で賑やかしがてらに?感想など流させて戴きますね。

ではでは、引き続きよろしくお願いいたします！

**Comment by snext1220** [comment]
@toki-sor1 さん＞

> こちらこそGBAT2SText、New Playgroundの仕様を把握しておらず、～

いえいえ、新規構文はリリース以来、混乱のもとになっており、申し訳ありません；；
こうしたご質問も掲示板で揮発させずに、マニュアル充実の糧にできればと思っていますので、引き続きよろしくお願いいたします～

ちなみに、本件については、あまりシステム的な詳細に踏み込むのも却って混乱のもとなので、現時点での「GBAT2SText、New PlaygroundではCDATA不要、エディターのみCDATAで」ママとできればと思っていますが如何でしょう？（エディターでも`&amp;`で回避はできますが、たぶん見にくくなるので、あくまでXMLに詳しい?人の裏技扱い）

**Comment by AyakaLinkyo** [comment]
先んじて、シナリオ紹介文の修正文だけ投稿させていただきます！

―――悪魔に魂を売り渡した暗黒の魔道士がいた。
彼はペンタウァを我が物にしようと国はずれの洞窟にて企んでいたが、ソーサリアンと魔道士によって阻止され、召喚されたモンスターたちは黄泉へと送られた。

それから年月は経ち。
奇しくもその洞窟近くにて多くのモンスターが続出した。中には怪我人も出ている。
このままではペンタウァの人々の命が危ない。

ソーサリアンよ、名だたる勇者よ。
急に現れ出したモンスター達の討伐、及び原因の追究を至急お願いする。
ペンタウァの人々の平穏をどうか取り戻してくれ―――！


以上になります
よろしくお願いします！

**Comment by toki-sor1** [comment]
@AyakaLinkyo さん＞
お疲れ様です！
シナリオの修正、シナリオ紹介文のご投稿と修正、そして画像の添付もありがとうございました！
紹介文の長さもばっちりです！
サイトに「黄泉へ送るレクイエム」の紹介ページが掲載されましたら、改めてご連絡致しますね～。

こちらこそ、引き続きよろしくお願い致します！

@snext1220 さん＞
お疲れ様です！　シナリオのご確認ありがとうございました！

> 現時点での「GBAT2SText、New PlaygroundではCDATA不要、エディターのみCDATAで」ママとできればと思っていますが如何でしょう？

はい、混乱回避ということで、こちらままで良いと思います！

> （エディターでも`&amp;`で回避はできますが、たぶん見にくくなるので、あくまでXMLに詳しい?人の裏技扱い）

そうですね、こちらは慣れた人やXMLに詳しい人向けということで、裏技扱いが丁度良いかなとｗ

**Comment by AyakaLinkyo** [comment]
ダミーデータの削除、及び、本文を「～減った」と統一させていただきました。
ギリギリになってしまいましたがよろしくお願いいたします。
また、 難易度の件も了解しました。ありがとうございました！

[scenario.zip](https://github.com/snext1220/snext-management/files/2897507/scenario.zip)

**Comment by Salvadors-cabin** [comment]
咲華さん

最新ファイルをGitHUBテスト環境にアップしました。
https://snext1220.github.io/stext/
※プルダウンメニュー（シナリオを選択してください）から選択可能になっています。

あと、DMでもご連絡しましたが、シナリオ紹介をSTextサイトに公開しています。
https://www.web-deli.com/sorcerian/next/stext.aspx

よろしくお願いします。

**Comment by AyakaLinkyo** [comment]
ありがとうございます！
了解しました

**Comment by toki-sor1** [comment]
@Salvadors-cabin さん＞

更新作業等お疲れ様でした！
GitHub、STextサイト共に表示も問題ないことを確認しました！
明日はよろしくお願い致します！

@AyakaLinkyo さん＞

シナリオの最終調整お疲れさまでした！
GitHubにて動作確認を行い、正常に動作することを確認致しました。
お忙しい中、ご対応いただきありがとうございました！

明日は「黄泉へ送るレクイエム」の公開日ですね！
状況にもよりますが、いつも大体20～22時頃に王さまbotから告知を行っております。
咲華さんのご都合の良いタイミングにTwitterを覗いていただけましたら幸いです(=´ω`=)

この度は「黄泉へ送るレクイエム」のご執筆ありがとうございました！！

**Comment by cocotori** [comment]
遅ばせながらシナリオ、プレイさせていただきました。
ホントに滑り込みもいいところで、すみません・・・！

どことなく明るさがあり、冒険を楽しんでいるような雰囲気が、
緊張感のあるシナリオが多い中で
いい感じにスパイスになっていると思いました。

ノーマルエンド、トゥルーエンドともにクリアさせていただきました。
ドラゴンと人との関係。
ほんとそれが作者さんごとに違ってて、
ドラゴンモードならではのらしさが出てていいなって思いました！
よきドラゴンであっても、戦わなくてはならないシチュエーション。
涙を飲み込みつつ、全力で戦わせていただきました・・・！

そして最後のタイトル回収、好きです。
どうかその音色が、黄泉の国の彼に届きますように・・・

執筆お疲れ様でした！
