### ISSUE TITLE
【意見・報告】STextときのじシナリオ全般

### ISSUE THREAD

**Issue by toki-sor1** [snext1220/snext-management#14]
ときのじ（@toki-sor1）のシナリオ全般の話題を扱うIssueです。
SText各シナリオ専用IssueはCloseするので、このIssueでは作者のシナリオ全般を扱います。
シナリオへのご意見や不具合報告等にご利用ください（個人メモとしても扱う予定です）。

#### 担当シナリオ（ユーティリティ）のタイトル

- Scenario 5「少女は英雄を語りて」
- Scenario 10「魂の選択」
- Scenario 15「常闇から来たる影」
- Utility 5「STextシナリオ開発道場」

**Comment by toki-sor1** [comment]
＞@RYU-DS さん

この度は、「常闇」を遊んでいただき、貴重なご意見やご感想ありがとうございます！（https://twitter.com/ishikawanonoich/status/1106598370204803072 ）
今回は勝手ながら、返信の場をこちらに移動させてしまい申し訳ありません。
しかし、Twitterだと連投リプになってしまったり、文字数制限により言葉足らずな返信になってしまいそうなので（汗）、この場にてお返事を書いていきたいと思います。

---

### Scenario 15「常闇から来たる影」

> 最初から5が表示されて「エレベーターの部屋に戻る」を押しても、さらに4が表示されるだけで、4の「エレベーターの部屋に戻る」を押すと3へ戻れて、何回やってもこう。

あわわ、不具合のご報告ありがとうございます……！
「常闇」公開後にPlaygroundでフローチャート生成が実装されて動作確認をしていたところ、「序盤のSceneが1つ抜けてる！？」と気付き、Sceneを割り振り直したりしていたのですが、すみません、修正し切れていませんでした……（大汗）

**本日、ご指摘のシーンの繋がりを修正致しました！**

> しかしこのシナ、俺にはちょっとわからない「？」な所が多く、もしかしたらこれで合ってるのかもしれん…

Free欄の数値から、今回は「通常ルート」の攻略であったとお見受けしました～。
「常闇」のシナリオ解放条件が「ゼロの創造」なので、ストーリーの各所に「ゼロの創造」の要素を取り入れています。
**「ゼロの創造」のシナリオクリア実績所持で分岐する別ルート** では、もしかしたらRYUさんの疑問も少し晴れるかもしれませんｗ

＃シナリオ内に別ルート分岐のヒントを入れていたのですが、現STextではどうも上手く表示されていないようなので、 **原因特定後に該当箇所を修正予定です。**

> どう見ても「本体」と「攻撃」なんだけど注釈が無い。
stextの基本戦闘ルールに則ると好きなのを順番に潰していくだけでよく、他からの攻撃も受けないんだが…

ご指摘ありがとうございます！
攻撃順の指定がないので、まさにこれは「マンティコア（本体）斃したのに、攻撃だけ当たるのおかしくない？」という矛盾した戦闘になっていましたね；

私もシナリオやゲームブック等のルールでは、「この解釈で合ってるかな？」と不安になることがあるので、**設定側のルールにちゃんと従えているか？** というプレイヤー側である時の気持ちを忘れずにルールを設定し、説明を書くことを意識しないとですね。気をつけねば……！

説明の例文もありがとうございました！
**例文を参考に、マンティコア戦があるシーンに以下の「戦闘ルール」を追加しました！**
＃以下のルールは、強化版マンティコアのものです
```
　戦闘ルール
　この戦闘では、「鋭利な右爪」から一番下の「巨大毒針（大）」
　までの攻撃を行った後でなければ、「マンティコア」へ攻撃する
　ことができないものとする。

　なお、「マンティコア」以外の箇所については、自由な順番で
　攻撃を行っても良い。
```

> このシナは欠片を結構入手するので使用可能魔法が多く、その選択を迫られる。
そうなると効果もはっきりしていないと困るもので…今回はプロテクトとホーリーウォーターの効果時間が決まっておらず、結局使わなかった（使えなかった）。
普通に1回かと思うけど、原作では一定時間効果があったし…

はいー、シャドードラゴン戦に向けて「七惑星の欠片」は多めに入手できるよう設定しています～（迷宮でも稼げるようにしています）。

魔法の効果ですが、シナリオ独自の使い方をしている際にはシナリオ内に説明を入れているものの、通常使用する場合には、現在のステータスの表記では確かにちょっと判断に迷ってしまうところがありますね。
人によって解釈が異なったまま遊んでいる可能性もあるので、 **ステータスの魔法に関する説明文は、今よりも詳しく表記する必要があるかもしれません。** （@snext1220 さん、如何でしょうか？）

> またなんか文句ばっか言ってる感じだけど、公開から一定時間が経っているのにこうって事は誰も指摘していないからであって、こういうのは作る側にとって大事なのでプレイヤー側として割り切って言ってます。
「俺の好きなシナリオに文句つけてんじゃねぇー！」とお怒りの方も、真に想うなら言いましょう

うっ、うっ、RYUさん……！　いつもありがとうございます……！！（感動で目頭が熱くなるときのじ）
STextも1周年を迎えましたが、シナリオ公開後に要改善点や不具合報告などが寄せられることはほぼない状態なので、RYUさんの **「シナリオに改善点があれば、執筆者が今後より良い作品が作れるように改善すべき個所をがっつり教えてくださるスタイル」** は、本当に感謝の気持ちでいっぱいです！

> でも作者ツイッターに直接言うのもアレだし、自ツイで言うにしてもネガティブな事は言いづらいのも確かだから、やっぱ掲示板要るかな？
不具合報告とかシナ別に分けたりして。匿名性が必要な気がする…
話がそれた、まだ続くぞ（やめて！とき○じのHPはもう0よ！）

伏字ｗ　ご感想をいただけて寧ろHPが回復してきましたｗ　……という、ときのじならぬえむのじはさておきｗ
私個人も「意見や不具合報告できる場所」は必要かな～と思い、今回は試験的にこのIssueを立ち上げてみました。
欠点は **「1.匿名ではない」「2.GitHubアカウント必須」** というところで、さらに言えば **「3.Twitterとは違い、他のプレイヤーさんがこの話題を目にする機会が少なくなる」** のも悩ましいですね。
＃@snext1220 さんは、「3」を意識されているご様子でなるほどなぁ～、と！

「匿名性があって誰でも気軽に不具合報告等ができる方法」については、 **まず必要かどうかの議論を重ねて、必要となったら実装方法を考えていきたい** ですね。

> 結局なんだかんだで１トライでクリアできたんだけど、今回も痛感したのが…
「偶数奇数で大きな判定をするのは非常に荒くて、結果キツイ」という事。

RPGやSLGゲームにおける「命中率」は、キャラクターの各種能力値や装備品の性能等を参照して計算しているのに対し、「ダイス値が奇数か偶数かによる判定」は、完全にプレイヤーのリアルラック任せですもんね……；
シナリオ難易度がリアルラックのみに左右されるシステムというのは、そういうシステムで成り立つゲーム以外ではただ理不尽なだけ（＝ストレスのもと）なので、 **これは次の作品で改善したいです！**

---

ひえぇん、長文になってしまいました……！（大汗）

RYUさんからご感想やご意見をいただき、自分がいかに「執筆者だけがルールを理解し、説明を怠っているか」「運ゲーシステムで難易度を上げているか」を痛感しましたが、それと同時に改善すべき点が明確になり、とても勉強になりました！
改めて、この度はシナリオ執筆者の視点とプレイヤーの視点で、様々な貴重なご意見やご感想をありがとうございました～！！
＃ご返信はどうかお気になさらずにです～。

**Comment by snext1220** [comment]
ご対応お疲れ様です～まずは、ご指名戴いた箇所です！

> ステータスの魔法に関する説明文は、今よりも詳しく表記する必要があるかもしれません。 

とりあえず以下の「魔法ルール」に追記しましたが、如何でしょうか（認識合ってますかね^^;）。
https://sorcerian.hateblo.jp/entries/2017/12/20

> ＃@stext1220 さんは、「3」を意識されているご様子でなるほどなぁ～、と！

SText、遊んでくださってる方はそれなりにいるようなのですが、言及がないのはやはり寂しいなぁと；そんなわけで、せめてものにぎやかしになればと…！

**Comment by toki-sor1** [comment]
＞@snext1220 さん

早速のご確認＆ご対応ありがとうございます～！

> とりあえず以下の「魔法ルール」に追記しましたが、如何でしょうか（認識合ってますかね^^;）。

マニュアル確認しました！　はい、良いと思います！
ただ、 **マニュアルのみだと参照していただけない可能性もあります** ので、更に **ゲーム内の魔法リストの説明** にも、効果範囲（持続時間）について追記できれば良いなと思いました～。
文字数制限もあって簡潔にまとめるのが難しいとは思うのですが……；

> SText、遊んでくださってる方はそれなりにいるようなのですが、言及がないのはやはり寂しいなぁと；そんなわけで、せめてものにぎやかしになればと…！

微妙にアカウント名を間違えてしまってすみません；；（いつものクセでついstextに……）
そうですね、感想を書くこともハードルが高いのですが、意見を書くというのは更にハードルが高いものだと思いますので、なかなかプレイヤーさんのお声がお聞きできないのも仕方がないのかなとは思うのですが、その一方で、やはりゲームとして開発し、シナリオを書いていると、色んなご意見をお聞きできれば……と考えてしまうんですよね；

今回はこちらのIssueを利用しましたが、「あっ、気軽に声を掛けてもいいんだ」と皆さんに気付いていただける環境づくりも大切ですよね。
私もTwitterとIssueは、内容によって使い分けていきたいと思います～。

**Comment by snext1220** [comment]
> ゲーム内の魔法リストの説明 にも、効果範囲（持続時間）について追記

こちらですが、とりあえず対応してみました。
もともとSTextにはターンという概念はないので微妙なんですが^^;、短くまとめるとしたら、このくらいかなと；如何でしょうか？

> 微妙にアカウント名を間違えてしまってすみません；

ドンマイです^^; GitHub上であれば、補完が効きますのでご利用くださいｗ

> なかなかプレイヤーさんのお声がお聞きできないのも仕方がないのかなとは思う～～

ですね～自分を振り返ってみても、普段、感想を言い合っている仲以外で言及するかというと皆無なので^^;（匿名でもまずしないですね…）
環境づくりについては、以前のコメント機能でもありましたが、長所短所ありだと思いますので、ゆるゆる検討してまいりましょう～

> 「ダイス値が奇数か偶数かによる判定」は、完全にプレイヤーのリアルラック任せ～

こちらの判断は、本当に難しいですよね…：

個人的には、ドラゴン戦闘の一演出としては、十分ありだったのかなと（ラック任せという意味では、ラストバトル直前にセーブを促す文言があるとベター？）。難易度としても、ワントライでギリクリアできるバランスは、実は絶妙だったのでは、とも思いますしｗ
＃こればっかりだと疲れてしまいますが、今回は連作全体でさまざまなアプローチがあるので猶更^^;

結局は、すべてが運と思わせない程度に分岐を交えつつ、**ダイス判定も**織り交ぜていく、その辺のバランスだと思いますが――引き続き悩んでまいりましょうｗ

**Comment by toki-sor1** [comment]
### ゲーム内の魔法リストの説明

早速のご対応ありがとうございます！
今まで「ターン」という表現がなかったので最初は「ん？」となるかもですが、そこをマニュアルで補っているのでばっちりだと思います！

### アカウント名の補完

どもです～；；
実は今までも補完機能そのものは知っていて、利用していたこともあったのですが、半角スペースを入れることをうっかり失念していて「あれ～？」と首を傾げていました；

### 感想・感想を伝える環境づくりについて

はい～、私も言及するかどうかはお相手の方による、という感じですね～。
（例えば、Next計画関係者の皆さんの場合は、共同開発している仲なので感想以外に意見もお伝えし易い等）
環境づくりについては仰る通り、それぞれに長所短所があるので、ゆるゆる検討了解です～！

### 「常闇」のダイス判定について

おぉお、ご感想＆ご意見ありがとうございます～！

ドラゴンモード本編Vol.1ということで、一番手のドラゴン戦をしょぼいものにしたくないという一心でルールを考えていましたが、公開から時間が経ち、皆さんからご感想・ご意見をいただいて、改めてルール作成やゲームバランス調整の難しさを痛感しておりました；

難易度緩和のために入手できる欠片の数を多めに、回復アイテムは必ず入手、進行有利ルートは武具の充実、中間地点にセーブポイントを設けたりしていたので、ワントライでギリクリアというのも、そういう調整が上手く作用してくれたのかなと、と思いました。
こういうフォローは引き続き入れていこうと思います！（ラストバトル直前にセーブを促すのもいいですね！）

ただ、シナリオ作成時には気付かなかったのですが、振り返ってみると **「ターン数の制限」と「ダイス値が奇数か偶数かによる判定」は抜群に相性が悪かった** ですね；
ルール作成時は、ルールを個々に見るのではなく、複数のルールを総合した際のバランスや相性も考えないといけないなぁ、と本当に勉強になりました！

「常闇」も課題の多い作品ですが、同一のテーマで色んなシナリオが楽しめる連作の中のドラゴン絶対スレイヤーマンなシナリオとして、皆さんに楽しんでいただけていたら嬉しいですねｗ

> 結局は、すべてが運と思わせない程度に分岐を交えつつ、ダイス判定も織り交ぜていく、その辺のバランスだと思いますが――引き続き悩んでまいりましょうｗ

まさにその通りだと思います！
はい～、今後もより良いバランスを探るべく、引き続き悩んでいきたいですｗ
