### ISSUE TITLE
シナリオ制作質問箱

### ISSUE THREAD

**Issue by snext1220** [snext1220/snext-management#16]
シナリオ制作／投稿時に発生した問題（うまく動かない／この機能どう書いたらいいか判らないなど）を質問投稿するためのスレです。バグかも、という内容も、こちらでお願いします。ご質問に際しては、問題特定の為、**詳細なエラー内容、及び、元ソース（scenario.xml／.gbatファイル）の添付**をお願いします。

主に、ゲストさん向けのスレですが、もちろん、スタッフの皆さまが利用されるのも歓迎です。

また、回答は誰が、というものではありませんので、是非**お答えいただけるものは積極的に回答**いただけますと幸いですm(_ _)m

※以前からご利用されていた皆さまへ＞
Stext issueで、もともと［Question］［Bug］としていたものの後継です。Stext Issueの方では、機能改定との切り分けが曖昧になって、イマイチ使われていませんでしたので、こちらでスレを立ち上げました（Bugでシステム対応の必要なものは、私の方で適宜Stext issueに移動させていただきます）。

**Comment by RYU-DS** [comment]
困った事に第三部のGBATデータがプレイグラウンドで動作しなくなってしまいました。
画像のフロチャの1桁数あたりの部分で基本的な動作をチェックした時は動作したのですが、その後全シーンを組み込んで試した所動作せず（次の画像のようにシーン1の文字すら出ず）…
さらに恐ろしい事に、不要な1桁部分等をlinkにして、動作していた他のデータと統合して読み込んでも動作しなくなります。
エラーが出ないので、自分で考えられる所は全てチェックして直しましたがダメでした。
シーン１の重複的なものかと思うのですが、第三部データのシーン1をlinkにしてダメなので自分的にはお手上げです。
SGML化したデータを見てもらって、どこがおかしいか見てもらえませんでしょうか？
[第三部GBAT.zip](https://github.com/snext1220/snext-management/files/3075999/GBAT.zip)

**Comment by snext1220** [comment]
現在、STextに展開できる環境でないため、テキストのみの確認ですが、戦闘式に含まれる`<`が悪さをしているように見えます。左辺右辺を逆にして`>`で差し替えて戴くと如何でしょうか。

**Comment by RYU-DS** [comment]
動作しました…お騒がせを…いやこれはわからんわ………

**Comment by RYU-DS** [comment]
複合条件式がうまく機能しません。
@f1251&!f3001
のような２つでかつ否定「!」が１つしか入らないものは機能しますが…※画像1、シーン3000
@!f3008&!f4200
のように否定が２つ入ると正常ではない選択肢として表示され、カーソルを合わせると2つ目の「!」がNOTとして認識されていないようなのですが…※画像2~3、シーン3300

![混合おｋ](https://user-images.githubusercontent.com/43634197/56083723-e350b000-5e63-11e9-81e0-f0c8e92061ab.PNG)
![SN3J5653](https://user-images.githubusercontent.com/43634197/56083761-670a9c80-5e64-11e9-9ba1-db486dd3d749.JPG)
![SN3J5652](https://user-images.githubusercontent.com/43634197/56083765-74278b80-5e64-11e9-93cf-1e35e048ef47.JPG)

**Comment by RYU-DS** [comment]
多いので分けます。次に4002と4009に行くとエラーが出て止まり、ブラウザの戻るで戻ってF5＞再ファイル読込＞実行＞続きから、でそのシーンから再開して動作はできるのですが…
2つのシーンの共通点として大文字と未設定bgmは消してみましたがダメでした。残りの複数条件式選択肢かと思われるのですが、再開でresultが消えてしまうので確認できません。
![e404](https://user-images.githubusercontent.com/43634197/56083934-9f12df00-5e66-11e9-863d-0025e53f94aa.PNG)

**Comment by RYU-DS** [comment]
次にテキストの条件表示も、「|」を使うとダメなようです。
シーン3186のGBAT※画像１を実行するとフラグ条件に関係無く必ず画像２の状態になります。
このシーンは画像３のように対応しましたが…
![｜不可？１](https://user-images.githubusercontent.com/43634197/56084047-755ab780-5e68-11e9-9740-2da0e3a9cc3b.PNG)
![｜不可？２](https://user-images.githubusercontent.com/43634197/56084052-7db2f280-5e68-11e9-8cb5-9e718f93d467.PNG)
![｜不可？対応](https://user-images.githubusercontent.com/43634197/56084056-899eb480-5e68-11e9-9847-d2493a6a45bb.PNG)

**Comment by snext1220** [comment]
お手数ですが、現時点での最新のscenario.xmlをUp戴いて宜しいでしょうか。
以下、昨日時点でのテキストで確認した範囲です（目確認なので、微妙に自信なし）。

+ 「!」複数については、「!(f3008|f4200)」では如何でしょうか。
+ scene4002についてはフラグが登録されていないようです（なんか全体として少ないので、かなり抜けているように見えます）。
+ ${if}内の「|」についてはバグです（すみません）。ルビ機能とバッティングしていますね...検討しますが対応まで時間がかかりそうなので、まずは逃げの方向でご対応頂けますとm(_ _)m

**Comment by RYU-DS** [comment]
とりあえずGBATとSGML送ります。

・「!」複数については、「!(f3008|f4200)」では如何でしょうか。
「!」複数ができないのは仕様という事でしょうか？

・scene4002についてはフラグが登録されていないようです（なんか全体として少ないので、かなり抜けているように見えます）。
前回送ったものは色々試して消した後のものでしたが、元々＆現状必要なフラグは仮登録＆得るシーンを作ってあり、それらは他のシーンでは機能していますが…

・${if}内の「|」についてはバグです（すみません）。ルビ機能とバッティングしていますね...検討しますが対応まで時間がかかりそうなので、まずは逃げの方向でご対応頂けますとm(_ _)m
わかりました、がマニュアルに記載が無いとできる前提で作ってしまうので、できない事の記載は他もすべてお願いします。
[第三部GBAT20190414.zip](https://github.com/snext1220/snext-management/files/3077144/GBAT20190414.zip)

**Comment by snext1220** [comment]
「!」については、現時点では不明なので、まずは単一パターンで逃げて戴けますと（調査に時間がかかりそうなので、ご了承ください）。その他の件についても判ったものから回答いたしますが、お時間戴けますと。

> できない事の記載は他もすべてお願いします。

こちらはできるだけ努めてはいるつもりなのですが、条件式／自動化などできることが増えているため（他の機能との連携まで含めると更に）、すべてのパターンの検証は現実的に不可能な状況です。発見されたものからマニュアルに反映していきますので、ご了承ください。

**Comment by RYU-DS** [comment]
いくつかはもともとご存知だったような印象を受けたのですが、そうでなかったならすみません。
つまりは「デバッグがまだあまりされていない」という事ですか…
他の方もあまり複雑な条件は使用されていないのですかね…

「!(f3008|f4200)」で現状はなんとかなりました。
4002の
・絶対ヤダ、逃げる@f1251&!(r3070&r3140&r3250&r3320)＞4003
・絶対ヤダ、逃げる@f1251&r3070&r3140&r3250&r3320＞4010
も「選択肢の条件がちゃんと機能していませんマーク」みたいなのが出ていないので、resultさえ持ってこれれば機能しているのでは？と思っていますが、エラーが直らず…

**Comment by RYU-DS** [comment]
r3250が存在しておらず、r3150になっていましたがそこを修正しても変化はありませんでした…（4002と4009でエラー）
4002の
・絶対ヤダ、逃げる@f1251&!(r3070&r3140&r3250&r3320)＞4003
・絶対ヤダ、逃げる@f1251&r3070&r3140&r3250&r3320＞4010
を両方とも削除した所、エラーは出なくなったので、もうちょっと細かく消したり残したりして原因探ってみます。

**Comment by snext1220** [comment]
> いくつかはもともとご存知だったような印象を受けたのですが、～

私のリソースも枯渇している状況で、申し訳ない限りですが、コードの分析までは手が回っておらず、現象から推論しているのみです（事前に把握できているわけではありません）。
上記コメント（ https://github.com/snext1220/snext-management/issues/16#issuecomment-482910000 ）の時点では、あくまでscenario.xml の**目確認で推測**できた範囲の回答でした（よって、実際のソース確認もこれからです）。

> 「デバッグがまだあまりされていない」という事ですか…

いえ、スタッフの皆さまのご協力を得て、日々決して少なくない動作テストを実施しているのですが（具体的な時間は判りませんが、他の皆さまもかなりの時間を割いてくださっているはずです）、それでも回っていないというのが実情です。新企画などを止めてまでそちらにリソースを割くというのは現実的ではありませんし、現時点では見つかった問題を持ち寄って対処していかざるをえない状況であること、ご理解戴けますと幸いです。

＃マニュアルメンテその他も同様で、現在のリソースで最善を尽くしていますし、ご指摘戴いたところは順次対応しておりますが、不整合はおそらく諸々の箇所で出ているのではないかと思います。。

> 他の方もあまり複雑な条件は使用されていないのですかね…

シナリオそのもののデバッグが困難になることもあり、ある程度、分岐は限定されていると思います。あとは基本、新機能ということもあり、（一気に横展開ではなく）個々の挙動を確認しながら進めて戴くことで、少しずつできることを確認している状況なのではないかと（感覚レベルではありますが、バグ報告は進行中に何度か戴いておりますので）

＃そのような感触もあったため、現在は自動化／条件式共々、新機能追加を必要最小限に留め、安定化に努めているという状況です。

> ・絶対ヤダ、逃げる@f1251&!(r3070&r3140&r3250&r3320)＞4003

こちら、昨日見落としていたのですが（フラグだと勘違いしていたので）、実績は「r01:slayer」のような記述で表します。実績はあくまで別シナリオの参照を想定しているので、基本はフラグのご利用をお勧めします。 

ただ、それ以外も複合条件式は問題もありそうなので、引き続き精査してまいります（こちらはお時間戴くことになるかと）。

**Comment by RYU-DS** [comment]
現在、突き当たった問題はすべて解決しました、ありがとうございます。

実績に関しては「他シナからの条件を使うためのもので、自シナでフラグ代わりに使うべきではない」という事ですね…ちょっとサボろうとしてエライ目に…ご迷惑をおかけしました…

ただ今回の件では…あくまで外部から見た意見ですが…
「この要素はまだ実際にあまり使われておらず、不具合がある可能性があるので、それを考慮して使用するようにして（大事な部分に使わない）、また不具合があったら即報告を」
というような注意書きは欲しかったです。
色々な理由で手が回っていない部分があるのが仕方無いのは当然なのですが、それを使う人に伝えられていないのは、こういったトラブルの元かと思います。
