### ISSUE TITLE
STextシナリオ「その名はドラゴンスレイヤー」

### ISSUE THREAD

**Issue by toki-sor1** [snext1220/snext-management#17]
RYUさん（ @RYU-DS さん）のシナリオ「その名はドラゴンスレイヤー」の話題を扱うIssueです。
専用スレッド（Issue）がなかったため、こちらで立てさせていただきました。
お気づきの点など合わせて、こちらにお願いします。

**Comment by toki-sor1** [comment]
この度は「その名はドラゴンスレイヤー」第三部のご執筆お疲れ様でした！

ご報告が公開日当日と、大変遅くなってしまい申し訳ありません……！
GitHub環境にてテストプレイさせていただきましたが、今回は新規のセーブデータを作成して第一部から第三部まで通しでプレイし、すごろくシーンで妙に躓いてしまっていたため、ブルードラゴン戦半ばでのご報告となっています……す、すみません；；

ボス戦の戦闘ルールはやや複雑で、把握するのにちょっと時間が掛かるのですが、手動計算を含めたルールはデジタルでもなお色褪せないアナログの魅力が光っていて、遊びごたえ満点ですね！

第三部にて新たな団体が登場したり、それに関係したココネちゃんのお話など、物語もますます盛り上がってきて、先が読めない展開に「これからどうなっちゃうんだろう！」とドキドキします！

上記の通りすごろくシーンは苦戦していて、最終的にはご報告の都合もあり、スペクテーター勝利後にすごろくを切り上げさせていただいてました；；（すみません……；）
しかし、第二部ではおどろおどろした森の中を彷徨ったりと緊張続きの展開だったこともあり、第三部のミニミニソーサリアンな雰囲気のあるすごろくシーンは、SE一つとっても芸が細かくて、コメディ色も強く、とても良い気分転換になりましたｗ

また、ブルードラゴン戦の選曲が「ああ～～～これはブルードラゴンみある！！！」という素晴らしいもので、「こ、これはきっと選曲にもとても苦労されたのでは……！？」と感じました……！
BGM、SE、戦闘ルールに描写にと、そのすべてがブルードラゴン戦をめちゃめちゃ盛り上げていて、こちらもノリノリで、そしてダメージにヒエエエエとなりながら楽しんでいましたｗ

残念ながら今回は時間切れでブルードラゴン討伐！！というところまではいけませんでしたが（いつでも再開できるようセーブ済みです！）、**ここまでの展開では、特に不具合等は見つからなかったように思います。**

ただ一点だけ、今回新たに**重魔法**が実装されましたが、チュートリアルでは触れられていたのを事前に拝見していたものの、**作中では第三部に説明としてパッと急に出てきた印象**で、ちょっと戸惑いもありました。
＃**何かキャラの会話などで説明があるかな**と思っていたため。

もしかしたら仲間にするNPC（ルート）によっては、この重魔法について言及されているのかもしれないのですが……私の見落としで見当違いなことを言っていたらすみません……！（私は今回マーベルさんでした）

遊びごたえのある戦闘ルールを考えるのは難しいと常々思っているので、RYUさんの「その名はドラゴンスレイヤー」をプレイする度に様々な発見があって、とても刺激になっています！
改めて、第三部のご執筆お疲れ様でした！　引き続きよろしくお願い致します！！

**Comment by RYU-DS** [comment]
テストプレイありがとうございます。

＞すごろくシーンで妙に躓いてしまって
普通にやるとかなり運任せで大変なんですが、これもそのスレ基本の通り「マッピングをすれば楽になる」になってます。出目が左右で選べるので行き先が嫌なマスだったら逆の目を使えばいいわけです。
後半の牛歩も切り捨て切り上げが自由なのはそのためです。

＞「ああ～～～これはブルードラゴンみある！！！」
実は最初はボスはワイバーンだったんですが、フリー素材をあさっている時にこの曲を聴いて「これは！」となってブルードラゴンになりましたｗ

＞BGM、SE、戦闘ルールに描写にと、そのすべてがブルードラゴン戦をめちゃめちゃ盛り上げていて
これはラスボス戦をどうやって盛り上げようかと考えた産物で、試金石でもあります。

＞重魔法～パッと急に出てきた印象で、ちょっと戸惑いもありました。
強状態異常、魔法無効、魔法耐性みなそうなんですが、もともとアイデアはあって使うかどうかどこで出すかはシナリオ展開で変わるので、どうしても唐突な後出しになってしまいますね…
一応今回修正して森最後のリザードマスターとワーベアで触れて、関連して全て説明を見るように誘導はしていますが、もうちょっと段階を踏んだ導入がよかったとは思います。
NPC別ではゾマが重魔法FLYを使ってくれますが、プレイヤーには使えませんｗ

**Comment by RYU-DS** [comment]
こういうシナリオテストのスレッド（イシュー）って、シナリオ執筆者が立てるルールだったんですね、気が付きませんでした…てっきり「完全新作には必要だが続き物には不要」となったと思っていました…。
しかし私はその旨の連絡を全く受けておらず、探した所、連作「ドラゴンモード」専用スレに

シナリオ執筆者様は、担当シナリオの詳細が決まり次第、そのシナリオ専用のIssueを立ち上げていただき、そちらで担当シナリオに関するご報告等を行ってください。

というのを見つけたのですが、私はドラゴンモードに参加していないのでこれを見落としていたのは致し方が無いかと（隅から隅まで全て見る訳にも）。
こういう重要連絡事項はもらさず伝える手段を講じてほしいと思います。

**Comment by toki-sor1** [comment]
@RYU-DS さん＞

早速のご返信ありがとうございます！
先程ブルードラゴンを撃破してきたところですが、まずは先に専用スレッド（Issue）について、こちらが紛らわしい書き方をしてしまっていたので訂正しますね；

> こういうシナリオテストのスレッド（イシュー）って、シナリオ執筆者が立てるルールだったんですね、気が付きませんでした…てっきり「完全新作には必要だが続き物には不要」となったと思っていました…。

ご説明やご連絡がしっかりとできておらず、申し訳ありません……！
まず、専用スレッドを立てる人は、**シナリオ執筆者様なのかスタッフ側なのかははっきりとは決めてはおらず、どちらでも自由に選択が可能です。**
ただ、今回は私が立てさせていただいた、という感じなのでした（以前はリオさんが代理で立ててくださったスレもありました）。

また、「その名はドラゴンスレイヤー」の場合は、やや特殊なケースでして。
「その名はドラゴンスレイヤー」は完全新作のシナリオではないのですが、**現在連載中のシナリオということもあり、専用のスレッドがあった方が今後も意見交換などがし易いと感じたため**、専用スレッドを立てさせていただきました。

> 私はドラゴンモードに参加していないのでこれを見落としていたのは致し方が無いかと（隅から隅まで全て見る訳にも）。
こういう重要連絡事項はもらさず伝える手段を講じてほしいと思います。

様々な企画を同一の場所で管理しているために、情報が混ざり易いということはスタッフとして予め予期しておかなければならず、各企画の参加者様に配慮すべきことでした。
また、重要連絡事項のご連絡が滞り、ご迷惑をお掛けしてしまい、本当に申し訳ありません……！

企画スタッフとして至らないところが多々あり、己の力不足を痛感する日々ではございますが、ご指摘・ご意見を真摯に受け止め、改善に努めます。
この度はご連絡の不備等、申し訳ありませんでした。
また、ご指摘ありがとうございました。

**Comment by RYU-DS** [comment]
これは…まだまだ私の勘違いがあったようですね。

まとめると、そもそも複数人でのテスト自体がしてもしなくてもいいような（必ず立てて～というのはドラモード専用のルールで）、執筆者が選んでも良い話なんですね。

実はテスト期間を設けるのが負担になっていたので、むしろありがたいです（ギリギリまで自分で調整したいので）。
GithubTESTも今回はSEのVOLの問題で必要でしたが、基本はプレイグラウンドで十分で、UPしてもらう手間がかかるだけと思っています。

自分は「全ルート全チェックを基本的にやる」ので、不具合報告よりは今回のように意見を頂くのがメインで、それなら公開後でもいいのかなと思います（実質今回もそうですし）。
次回からは、内容からテストの必要性や期間を考えてGithubtestへのUPのお願いやスレ立てをしたいと思います。

ただ、こういうスタンスである事も今まで知らなかったので、そういった事を伝えていただく手段や機会を設けてほしいのは同じですが…

**Comment by snext1220** [comment]
@toki-sor1 さん＞
スレ立て＆見解ありがとうございます。
こちらはこれまでも、シナそれぞれでまちまちでしたね^^;
私の自シナなんぞはそもそもＴＬで適当ににぎやかしにしてやって、というスタンスなので、トライン、終焉ゼロ共に、そもそもスレすら立てませんでしたし（王杖の時もスキップした気が）。
今後もそんな程度かなと個人的には。

＃ それとは別に本レポジトリトップで出していた「スレ数は常時最大でも7～8個に留めるのが良さそう」が結構越えてきたので、一定期間投稿のないスレはCloseして、必要に応じてReopenするなどしていった方がよいかもしれません。

**Comment by Salvadors-cabin** [comment]
みなさん、お疲れ様です！
・その名はドラゴンスレイヤー第三部の本番環境更新
・SText Webサイト詳細情報更新
・stext.xmlのGitHUB展開
・王様ツイート
が完了しました。

RYUさん、長期間の対応ありがとうございました！
まだ微修正はあるかもとの事ですが、遠慮せずどんどんお願いしますね。

**Comment by RYU-DS** [comment]
今確認した所、4002のブルードラゴン登場シーンのSEが出ないようです。
Githubtestでは出ていますが本番環境では出ない容量などあるのでしょうか？

45KBの雷鳴は出ていますが47KBの咆哮＋雷鳴は出ておらず45KBがライン？
今44KBに落として反映してみましたがそれでもダメでした。
29KBの咆哮のみにした所出ましたが、BGMとのトータルで見てもシーン3330の@se:45kb-thunder-labo
@bgm:BlueDestiny1.10mbの方が多く（@se:44kb-shout+thunder2-labo@bgm:BlueLightning1.09mbであれば）…
推奨の30KBに抑えろというのもわかるんですがそれでは制限がきつく、どこまで足を出してよいかを確認するためのGithubtestなので（BGM/SE的には）、これではますますGithubtestをする意味が薄いのですが…

原因確定しました。28KB-shout+thunder2-laboでダメだったので「+」を外して「shoutthunder」にした所47KBでも出ました…
容量の問題ではなく「+」が入っているとGithubtestでは出ますが本番環境では出ません。

**Comment by Salvadors-cabin** [comment]
RYUさん、お疲れさまでした。
これまで誰も遭遇したことのないトラブルだったようですね。（私もまったく知らなかったです）
取り急ぎ、本番環境からGitHUBテスト環境に反映させておきました。

**Comment by RYU-DS** [comment]
Githubtestと本番環境の差異も探すのはキリが無いと思われるので、同じではないと思った方がよさそうです。擬似本番環境動作チェックというよりは、皆さんに先行でテストしてもらう場と捉えるべきかと

**Comment by snext1220** [comment]
先行テストの場＞
はい、そのようなご認識でお願いします。
将来的にも、本番環境へのUploadをオープンにする可能性はありますが（現在はスタッフ面々での確認が前提になっていますが、将来的には投稿シナリオの内容／品質は作者さんに委ねる、が自然だと思っています）、GitHubをオープンにする可能性はないので、あくまでGitHub Pagesは内部用途の簡易な確認手段とお考えいただいた方が良いかと思います。

**Comment by RYU-DS** [comment]
＞サルバさん
本番環境の更新しました。
主な変更点は…

・チュートリアルの更新
今まで書き足してきただけだったのをまとめて、見出しや強調などで見やすくしました。
・第三部調整
ブルードラゴンに耐久力を表示した「本体」を追加、わかりやすくかつこれで月が加わり１ループで７種全て得られるように。
隼の剣の攻撃力増加（ハルバードから下げるのが嫌に感じたので下げなくてもいい様に）。
まだほぼ第三部のみですが見出しや強調などで見やすく。

以上です。よろしくお願いします。
たぶんこれを見てもう少し調整すると思います。

**Comment by RYU-DS** [comment]
さらに本番環境の更新しました。
追加変更点は…

・リフレクスの魔法反射条件の変更（ハルバードなどでメインを反射しつつサブも攻撃、といった事はできないように）。
・第三部の見出しや強調の調整。

これでしばらくは更新はしない予定です。
第一部～第二部の見出しや強調を少しずつやって仕上がったらにしようと思います。
もちろん問題点があったらすぐ調整しますので、報告お願いします。

**Comment by Salvadors-cabin** [comment]
RYUさん、対応遅くなりスミマセン。
最新のファイルをGitHUBテスト環境に反映させました。
よろしくお願いしますー
