### ISSUE TITLE
【検討】Mini＆Playground検証企画

### ISSUE THREAD

**Issue by toki-sor1** [snext1220/snext-management#20]
**【検討】Playground検証企画**(#12) に続くIssueです。
このIssueでは、プレグラ100祭以外に、新しく「ミニミニ30」シナリオの話題も扱います。
どうぞご利用ください。
***
#### 2020年 5月～
- 【プレグラ】Vol.4（5月2日公開済）：ちゃなさん（不思議のソーサリアン）

　※以降、シナリオは隔月連載になります

#### 2020年 6月～
- シナリオ公開なし

#### 2020年 7月～
- シナリオ公開なし
- 【SN2020】Next Scenario 2020（7月13日公開済）：サルバさん

#### 2020年 8月～
- 【プレグラ】Vol.5（8月1日公開予定）：鏡読みさん（たまには日の光を浴びよう）

#### 2020年 9月～
- シナリオ公開なし

#### 2020年10月～
- 【プレグラ】Vol.6（10月26日公開済）：ちゃなさん（ソーサリアベンジャーズ）

#### 2020年11月～
- 【プレグラ】Vol.7（11月or来年公開予定？）：ときのじ（ハクジャ伝説）

***

**Comment by snext1220** [comment]
新規Issueありがとうございます！
まずは8月のminiを進めていければと思いますが、その他にも、現時点では以下のようなものを検討しております（隗より始めよ、で挙げてみる）。

+ ある魔術師の大失敗 or 灰色のダンジョン
    + チュートシナ
    + 天神もありかと思いつつ、チュートはダンジョンものの方がよいか
+ 七星の名のもとに
    + ドラモード外伝
+ 剣と魔法の都ペンタウァ
    + シナコン移植作品
    + オーソドックスな作品になりそうなので、シカケの多いシナの中で埋もれそうかと悩み中
+ 新・アマゾンの剣
    + パーティ制
    + 3シナ同時進行もの。初期から検討しているものの煮詰まらず；
+ 嗚呼、ジョセフィーヌよ、何処へ行く
    + ミニミニ30の時に検討していたもの。気が向いたら

ある程度進められそうであれば、stext.xmlにどんどん登録して誘い水にしていければ、などとも考えています（ミニミニ～もそんな感じでしたが、大丈夫ですかね？？）。

> ＃私もテーマは2つほどあり、片方はゲームの中にゲームを展開するような内容で、もう片方が夏向きの内容なのですが、まだふわっとした状態ですね；

おぉ、楽しみです！夏向きということで、8月枠は全然お譲りできますので、必要であればお声がけください～

**Comment by snext1220** [comment]
進捗していない進捗報告です；
システム改定を優先させていたため、なかなかシナリオ作成に取り掛かれずにいますが、流石に隔月スパンを前提にしても10月は死守しなければと思っております。頑張ってまいります...

そんな中で恐縮ですが、皆さまのシナリオ状況は如何でしょうか。
ポストPg100、幕末等、話題が途切れてから時間も経ってしまったので、伺い方々、一応スレ上げしておきます～^^;

**Comment by toki-sor1** [comment]
お返事が大変遅くなり、申し訳ありません…！；；
ご返信、そして進捗についてもありがとうございました…！

> ある程度進められそうであれば、stext.xmlにどんどん登録して誘い水にしていければ、などとも考えています（ミニミニ～もそんな感じでしたが、大丈夫ですかね？？）。

はい、ミニミニのようにまずは予定としてどんどん登録、良いと思います！

> 流石に隔月スパンを前提にしても10月は死守しなければと思っております。頑張ってまいります...

> そんな中で恐縮ですが、皆さまのシナリオ状況は如何でしょうか。

ご報告が遅くなり申し訳ありません；；
シナリオを幾つか書きかけで紆余曲折し、ようやく和風シナリオにしようと決まり、現在執筆中です；
おそらく10月中には書き上げられるかなぁというところまで大筋の流れはできているので、このまま頑張りたいと思います～…！

多分、ところどころ変わるかもしれませんが、大体は下記のような始まり方のノベルみの強めな中編（？）シナリオです。
***
### ハクジャ伝説　七星御伽草子　一ノ章（仮）
#### Scene 0
　とっぷりと日が暮れて、夜の色に染め上げられた山々は影絵に姿を変え、夜空の下方に並んでいる。
　数え切れぬほどの星が瞬く銀鼠色の僅かな雲が穏やかな風に流れ、煌々と輝く蒼き月の上をなぞっていった。

　『君』は松明片手に、疲れてやや重い足取りで田んぼに囲まれた夜道を歩いている。
　人が二人並んで歩ける程度の道幅だが、君はど真ん中を延々と歩いているのだ。
　誰かとすれ違わないものかと多少の望みは抱いていたが、一向にその気配はない。
　雑草がまばらに生えたデコボコの畦道に人影はなく、君が黙々と歩く音と蛙達の大合唱が聞こえる。ただそれだけである。

　此処は神秘の国『JAPAN』。
　ソーサリアンである君の祖国ペンタウァから遥か遠く離れた東洋の島国である。
　過去に他のソーサリアンがJAPANに巣食う強大な魔族を斃しに赴いた地であるのだが、今回の君の目的は、それとは別の案件だ。

　『不老不死の妙薬の入手及び製造方法が記された書の入手』。
　これこそが君がペンタウァ国王に命じられ、このJAPANという国に赴いた目的である。

　だがしかし、あろうことか君は今、JAPANの片田舎で盛大に迷っていたのだ！
　元々が土地勘のない、更には文化も違う未知の国である。迷子になるのも仕方がないと言えば仕方がないことなのだが、それでもやはり祖国で『勇者していた』だけに、その落差と事実は君の疲労を増加させていた。

　この国での野宿にはもう慣れたものだが、そろそろ安全な場所で眠りたい。『フトン（布団）』と呼ばれる長方形の綿入り布袋のような寝具で寝たいなどという贅沢は言わないが、せめて人里の家屋に入って心身を落ち着ける時間が欲しい。
　……あともう少しだ。
　君は遥か前方に灯る温かな光の集合体を見つめ、重くなった脚に喝を入れて歩みを速めた。
　疲労でやや充血した君の視線の先にあるのは、小規模の人里だったのだ。
<br>
**村を目指して歩き続け――**
***
#### Scene 1
　ようやく人里に到着した君は、その入り口で見張りの男達に怪しまれてしまった。
　夕刻をとうに過ぎた頃に、JAPANでは見慣れない風体の人間が1人でヨタヨタと村の入り口に寄ってきたのだ。男達の対応は当然のことである。

　君は正直にペンタウァという西洋の国から船で渡ってきたソーサリアンという旅人だと男達に説明したが、男達は首を傾げ、ペンタウァとソーサリアンの発音もままならない様子だ。
　これまでの旅で実感していたことだが、ペンタウァでのソーサリアンの知名度は、JAPANではないに等しい。つまり、JAPANではペンタウァでの名声は一切通用しないと思った方がいいようだ。

　見張りの男達と君の問答は暫く続いた。
　JAPANESE MONSTER――すなわち東洋の化け物『ヨウカイ（妖怪）』と疑われもしたが、君が粘り強く説得を続け、切実に休憩場所を欲しているのだと訴え続けた結果、見張りの男に呼ばれてきたこの村の代表である男の屋敷に招かれることとなった。

**Comment by snext1220** [comment]
お返事ありがとうございます！

> シナリオを幾つか書きかけで紆余曲折し、ようやく和風シナリオにしようと決まり、現在執筆中です；

おぉ、幕末に先行して和風シナですか…！
導入を拝読しても雰囲気十分で、出来上がりが楽しみです～
10月中、についても承知いたしました。どうぞよろしくお願いいたします！

一ノ章ということで、連作的な?構造なのかな、と想定しておりますが、もし可能であれば連作機能使ってやって戴けますとm(_ _)m 結局、実装から一年、実践導入せず終いだったもので、幕末前に試験的にでもご利用いただけると、ゲストさん参加の前に課題を洗い出せるかなと（ないに越したことはないのですが、が、が；）。あくまで宜しければ、というレベルですが、ご検討くださいませ～

そして、私の方ですが、スミマセン、8月以降、PgFlowの改定で完全に手一杯状態で、シナリオに振り向けられておりません。。幸いちゃなさんの進行拝見する限り、10月末に公開できるのかなと勝手予想していたため、私の方はPgFlowの改善に振り切らせて戴こうかと（て、その後、幕末第一作目もあるので、早めにそちらへなんとか...！）。

もちろん、Pg100、ミニ30についても、幕末一作目のあと、振り向けていければと思いますので、恐縮ですが、お許しいただけますと。。シナリオ側はときのじさんらにおまかせっきりになってしまい、本当に申し訳ありません；；

**Comment by toki-sor1** [comment]
お返事が遅くなってしまい申し訳ありません…；

> おぉ、幕末に先行して和風シナですか…！
導入を拝読しても雰囲気十分で、出来上がりが楽しみです～
10月中、についても承知いたしました。どうぞよろしくお願いいたします！

お褒めのお言葉ありがとうございます！！
最初は洋風だったのですが、どうも真新しさがないなぁと思って、それなら逆に和風にしてみたらどうだろうと転換したら意外とシックリきて、和風シナリオ採用となりましたｗ
幕末ソーも控えていたので、ウォーミングアップの意味もありますねｗ

> 10月中、についても承知いたしました。どうぞよろしくお願いいたします！

当初は10月中に公開の予定でしたが、どうにも厳しそうなもので、申し訳ありませんが公開月を11月または来年にスライドさせていただいてもよろしいでしょうか？；；
幕末ソーのこともありますので、11月上旬までに公開できそうにない場合は、来年に回していただけると助かります…；

> 一ノ章ということで、連作的な?構造なのかな、と想定しておりますが、もし可能であれば連作機能使ってやって戴けますとm(_ _)m 

旅の目的を考えるとシリーズ化しても面白いかなと思って仮に一ノ章とつけておりましたので、連作対応も可能です～。
ただ、「ハクジャ伝説」が終わったら次の章へ、というイメージであることと、二ノ章の構想がまだ浮かんでいないことから、幕末ソー前に二ノ章は投稿できそうにないですね…申し訳ありません；；

> そして、私の方ですが、スミマセン、8月以降、PgFlowの改定で完全に手一杯状態で、シナリオに振り向けられておりません。。

> もちろん、Pg100、ミニ30についても、幕末一作目のあと、振り向けていければと思いますので、恐縮ですが、お許しいただけますと。。

いえいえ、怒涛の更新でしたもんね…！　本当にお疲れ様でございます…！！
リオさんが多くのご意見やご感想をもとにPgFlowの改善に全力を注いでくださったことで、PgFlowが劇的にパワーアップしてとても使いやすくなりました！　ありがとうございます…！！
「ソーサリアベンジャーズ」もめでたく公開となり、お次は幕末ソー（とPg100祭も…！）が控えておりますが、引き続きよろしくお願いいたします…！

**Comment by snext1220** [comment]
@toki-sor1  さん：

お返事ありがとうございます！

ウォーミングアップ＞ホントこれですよね～私の方もドラモードゼロ以来、専らシステム改定に感けて、シナリオは久々になってしまったので、微妙にウラシマさん状態です；全然調子（頭）が戻ってこずに、苦戦中です＞＜

> 公開月を11月または来年にスライドさせていただいてもよろしいでしょうか？；；幕末ソーのこともありますので、11月上旬までに公開できそうにない場合は、来年に回していただけると助かります…；

了解です！勿論、ご無理ない範囲でお願いします～
＃連作機能ももしうまく活用頂けるようであれば、という程度でしたので、無理せず使ってやってくださいませm(_ _)m

> リオさんが多くのご意見やご感想をもとにPgFlowの改善に全力を注いでくださったことで、PgFlowが劇的にパワーアップしてとても使いやすくなりました！

成果物が見えにくい作業も多く、役に立ってるのかな？と手探り状態だもので、そう仰って戴けると、救われます^^; 是非、新作作成の折にもお気づきの点があればなんなりとお声がけください！（ちゃなさんのソーサリアベンジャーズ進行は、まさにPg100祭でしたｗ）

ではでは、引き続きよろしくお願いいたします～
