### ISSUE TITLE
連作「ドラゴンモード」専用スレ

### ISSUE THREAD

**Issue by snext1220** [snext1220/snext-management#5]
掲示板から引き継いで、スレのみ立てています。

**Comment by toki-sor1** [comment]
スレ立ち上げありがとうございました！
掲示板のサービス終了、それに伴うIssueへの移行ということで、ドラモード情報もこちらに改めて記載しますね。

---
### このスレッドは、連作シナリオ「ドラゴンモード」の話題全般を扱うIssue（スレッド）です。

ドラゴンモードのシナリオ執筆者様同士の意見交換、情報共有、ご質問等は、こちらのIssueへの書き込みをよろしくお願い致します。

**【参考資料：GitHub（ギットハブ）の使い方：issue（イシュー）編】**
http://www.atmarkit.co.jp/ait/articles/1407/28/news006.html

シナリオ執筆者様は、担当シナリオの詳細が決まり次第、そのシナリオ専用のIssueを立ち上げていただき、そちらで担当シナリオに関するご報告等を行ってください。

ドラゴンモードについてご不明な点、お知らせ等ございましたら、下記の方法で気軽にお訊ねください。

- こちらのIssueに書き込む
    - このIssues（掲示板の代わり）に返信したり、新規Issueを立ち上げるためには、GitHub（このサービス）のアカウントを作成する必要があります。こちらのページを参考に、GitHubアカウントの作成をお願い致します（https://programmingnavi.com/61/ ）
    - 通常内容の書き込み時は、ご連絡は不要です。
    - 急ぎのご連絡の時は、王さまbot（https://twitter.com/snext1220 ）または「外部投稿者窓口」担当のサルバさん（https://twitter.com/mail74446386 ）にご連絡をお願い致します

- Twitterにて王さまbot（https://twitter.com/snext1220 ）、または「外部投稿者窓口」担当のサルバさん（https://twitter.com/mail74446386 ）宛てにリプライやDMを送る

---
### ご報告いただいているタイトル／ドラゴン候補／解放条件／進行有利
※01/17現在
※解放条件の既存シナリオ割り当ては、12/25に正式決定

- 本編シナリオ2「裏切り者の流儀」
    - ？？？・・・山田さん
    - 解放：Scenario 1「新・消えた王様の杖」（作・リオ）
    - 解放：Scenario 10「魂の選択」（作・ときのじ）

- 本編シナリオ3「黄泉へ送るレクイエム」
    - ブルードラゴン（原作由来）・・・咲華さん
    - 解放：Scenario 5「少女は英雄を語りて」（作・ときのじ）
    - 解放：Scenario 12「ソーサリアン性格診断占い」（作・RYUさん）

- 本編シナリオ4「金竜の陰謀（仮称）」
    - ゴールドドラゴン（原作由来）・・・ちゃなさん
    - 解放：Scenario 4「災厄の夜 - テンペスト・ナイト -」（作・ちゃなさん）
    - 解放：Scenario 7「その名はドラゴンスレイヤー」（作・RYUさん）

- 本編シナリオ 5「時を超えた協力者」
    - ナイトメアドラゴン（オリジナル）・・・ココさん
    - 解放：Scenario 3「プレアオブ・ドールズ」（作・cocotori）
    - 解放：Scenario 13「トラベラーズ☆イン」（作・リオ）

- 本編シナリオ 6「ドラゴンネゴシエーター」
    - アイスドラゴン（原作由来）・・・サルバさん
    - 解放：Scenario 6「鉄腕の吸血姫」（作・cocotori）
    - 解放：Scenario 8「ラミディアの魔法使い」（作・Salvador）

- 本編シナリオ 7「―」
    - ？？？・・・座間さん
    - 解放：Scenario 9「わたしのネコを探して」（作・cocotori）
    - 解放：Scenario 11「戦国ソーサリアン外伝・上杉謙信の章」（作・Salvador）

- 本編シナリオ1「常闇から来たる影」　※公開済み 
    - シャドードラゴン（原作由来）・・・ときのじ
    - 解放：Scenario 2「ゼロの創造」（作・Salvador）

---
### 関連ページ・シナリオ作成マニュアル
※wikiのURLは、短縮URLサービスを使用しました

- 連作「ドラゴンモード」執筆者募集！（https://bit.ly/2CZZahN ）

- 連作「ドラゴンモード」詳細情報（https://bit.ly/2RzHfmk ）

- Playground（オンライン上のシナリオ動作確認環境）（https://www.web-deli.com/sorcerian/next/playground.aspx ）

- STextシナリオ開発道場（SText基礎知識を解説するシナリオ）（https://www.web-deli.com/sorcerian/next/game.aspx?id=trial ）

- ソーサリアンText 開発者向けマニュアル（環境準備編）（https://sorcerian.hateblo.jp/entries/2018/01/25 ）

- ソーサリアンText 開発者向けマニュアル（シナリオ開発リファレンス）（https://sorcerian.hateblo.jp/entry/2018/11/01/211745 ）

- ソーサリアンText開発者向けマニュアル（GBAT to SText編）（https://sorcerian.hateblo.jp/entries/2018/01/31 ）

**Comment by toki-sor1** [comment]
### ドラモード参加者様へ

**＞山田さん**

※シナリオの最終調整中、もしくは既にサルバさんにシナリオ送付済みでしたらスルーしてください。

現在GitHub版にアップされている「裏切り者の流儀 ver8」ですが、Scene 0の以下の指定が抜けているため、表示が崩れてしまっているようです（サルバさん、リオさんからご報告がありました）。
```
<scene id="0" bgm="@none">
<![CDATA[
本文
選択肢ボタン
]]>　←この部分
</scene>
```
---
**＞ちゃなさん
＞進行有利時でなければ取得できない実績を設定するご予定のある参加者様**

「金竜の陰謀」には「進行有利」も実装予定と伺っておりましたが、「金竜の陰謀」プレイ中に取得できる実績の中に「進行有利時でなければ取得できない実績を設定するご予定」はありますでしょうか？
もし実装予定の場合は、シナリオ中（バッドエンドなど）に、以下のようなヒントの記載もよろしくお願い致します（文面、ヒントの出し方は改変・変更可能）。

※以下は「常闇から来たる影」の例です。進行有利時でなければ取得できない実績を「既に取得している状態」では、このヒントは消えるようになっています

※進行有利と判定する実績を含んだ既存シナリオが「実績が多いシナリオ」の場合は、実績特定が困難なため、もう少し分かり易いヒントにしても良いと思います
```
${if -r06:shadow}%red%
　※一部の実績取得条件には、Scenario 2「ゼロの創造」の
　　実績取得率が関係しているものも含まれています%/%
${/if}
```

**Comment by kenjiintasmania** [comment]
> ### ドラモード参加者様へ
> **＞山田さん**
> 
> ※シナリオの最終調整中、もしくは既にサルバさんにシナリオ送付済みでしたらスルーしてください。
> 
> 現在GitHub版にアップされている「裏切り者の流儀 ver8」ですが、Scene 0の以下の指定が抜けているため、表示が崩れてしまっているようです（サルバさん、リオさんからご報告がありました）。
> 
> ```
> <scene id="0" bgm="@none">
> <![CDATA[
> 本文
> 選択肢ボタン
> ]]>　←この部分
> </scene>
> ```


先程、サルバさんに送付しました！

**Comment by Salvadors-cabin** [comment]
サルバです。
山田さんより「裏切者の流儀」Ver.9を受領しましたので、さきほどGitHUBにアップしました。
よろしくお願いしますー

**Comment by toki-sor1** [comment]
**＞山田さん、サルバさん**

「裏切り者の流儀」Ver.9の更新＆GitHubアップお疲れ様でした！
Scene 0が正常に表示され、シナリオも問題なく遊べることを確認しました！
山田さん、ドラモード本編シナリオをご執筆いただき、本当にありがとうございますっ！！

シナリオの公開＆王さまbotからの告知は、状況にもよりますがいつも20～22時の間に行っています。
21日まであと2日ですね！　引き続きよろしくお願い致します～！

**＞サルバさん**

「裏切り者の流儀」の本番環境への反映（リンク開通）と告知をよろしくお願い致します～！

**Comment by kenjiintasmania** [comment]
いろいろありがとうございます！
今日のFT新聞（ゲームブック＆TRPG専門メルマガ）で宣伝してもらってます。
素晴らしいタイミングｗ

**Comment by snext1220** [comment]
おぉ、拝見して朝っぱらから魂消ておりましたｗ＞FT新聞
ありがとうございます！！

**Comment by olreia** [comment]
ちゃなです。
私のシナリオ「金竜の陰謀」では、進行有利は、とある重要な選択肢で間違えづらくなる程度の効果ですので、実績取得には関係しません。ですので特に注釈しなくて大丈夫かと思います。

**Comment by AyakaLinkyo** [comment]
咲華です。

シナリオ、ギリギリになってしまい申し訳ございません……
こちらで上げさせていただきますのでご確認お願い致します。

ファイルなのですが、AZさんのBGMを使わせていただいた場合のBGMデータをどのように組み込めばいいのか分からなくて、scenario.xmlのみをzipにさせていただいている形です……ごめんなさい……

[yomi.zip](https://github.com/snext1220/snext-management/files/2866844/yomi.zip)

**Comment by snext1220** [comment]
お疲れ様です＆シナリオ完成おめでとうございます！
現時点では2/25（mon）正式公開を目指して、別途拝読してまいりますね。

> BGMデータをどのように組み込めば

標準bgmはシステムが自動で配信しますので、組み込みご不要です。
詳細はこちらを参照下さいませm(_ _)m
https://sorcerian.hateblo.jp/entry/2018/11/01/211745#bgm

なお、今回はシナリオをNew Playgroundで作成戴いているようで、ありがとうございます！（本番のための利用は第一号です！ｗ）なにかお気づきの点があれば、是非お寄せください～

＃こちら、最低限のテストは手元でしているのですが、不具合が残っている可能性もあるため、データのバックアップはくれぐれも。。

#### 追記

#11 に専用スレも用意しておきました。感想等はこちらをご利用ください。＞皆さま

**Comment by toki-sor1** [comment]
**＞ちゃなさん**

遅ればせながら、お忙しい中「金竜の陰謀」ご執筆お疲れ様でした！
シナリオ完成おめでとうございます！

また、進行有利についてもご返信ありがとうございました。
実績取得には関係してないとのお話でしたので、注釈なしですね。承知しました。

シナリオの修正お疲れ様です。
最新版のシナリオ拝読後に、専用スレにて感想等を投稿致しますね。

**＞咲華さん**

いえいえ、お忙しい中「黄泉へ送るレクイエム」ご執筆お疲れ様でした！
シナリオ完成おめでとうございます！

AZさん作曲のBGM組み込みについては、既にリオさんのお返事がありましたので割愛しますね。
（もしフリー音楽素材等をご使用される場合には、同ページ内の「フォルダー構造」も参考になるかもしれません）
https://sorcerian.hateblo.jp/entry/2018/11/01/211745

現在のシナリオ拝読後に、専用スレにて感想等を投稿致しますね。

**Comment by zamashow** [comment]
座間です。
お久しぶりからのお久しぶりです。すいません。

タイトルとあらすじを提出して欲しいとのことでしたので、ここにアップさせて頂きます。
シナリオ、ようやくプロットを実文章に書き起こし始めたところです。期限長めの設定に甘えてしまって申し訳ないですが、もう少しお待ち下さい。
前回の失敗の主たる原因だった会社勤めは卒業できたので、今回はちゃんと完走します。

ところでドラゴンモードの一環のシナリオが、こういった物語然としたもので大丈夫なのか（いちおうできるだけシンプルに、ドラゴンとの対面を意識したシナリオにはする予定です）、もっとシンプルにドラゴンと格闘させたほうがいいのか、いまいち把握しきれておりませんで、その辺どなたかにご鑑定頂けますでしょうか？


-----------------------------------------------------------------
タイトル：怪竜奇術の“ソーサリアン・アパート”
-----------------------------------------------------------------

気が付くと、人の気配のないアパートの廊下にいた。
老朽化が激しく、蛍光灯は不規則な明滅を繰り返している。

というか「アパート」ってなんだ…？「蛍光灯」って…？
知らないはずの言葉を知っている。でもそれがどんな物なのかは、今朝見ていたはずの夢のように頭の中から消えていく。

見たこともない、木でも石でも鉄でもない材質…「コンクリート」の壁に覆われたダンジョン。
既視感と未視感が交錯する迷宮の中で、それでもいつも通り敵を倒し、謎を解き、部屋から部屋を行き来しながら、事態の深層へと進んでいく。

「１９８７」。なじみのない数字が殴り書きされた掲示板と、各部屋の番号札、数字で細かく区切られた意味不明の小説。
そして埃を被った「フロッピーディスク」と「パーソナルコンピューター」。
不可思議な青い影を引きずる竜の気配。

“ねえ、皆はここに来たことがある？
それとも、
もしかして私たちは…”

**Comment by zamashow** [comment]
適当に区切り線を入れたつもりがなんか特定の記述になってしまったようだ…タイトルっぽくはなったので勘弁してやって下さい

**Comment by snext1220** [comment]
@zamashow さん、改めてタイトル、プロット有難うございました！

こちらは一寸現代風、かつホラー?風味のソーサリアンといったところでしょうか。
Vol.6までとはまた全く異なるテイストからの斬り込み、ありがとうございます！

物語然としたもので大丈夫、については、問題ないと思います。
今回のドラモードについては、原作のひたすらドラゴン戦というよりは、ドラゴンの登場する連作シナリオ、な雰囲気になっていますので^^;（物語も、スタンダードな探索ものからミステリー風味、ノベル風、タワーディフェンスと結構バリエーションあります）
詳細は既存のシナもご覧戴ければ幸いですm(_ _)m
https://www.web-deli.com/sorcerian/text/

連作、という意味では、ご執筆に際して、以下Wikiの「シナリオの修正・調整」、特に「ストーリーの共通点～」のくだりを気にして頂けると、最低限つながりを表現できるかなと。
https://github.com/snext1220/stext/wiki/%E9%80%A3%E4%BD%9C%E3%80%8C%E3%83%89%E3%83%A9%E3%82%B4%E3%83%B3%E3%83%A2%E3%83%BC%E3%83%89%E3%80%8D%E8%A9%B3%E7%B4%B0%E6%83%85%E5%A0%B1

@toki-sor1 さん＞
とりあえず終章の執筆を進めて戴く上で、上記の情報で問題ありませんでしょうか。「この辺の詳細を～」などありましたら、ご指摘お願いします～

**Comment by zamashow** [comment]
連作の件、了解しましたー。ありがとうございます。

**Comment by snext1220** [comment]
勝手ながら、王さまbotツイ追加用のスレを追加させていただきました。
https://github.com/snext1220/snext-management/issues/15
シナリオ執筆者の皆さま、ご利用いただけますとm(_ _)m

@cocotori さん＞とりあえず立ち上げてみましたが、如何でしょうか。
こんな形だと作業しやすい、などあれば、是非にお願いしますm(_ _)m

**Comment by toki-sor1** [comment]
＞ @zamashow さん

この度は、「怪竜奇術の“ソーサリアン・アパート”」のあらすじをご投稿いただき、ありがとうございます！
私の方こそ「未来の私頑張って……」という状態なので（てへぺろ顔）、シナリオご提出日についてはお気になさらず、座間さんの無理のないペースでご参加いただけましたら幸いです〜。

早速あらすじを拝読しましたが、何処か昭和の懐かしさを感じるタイトルは、とてもインパクトがありますね！
あらすじの内容も現代風且つミステリアスで、薄暗い空間の中を何処かぼんやりとしながらも深層へと進む主人公、意味深なキーワードの数々、そして最後の台詞等、拝読していてとてもぞくぞくとしてきました！
終章の前に、これまでのファンタジーな世界観とは異なる現代風の世界観が登場し、これもまさに連作の醍醐味だと感動しました〜！

> ところでドラゴンモードの一環のシナリオが、こういった物語然としたもので大丈夫なのか（いちおうできるだけシンプルに、ドラゴンとの対面を意識したシナリオにはする予定です）、もっとシンプルにドラゴンと格闘させたほうがいいのか、いまいち把握しきれておりませんで、その辺どなたかにご鑑定頂けますでしょうか？

ドラゴンモードは連作ということで、執筆者様それぞれの「人とドラゴンとの関係性」を描いています。
ドラゴンは斃すもヨシ、和解するもヨシ、交渉して退けるもヨシ、別れを惜しむように決別するもヨシ、と本当に自由ですし、リオさんも仰っていますが、ジャンルも本当に様々です。

ドラモードwikiのストーリーの共通点をご参照いただき、シナリオに取り入れていただく以外の部分では、座間さんもご自由にドラゴンとストーリーを描いていただければ幸いですー（私のシナリオは、ストーリー重視＋ドラゴン討伐系でした）。

座間さんのご都合の良いタイミングで大丈夫ですので、新規に「怪竜奇術の“ソーサリアン・アパート”」の専用スレッドを立てていただいた後は、専用スレッドで引き続きやり取りしましょー。
ご不明な点がありましたら、気兼ねなくお尋ねくださいね。 よろしくお願い致します！

---

＞ @snext1220 さん

ドラモードについてのご案内ありがとうございました！ 内容バッチリでした！
終章は今までのドラゴンモードの内容を取り入れようと考えているので、なんとかいい感じにまとめられるように頑張ります！ 頑張って私……！

王さまbotツイ追加用スレッドもありがとうございました！
今まではDMでのやり取りと各自用意して掲示板やO/Dで提出という感じだったので、こうしてissueでやり取りできるのは良いですね！
なかなかツイートが提出できず申し訳ありませんが（汗）、思いつき次第提出したいです……！

**Comment by snext1220** [comment]
内容ご確認ありがとうございました！
終章、については、これまでの個性あるシナリオ群を束ねてのキンドラ戦ということで、序章以上に大変なのではないかと思いますが、楽しみにしております＆どうぞよろしくお願いいたします！

王さまbotツイスレッド＞
こちらもご確認ありがとうございます。
新しいものツイも、ですが、これまでに王さま／自アカから流した告知／言及などもうまく編集して、bot側も充実させていければ良いなと思っています^^;（その際に、モーメント活用しておりますｗ）
是非是非よろしくお願いします～＞皆さま

**Comment by snext1220** [comment]
ソーアパートのタイトルを［Scenario］ページのカルーセルに反映しました。
＃併せてモーメント20もAboutページに追加済みです。

ただ、タイトル横幅が長く、見た目が崩れてしまうので、勝手に短縮しています＞＜;
改めて対応検討しますが、良い短縮名があればお願いしますm(_ _)m ＞ @zamashow さん
※ページ下の紹介本体は正式名称で表記の予定です。

**Comment by zamashow** [comment]
ときのじさん、むっちゃありがとうございます！
終章ときのじさんなんですね、変な話書いて申し訳ない…！

略称は単にソーサリアン・アパートとかでいい気がしますー

**Comment by kenjiintasmania** [comment]
アパートには「遠く離れて」って意味もありますね。僕は最初、そっち（外伝的な意味だろうか）と思いましたｗ

**Comment by zamashow** [comment]
アパートメントでないそっちのアパートの意味ももちろんあります！
流石でいらっしゃる

**Comment by kenjiintasmania** [comment]
よかった（ホッ）ｗ

**Comment by toki-sor1** [comment]
＞ @zamashow さん

お疲れ様ですー！
ドラゴンモード関連のお知らせ＆確認事項がございますー。

来月の6月21日頃が座間さんのシナリオ公開予定日になっておりますが、ご予定の方は如何でしょうか？

お忙しい中、たいへん恐縮ですが、ご予定についてお教えいただけましたら助かります〜。
（公開スケジュールは調整可能ですので、要調整の際にはご相談くださいませ〜）

> 終章ときのじさんなんですね、変な話書いて申し訳ない…！

あわわ、お返事が遅くなってしまい、申し訳ありません……！
いえー、こちら寧ろ座間さんのプロローグからエピローグの方向性が定まりつつあるので、感謝感謝でございます！ありがとうございます！
