### ISSUE TITLE
【事務連絡】システム関連

### ISSUE THREAD

**Issue by snext1220** [snext1220/snext-management#6]
掲示板から移動しています。以下は、既存スレのコピーです。

これまでスタッフＤでお知らせしてきましたが、流れてしまいがちなので^^;＆ゲスト執筆者の皆さまとも共有しておいた方が良いものもあるので、こちらでスレ立て致しました。

---

+ February Updateテスト完了（https://github.com/snext1220/stext/milestone/5?closed=1 ）に伴い、SText 1.1をリリースしました。更新履歴もこちらで参照ください。https://github.com/snext1220/stext/releases
+ 伴い、March Updateを立ち上げています。その他リクエスト含めて、ご意見あればお願いいたします。https://github.com/snext1220/stext/milestone/6 ※オープンな場なので、ゲストさんの書き込みも大歓迎です！^^
+ March Updateには「■ときのじさん：×■サルバさん：×■cocoさん：×■」という表記を追加しています。お手数ですが、機能テスト終了時には「×→○」で終了宣言をお願いします。 ※終了の把握が難しくなっていたため、お手数をおかけしてしまいますが、ご協力のほどお願いいたします。

**Comment by snext1220** [comment]
スタッフの皆さま：
以下Issueにて比較的大きめな課題について、議題を上げています。お手数ですが、未回答の方は、「問題なし」含めて、軽くでもご意見戴けますと幸いです。

+ SText2年目の課題
  https://github.com/snext1220/stext/issues/72
+ マニュアルの導線強化
   https://github.com/snext1220/stext/issues/78
+ 新Playgroundの検討
  https://github.com/snext1220/stext/issues/87
+ プレイヤー称号（レベル）の追加
   https://github.com/snext1220/stext/issues/82

※あ、ゲスト執筆者の皆さまもご意見戴けるならば、もちろん歓迎です！:wink:

**Comment by snext1220** [comment]
先ほど、Playground新版を本番環境にUpしました（これに伴い、～_new.aspxは削除しておりますので、ご了承くださいm(_ _)m）。
https://web-deli.com/sorcerian/next/playground.aspx

凡そここまでに戴いたご指摘は吸収しているかと思いますが、もしヌケなどありましたら、ご指摘ください。

@cocotori さん＞諸々のお返事ありがとうございました。個別には別途お返事させて戴きますね。

**Comment by snext1220** [comment]
March Updateへの対応を終了しました（滑り込みで新規Issueも幾つか追加しております）。
https://github.com/snext1220/stext/milestone/6
 
一部は、既にご確認戴いておりますものもありますが、未了のものにつきまして動作テストをお願いいたしますm(_ _)m また、お手数ですが、完了の折はステータスの○もお願いいたします（ @toki-sor1 さん、早速ありがとうございます！）。

また、https://github.com/snext1220/snext-management/issues/6#issuecomment-455402566 のご意見についても引き続きどうぞよろしくお願いします。
＃諸々作業が立て込んでしまい、お忙しいところ申し訳ありません；

**Comment by Salvadors-cabin** [comment]
お疲れ様です。
RYUさんから連絡があり、「その名はドラゴンスレイヤー」の実績を追加していただいたとの事です。

RYUさんから頂いたDMをほぼそのまま転記します。

----------------------------------------------
★実績追加
先の話の「現状クリア認定用実績」と「ドラモード解放用実績の見直し分」を追加/検討しました。

●ドラモード解放用実績の見直し分
①r1056:娘を助けて武器屋を通常営業に戻した:2:超絶テンプレートイベント
②r1061:ファイヤーエレメントを消した:3:いやこれで消えるかね、ホント…
③r1106:クラーケン・ジャイアント(普)を倒した:4:ザ○ドゥの時とかも思うんだけど､こういうの倒したら大量の食料が手に入ってもいいんでは？味はともかくとして｡
④r1108:クラーケン・ジャイアント(怒)を倒した:5:うーむ…クラーケンがやられてしまってはしかたがない､きょーのところはひきあげだ(軽い)｡

①が一番軽い実績で、さらにスタートしたら武器屋に行くよう促せばすぐに取得できると思います（戦闘無視ならものの１分？）
②早ければ①の直後に、順当に行けば第一部の中～後半に取得できると思います。
③④第一部クリア実績となります。
これらから選択してもらえれば、問題ないかと。
遊び心を出すなら、先に提示した各強敵エンカウント実績のどれかひとつ（それを探す）というのも面白いかもしれません。

●現状クリア認定用実績
①r2151:拒絶の森に入った:3:感じ悪りーなーもー
②r2531:森の聖水域(並)に入った:3:いやされるぅ～
③r2641:森の聖水域(特)に入った:3:い～や～さ～れ～るぅ～
④r2121:森の最深部(西側)に入った:4コイツは激戦の予感がするぜ…
⑤r2903:拒絶の森を救った:5:物語はさらに核心に迫る…
⑥r856:この島の歴史と､小さな幸せが1つ消えた事を知った…:5:世の厳しさも､その中で得る幸せのはかなさも､全ては無情だ…

①～⑤他の事態にも備えて、フラグ同様のゲーム進行状態を表す実績を入れました（これからも入れていく事にします）。
⑥こちらが第二部クリア＝現状クリア実績となります。

以上と、若干のBGM変更と文字サイズ変更、発見したミスの修正をしたデータを昨日深夜（朝）、本番環境に反映済みです。

----------------------------------------------

というわけで、さきほど私（サルバ）の方で以下の対応を行いました。
・stext.xmlの「そのスレ」クリア実績に"r2151,r2531,r2641,r2121,r2903,r856"を入れました。
・「そのスレ」シナリオおよびstext.xmlを本番環境からGitHUBに反映。

よろしくお願いします。

**Comment by snext1220** [comment]
更新お疲れ様です＆ありがとうございます。

ただ申し訳ありません。
クリア実績ですが、clears属性に示すものはシナリオクリアと見なす実績なので、ドラスレの場合は現時点では入手できないもの、となります（not 第●○部クリア）。お手数ですが、入手できないダミー実績を設定の上、そちらをclears属性に設定頂くよう、ご案内戴いても宜しいでしょうか。

お手数をおかけしまして恐縮ですが、引き続きよろしくお願いいたします。

**Comment by RYU-DS** [comment]
？？？
「途中ではあるけども、とりあえず現状行ける所までは行っていると認定する実績」
を設定して、それを所持しているとシナリオ選択時のトップ画面に「Clear!」と表示されるためのものと思っていたのですが…
そうではなく、本当の最終的なクリア実績を仮でいいので先に作って、称号システムに先に登録しておく必要がある、という事でしょうか？
その場合でも、現在複数ENDの数をはっきりとは決めていないので、今後変わる可能性があっても問題ないのでしょうか？

**Comment by snext1220** [comment]
説明不足で申し訳ありません。
clear属性そのものは、先の投稿の通り、最終的な「シナリオクリアと見なす実績」を想定しています。よって、未完のドラスレは現時点ではClear、Completeなどのスタンプは立たないが正しい挙動です。
ということで、「本当の最終的なクリア実績を仮でいいので先に作って」戴けると幸いです。

> 現在複数ENDの数をはっきりとは決めていないので、今後変わる可能性があっても問題ないのでしょうか？

はい、問題ありません。実績取得割合は変動しますが、これは仕方ないかと^^;

**Comment by snext1220** [comment]
フローチャート志向のPlaygroundをプロトタイプ版として立ち上げましたので、お知らせです。
まずはお気軽に触ってみてください。
https://github.com/snext1220/stext/issues/87

**Comment by snext1220** [comment]
March Updateの機能テストありがとうございました！（○でのチェックもご協力感謝でございます）

伴い、New Playgroundのステータスも［Testing］に格上げいたしました。
まだ諸々問題もあるのではないかと思われますが、ゆるゆると動作のご確認をお願いできますと幸いです。 https://github.com/snext1220/stext/issues/87

＃一応、April Updateに含めておりますが、動作安定しない場合は、もちろん、以降に持ち越してまいります。

**Comment by snext1220** [comment]
ソーサリアン Text、新規サイト（暫定の暫定）を立ち上げました。
https://github.com/snext1220/stext/issues/27#issuecomment-459941192

まずはコンテンツを分離しただけですが、それでも今後の拡張はしやすくなるのではないかと。シナリオページ、現在の縦長のページはイマイチなので、見せ方要検討なのですが、キモだと思うので、ぜひ皆さまの知恵をお借りしたく。

**Comment by snext1220** [comment]
現在、STextサイトリニューアルを進めておりますが、その際にフォルダー等の移動が発生いたします。このため、シナリオ紹介画像が各シナリオフォルダーのintro.pngに移動されていない場合にはリンク切れの原因となります。以前stext.xml改定（ https://github.com/snext1220/stext/issues/68 ）の際にお願いしておりましたが、未対応の皆さまは画像の登録とstext.xmlの更新をお願いできれば幸いです。

@Salvadors-cabin さん＞お手数ですが、ゲストさま分シナもご確認をお願いできますと幸いです（未修整のものは、新規に画像を選定戴くか、現在のサイトのものをダウンロード＆シナフォルダーへ移動くださいませ）。

**Comment by Salvadors-cabin** [comment]
>ゲストさま分シナ

ちゃなさんとRYUさんの紹介画像は全部修正対象ですね。
了解です。
私の既存シナも含めて数が多いのでタイミングをみて対応します。

**Comment by olreia** [comment]
こんにちわ、ちゃなです。
実績の件、承知しました。RYUさん有難うございます。とりあえず私のシナリオ「金竜の陰謀」の解放条件は、「娘を助けて武器屋を通常営業に戻した」にしておきます。ストーリー的には間接的につながようになっていますので。。

**Comment by RYU-DS** [comment]
＞ちゃなさん
ありがとうございます。やっぱそこらへんがいい塩梅ですかね。
面倒な人は速攻武器屋行って戦闘無視すれば１分ぐらいで取得できますし、逆にしっかりやってもらえればどんなシナリオかわかってもらえるかと。

＞サルバさん
これを機に、今まで変えよう変えよう思いつつ忘れてきたけどもやっと画像手に入ったので、紹介画像変えたいんですが…
大丈夫ですかね？（いろいろと）
![ds -](https://user-images.githubusercontent.com/43634197/52534747-9b8caa00-2d88-11e9-9f3a-be7824676748.jpg)

**Comment by Salvadors-cabin** [comment]
>これを機に、今まで変えよう変えよう思いつつ忘れてきたけどもやっと画像手に入ったので、紹介画像変えたいんですが…

おお、これはザナドゥの最終盤にテンプルで表示される地図ですね。
なんて懐かしい・・・

>大丈夫ですかね？（いろいろと）

まあ、大丈夫じゃないかと思います。
この手のゲームキャプチャ画像を禁止すると、草の根のゲーム紹介サイト全滅です。
次回アップデート時に合わせて入れ替えしておきます。
（「そのドラ」の紹介画像ですよね。念のため）

**Comment by snext1220** [comment]
April Updateにつきまして、状況見まして、今回はこちらでFixとさせて戴ければと存じます。
お手数ではありますが、機能テストの開始をお願いできますと幸いですm(_ _)m
https://github.com/snext1220/stext/milestone/7

**Comment by snext1220** [comment]
ゲスト様が投稿される際に利用できるIssueテンプレートを用意しました。

［New Issue］を押すと、［シナリオ投稿テンプレート（外部投稿者向け）］が現れますので、こちらをご利用いただけますと幸いです。

＃今後、マニュアル等にも反映してまいります。

**Comment by RYU-DS** [comment]
＞サルバさん
「ドラゴンスレイヤーを探す」というワードから最初に思い浮かんだのがコレだったんですよー

大丈夫ですかね？（いろいろと）
これは特定の物だけダメな場合があるので、界隈に詳しい人なら常識だったりするのでそういうのが無いかと確認を…ソーサリアンサントラにロマンシアが入らないとか色々あるみたいなので。

（「そのドラ」の紹介画像ですよね。念のため）
あっすっかり忘れてました（占いの存在を）、すいませんもちろんそのスレの方です。

**Comment by RYU-DS** [comment]
遅くなりました（というか忘れていた）が、そのスレに仮のクリア実績作りました。
・r10000:ドラゴンスレイヤーを手に入れた:5:クリア実績用(仮)
が、これまた仮のルートのシーン10000（クラーケンから派生）に入れてあり、そのシーンで収得できるようにもしてあります。
すでに本番環境に反映済みですがこれでいいんでしょうか？

**Comment by snext1220** [comment]
ありがとうございます！
仮実績は現時点で実績100％にならないようにするためのガードだけなので、それで大丈夫だと思います。お手数をおかけしましたm(_ _)m

@Salvadors-cabin さん＞お手数ですが、stext.xml含めたGitHub環境の更新をお願いいたしますm(_ _)m

**Comment by snext1220** [comment]
April Updateにつきまして、Reminderでございます。
〆までまだありますが、大規模Updateとなりますため（バグ修正にも時間がかかる可能性があるため）、問題ある場合には単発でもお早めにご指摘戴けますと幸いです。
https://github.com/snext1220/stext/milestone/7
お忙しいところ恐縮ですが、引き続きどうぞよろしくお願いします。

＃SText本体とコード上の依存性もあるため、「New Playground」「New サイト」「Backup統合」の3点は同時リリースとさせてください（コードを二重管理しないと、個別リリースが困難）。また、同じ理由で、これらの案件リリースまでは新規機能も凍結とさせて戴きたく、恐縮ですが、ご了承くださいm(_ _)m

**Comment by Salvadors-cabin** [comment]
STest本番環境およびGitHUB環境の更新を行いましたので連絡します。

■黄泉に送るレクイエム
・最新ファイルをGitHUBへアップ
・最新ファイルを本番環境にアップ

■STextサイト(stext.xml)
・「レクイエム」シナリオ紹介を公開
・「そのドラ」クリア実績更新、紹介画像を変更
・「金竜」「ネゴシエーター」の（仮）を削除
・下記シナリオのintro.pngをcaptureフォルダにアップし、パスを修正
  「占い」「そのスレ」「テンペスト」「ゼロ」「ラミディア」「謙信」

■GitHUB
・「そのドラ」本番環境からコピー
・下記シナリオの本番環境からintro.pngをコピー
 「占い」「そのスレ」「テンペスト」「ゼロ」「ラミディア」「謙信」
・stext.xmlを本番環境からコピー

よろしくお願いしますー

**Comment by snext1220** [comment]
@Salvadors-cabin さん＞
大量のご対応、ありがとうございます！
一点のみ、stext.xmlの紹介文ですが、段落間が詰まっておりますため、適宜空行を開けて戴いた方が良さそうです（他との統一の意味でも）。お手数をおかけしまして、申し訳ありません。。m(_ _)m

他の皆さま＞
intro.pngについて、一部のシナリオで.png以外を使われているものがあるようで（すべて確認してませんが、heroなど）、以下Issueの対応で正しく動作しなくなる可能性があります。お手数ですが、.png形式での差し替えをお願いできますと幸いですm(_ _)m
https://github.com/snext1220/stext/issues/99

**Comment by Salvadors-cabin** [comment]
>一点のみ、stext.xmlの紹介文ですが、段落間が詰まっておりますため、適宜空行を開けて戴いた方が良さそうです

先ほど修正しました。GitHUBも更新済です。
よろしくお願いしますー

**Comment by snext1220** [comment]
お手数をおかけしました！ありがとうございます～

**Comment by toki-sor1** [comment]
@Salvadors-cabin さん、大量更新お疲れ様です！
@snext1220 さん、intro.pngについてご連絡ありがとうございます！
先程、GitHubのheroフォルダ内、本番環境のheroフォルダ内、stext.xmlを更新完了しました！
（heroのintro画像をPNGに修正＆stext.xmlではintro.pngに修正））

**Comment by snext1220** [comment]
@toki-sor1 さん＞
intro.pngの更新、ありがとうございます！
SEM対応はNewサイトからになりますが、徐々に実装できればと思いますので、お待ちくださいませ。

＃New Playground、Newサイト等、 @toki-sor1 さんへのご相談事項が立て続いてしまい申し訳ありませんが、引き続きよろしくお願いいたしますm(_ _)m
https://github.com/snext1220/stext/issues?q=assignee%3Atoki-sor1+is%3Aopen

**Comment by snext1220** [comment]
スタッフの皆さま＞
April Updateですが、明後日3/2にてCloseとなります。
https://github.com/snext1220/stext/milestone/7
お忙しいところお手数ですが、未了のものにつきまして動作テストの上、ステータスの○をお願いいたしますm(_ _)m

**Comment by snext1220** [comment]
# 重要

サイトリニューアル関係で、早ければ明日から作業を開始予定です。
旧ページからのリダイレクトをはじめ、権限設定の振り替えなど、作業が多岐に亘るため、以下の日時でのFTP／GitHubの更新は中止戴けますと幸いです。

日時：03/02 8:00～ 03/02 15:00（終了）
＃実際にアクセスできない時間は極力短くする予定ですが、それでもこの期間は、不安定になる可能性があるので、ご了承ください。

また、今回リニューアルでは、現在のFTPのファイルを一旦削除し、GitHub最新版ファイルを改めて一括Upload致します。よって、FTP／GitHub間に食い違いがある場合はクリア（ダウングレード）する可能性があるので、ご注意ください。万が一、そのような状況あります場合は、急ぎお知らせくださいませ。

**Comment by snext1220** [comment]
# Newサイト移行、終了しました

ざざっとではありますが、Newサイト移行を完了いたしました。
作業内容は以下です（大まかなので、気になる点はお聞きください）。

### Newサイト移行作業内容

- [x] 新サイトへの画像反映
- [x] ユーティリティ動作確認
- [x] 旧サイトからの不要リソース削除
- [x] 旧サイト動作／表示確認
- [x] ゲーム画面動作確認（サンプリング）
- [x] 旧サイトからのリダイレクト
- [x] FTPアクセス権限付け替え
- [x] stext.xml更新
- [x] New Playground展開（リンク付け替えのみ）
- [x] 新機能リリース
- [x] 総合テスト

### 皆さまへのお願い＆申し送り

+ April Updateについては、皆さまの確認後（○になった後）、Closeとさせていただきます。引き続きご確認のほどをお願いいたします。

+ 相変わらず突貫で作業していますので、細かな誤りなどは残っているかもしれません。順次修正してまいりますので、ご指摘戴けますと幸いです。
＃特にシナリオ、ユーティリティについては皆さまの方でもご確認いただけますとm(_ _)m

+ @cocotori さん＞New サイト移行に伴い、お手数ですが、王さまBot自動ツイのURL差替をお願いできますでしょうかm(_ _)m 現在、最低限旧サイトからのリダイレクトをかけていますが、今回、Newサイトで1:nにページが分かれているため、現状だとすべてシナリオページに飛んでしまうと思われます（また、以下リンク新機能についても参照ください）。

+ @Salvadors-cabin さん＞ドラスレ画像については若干小さめだったので、サイズ指定を修正しました。今後も、縦横比が他と異なる画像は調整戴いた方が良いかもしれません。お手数ですが、宜しくお願いいたしますm(_ _)m

+ @toki-sor1 さん＞ メニュー画像等のご対応ありがとうございました。Banner、New Playgroundなど残存については、またゆるゆるお付き合い頂けますと幸いです。

+ New Playgroundについては問題発生時にも影響を限定的にするために、今回はGitHubに据え置きとし、各ページからリンクを貼るに留めました。今後、New サイトが落ち着いたいところで、本番サイトに移行の予定です（実行上は差し支えないはずです）。

+ 新サイトで「https://web-deli.com/sorcerian/text/#begin 」のようにすることで、該当のシナリオ紹介へ直接飛ぶようになっています。シナリオ紹介時にご利用ください。

+ GitHub／FTPの更新凍結も現時点をもって解除致します。ご協力ありがとうございました。

**Comment by snext1220** [comment]
April Updateの動作テスト、ご対応ありがとうございました＞皆さま
こちらは一応終了、なのですが、アイコン／バナー作成等の残があるため、管理上、そちらの終了でもってCloseとしてまいりますね（備忘録代わりで、催促ではありませんのでご容赦を…^^;）。

また、伴い、May Updateを立ち上げています。
https://github.com/snext1220/stext/milestone/8
今後、状況見ながら追加／削除の予定ですが、「これはどうなっとるのか」などあればご指摘お願いします。もちろん、昨年からの課題「半自動化」「連作対応」関連のリクエスト、完全新規のリクエストも歓迎です。

**Comment by snext1220** [comment]
あ、今回、New サイトのキャッチフレーズや文章、説明系PPTは**結構適当に書きなぐってた**のですが、特にNGも出ず、むしろ心配に^^; こんな感じでどうよ、などあれば、後追いでもよろしくお願いします～

**Comment by snext1220** [comment]
スタッフ内Ｄでも流していますが、一応、こちらでも。

---

STextロードマップ（勿論、主なテーマのみ）をProjectでまとめてみました。
https://github.com/snext1220/stext/projects/3 
TL／Issueで過去話題になったものですが、勿論、決まっているものではありませんので、まずはご相談の叩き台と、思惑の共有?とお考え戴けますと。

詳細は、改めて掲示板にまとめさせていただくとして、まずは

+ Playground検証企画（ミドル70）
+ 連作検討企画（幕末）

について、軽く感触戴ければ幸いです。かなり先の話ですが、突貫になってしまったドラモードの反省を活かして^^;、ご賛同得られるようであれば、ゆるゆる議論させていただければとm(_ _)m
#重ねてですが、70scene、幕末等のテーマは仮置きしているだけで、前提ではないと思っています。

**Comment by toki-sor1** [comment]
STextロードマップの作成ありがとうございました～。
Issueの数が多くなってくると、確認すべきIssueを見失ってしまうこともあるので、Projectのようにすぐに確認できて全体も見渡せるまとめはgoodだと思います！

> Playground検証企画（ミドル70）

ミニ30祭りでもシナリオ作成と同時にPlayground検証ができて、機能の把握やエラー等の発見にも有効でしたもんね。
又、ミニ30祭りではシーン30縛りが結構厳しい印象だったので、中編くらいのシーン70縛りは、内容的にも長すぎず短すぎずで丁度良さそうな感じがします。

> 連作検討企画（幕末）

リオさんの幕末ソーサリアンシナリオがとても本格的で夢中になって拝読していたので、幕末が舞台のシナリオも良いなぁと思いました！
ただ、歴史シナリオということで、きっちり正しい歴史を描くとまではいかなくても、ある程度は歴史を改めて復習し、それに沿った設定にする必要はあるかなと思っているので、（私の場合はですが）幾つかシナリオの候補となる人物や事件などを挙げていただいて、その中から選ばせていただいた方が歴史の復習もし易いかなぁと思いました。

**Comment by snext1220** [comment]
ロードマップのご確認ありがとうございました！

見失って＞ですよね^^; もちろん、Projectに載せているのは一部のIssueですが、なるべく全体方針に関わるものは、ここで見渡せるようにできればと（もちろん、必要と思われたものは、皆さまの方でもご自由に追加くださいませ）。
＃逆に、Projectでは細かなことは書かずに、必要になった場合は新たにIssueを立ち上げつつ、概観を維持していければと思っていますので、詳細はIssueへの投稿をお願いしますm(_ _)m

### Playground検証企画（ミドル70）

ご賛同ありがとうございます！
Scene数もそれなり問題なさそうで、良かったです^^
＃実際には、70～100くらいの幅を持たせながらになるかもですがｗ、とりあえずは70前後という前提でご相談進めてまいりましょうか！

### 連作検討企画（幕末）

夢中に＞あ、ありがとうございます！シナコン時代からＴＬ上の反応も良い話題だったので、提案させていただきました^^;

歴史を改めて復習＞ですね～私も実は五稜郭を立ち上げる前は、まるで素人で図解幕末的な本から齧ってた覚えがｗ

> シナリオの候補となる人物や事件などを挙げていただいて～～

こちらは、まずはざっくりとですが、まとめてみました。
タイトルはほぼNext0401企画の時のものママです。

タイトル（例） | 事件 | 主な登場人物
-- | -- | --
壱：夷国到来！黒船来襲 | ペリー来航 | ペリー
弐：桜田門外の変 | 安政の大獄 | 井伊直弼
参：京都動乱 | 池田屋事件、禁門の変 | 新選組
肆：薩摩はなまむぎの夢を見るか？ | 生麦事件 | 薩摩藩、島津久光
伍：奇兵隊 | 長州征伐、長州藩クーデター | 高杉晋作
陸：最後の将軍 | 鳥羽伏見の戦い | 徳川慶喜
漆：上野に咲く朱き花 | 上野戦争 | 大村益次郎、勝海舟
捌：会津炎上 | 会津戦争 | 白虎隊、松平容保
玖：壬生浪の旗は函館に | 函館戦争 | 土方歳三、榎本武揚
終：西南に没す | 西南戦争 | 西郷隆盛、大久保利通


あくまで案ですし、参加者の見込みに応じて、シナリオ数は適宜間引く（あるいは追加する）と思いますし、そもそも幕末に西南戦争は入るのか、とかいろいろありますがｗ、まずは叩き台とご参考になれば～
＃この流れであれば、シリーズ全体を通して、登場する支援キャラは（たとえば）人気も高い土方歳三を想定しています。

皆さまの凡その合意を得られてからだと思いますが、もちろん、細かい全体ストーリーは徐々にブレイクダウンしていければと思っています。

如何でしょうか。
他の皆さまも引き続きご意見戴ければ幸いですm(_ _)m

＃あ、スタッフ以外でも、なんとなく気になったという方はぜひ口をはさんでやってください^^;

**Comment by cocotori** [comment]
ロードマップ作成ありがとうございます！
ざっくりとでも一年の計画が見えてくると、
それぞれの企画の流れを意識できてよいですね。

・Playground検証企画（ミドル70）
いいと思います！
ご提案の通りで問題ありません。
30シーンの次は、少し長めのシナリオに挑戦、
というのも面白そうです。

ただ一点、シーン数はプレイする側からすると
あまり重要ではないのかなと思っています。
どちらかと言うとプレイ時間OO分以内
（何を持ってプレイ時間とするかは作者次第。
　1周でもいいし、総プレイ時間でもいいし。
　シーン数は自由。）
みたいな感じだと、プレイヤーさんがわかりやすいのかなと思いました。

ただ、どちらかと言うと執筆者向けの企画とも言えますし、
シーン数という明確な基準があるのもわかりやすいと思いますので、
どちらでも大丈夫です。


・連作検討企画（幕末）
こちらはごめんなさい、
わたしがあまりイメージわいてないです。

なにか参考に資料等あればありがたいです。
（リオさんのページにありますかね？）

タイトルを拝見する限り、なんとなく
歴史を時系列的に追っていく連作シナリオ、といった感じでしょうか。

和風なソーサリアン、面白そうですね！
ドラゴンモードのときもそうでしたが、
同じドラゴンというテーマからも
様々な作品が生まれたので、
幕末という設定からも、本当に作者さんそれぞれの色が出た
シナリオが出来上がるんじゃないかとわくわくします。

ちょっとまだどのような形になるのかわかっていませんが、
基本的に賛成です。
一年間で、シーン数縛りの自由形シナリオと、
テーマ縛りのシナリオをこなしていき、
何年か回していけたら楽しそうですよね。


・ホームページリニューアル
こちら、だいぶ反応が遅くなってしまってすみません・・・！
デザイン据え置きと言ってしまった張本人ですが、
なにか不満があるとかではないので、
個人的にはこのままでも大丈夫かとは思っています。
というか、わたしもノーアイデアで申し訳なく・・・

本当に微力ながらになってしまうのですが、
もしもイラスト等でお力になれるなら
可能な限り協力したいと思います。

**Comment by Salvadors-cabin** [comment]
お疲れ様です。

「PlayGround」縛りは問題ないと思います。
ただ、シーン数についてはこれまでの感触で、ストーリー重視のシナリオと
探索重視のシナリオで違うんじゃないかと思うんですよ。
じゃあどうすればよいか、の答えは思いつかないですが・・・

「幕末」縛りはちょっとキツすぎると思いますね。
「戦国末期～幕末」（「江戸時代」といったほうがよい？）ぐらいの緩さの方が入りやすいと思います。

**Comment by snext1220** [comment]
cocoさん、サルバさん、
早速のお返事ありがとうございます！

> 一年間で、シーン数縛りの自由形シナリオと、テーマ縛りのシナリオをこなしていき、何年か回していけたら楽しそうですよね。

おぉ、まさに同じことを考えていましたｗ
引き続き（その場の思いつきではありますけど）諸々企画挙げていきたいと思いますので、気長にお付き合いください～

> ホームページリニューアル
> デザイン据え置きと言ってしまった張本人ですが、なにか不満があるとかではないので、個人的にはこのままでも大丈夫かとは思っています。

こちらも言及ありがとうございます。
なかなか自分だけだと気づけない（＆チラッと思っても、ま、いいかと流してしまう）ことも多いので^^;、コメント助かります！

デザインについては、ゆるゆると変えていければと思っていますので、もし思いつかれることがあれば、引き続きご意見よろしくお願いいたします～

> もしもイラスト等でお力になれるなら可能な限り協力したいと思います。

お申し出、ありがとうございます！
イラストは、@toki-sor1 さんにご負担が集中しておりましたので、助かりますm(_ _)m
@toki-sor1 さん＞ 今後、こんな感じで進められそう、などあればお願いします。

★

ということで?、とりあえず皆さまに実施そのものはご賛同いただきましたので、後日、それぞれ独立したスレを立ち上げたいと思います（個々のお返事はそちらにて改めて）。改めて、どうぞよろしくお願いいたします～

**Comment by toki-sor1** [comment]
> もしもイラスト等でお力になれるなら可能な限り協力したいと思います。

> イラストは、@toki-sor1 さんにご負担が集中しておりましたので、助かりますm(_ _)m
@toki-sor1 さん＞ 今後、こんな感じで進められそう、などあればお願いします。

@cocotori さん、心強いお言葉ありがとうございます！
@snext1220 さん、お気遣いありがとうございます！
イラストについてですが、今まで0401計画、STextの両企画でイラスト（ドット絵含む）が必要になった（あったらいいなと感じた）場面をまとめてみました～。

#### 1. バナー等のWebサイト素材（作成時の優先度：高　※現在は中程度？）
★ファイル形式：PNG
- 先日STextサイト素材を作成し、とりあえず一旦落ち着いたかなと思います。
- 素材の修正・改良が必要と判断した場合、その都度対応という感じでしょうか。

#### 2. Playground用のアイコン等のドット絵素材（作成時の優先度：高）
★ファイル形式：PNG
- こちらは必要になれば作成という感じなのですが、 https://github.com/snext1220/stext/issues/82 の関係で新たなドット絵等の素材が必要になる可能性があります。

#### 3. シナリオの挿絵（現在はときのじはご依頼の受注休止中）
★挿絵サイズ：横500px × 縦300px（こちらは基準なので、違ってもOK！）
★ファイル形式：PNGで統一
  - 皆さんにお気遣いいただき、現在では持ち込みメインにしていただいております……ありがとうございます……；；
  - 描きたいと思ったシーンを描かせていただく（＝シーン選択はお任せ）ファンアートのような形も有りかなと思っていますが、その場合は下記の **「5. ファンアート等のイラスト・ドット絵（自由）」** のような感じが良いかもしれません。

#### 4. シナリオ宣伝用イラスト（作成時の優先度：自由）
#### 5. ファンアート等のイラスト・ドット絵（作成時の優先度：自由）
★画像サイズ、ファイル形式：可能であればPNGで統一（※）
（※他形式の方が良いという場合は要相談。Twitter用はJPEG、サイト掲載用はPNGと使い分けも有りかと思います）
- Twitterのツイートとしてアップ、サイトのGalleryに掲載、ご自身のサイト等への掲載が主な用途でしょうか。特に制限や〆切りもなく、完全に任意・自由ですね。
- こちらで描いたイラストを、シナリオの挿絵やサイトのシナリオ紹介用イラストとして掲載するというのも、既にココさんが実践されていましたね！　グッドアイデア！

イラスト関連の作業は皆さんにお気遣いいただき、作業量を減らしていただいていますが、時々作業が集中することがあるので、ココさんのお言葉が本当に心強いです！　ありがとうございます！！

ココさんには、度々シナリオに関連した素敵なイラストを描いていただいていますので、今後もココさんの食指が動いた時にイラストが拝見出来ましたら嬉しいです～！（親指ぐっ）

イラスト関連の作業に限らず、皆さん各々にお忙しい状態ですので、どうかご無理のない範囲でゆるゆる～っとよろしくお願い致します～m(_ _)m

**Comment by snext1220** [comment]
@toki-sor1 さん、言及ありがとうございます！

一点のみ、丁度話題に上ったので、ファイル形式についてです。
可能な範囲で、ではあるのですが、ファイル形式は.pngで統一は可能でしょうか。

というのも、

+ サイト掲載の際、ほとんど手作業だもので、意外と間違いのもとに^^;（機械的にコピペしていったら反映されず、悩んでたら拡張子違いということが時折；）
+ 同じくプログラムの関係で、拡張子を意識しなくて良い分、コードを多少シンプルにできる

などの要因があるためです。

勿論、ファイルサイズ、画質、その他の要因があるかもなので、そうした時には要相談というレベルでございます～

**Comment by toki-sor1** [comment]
補足ありがとうございます！
先程、上のIssueを可能な範囲で「.png」に統一（ただし、他形式が良い場合は要相談）という意味合いの文章に修正致しました～。

**Comment by cocotori** [comment]
>ときのじさん

お返事遅くなりましたが
イラスト業務の洗い出し、ありがとうございます！

とても多岐にわたっていて
ときさんの負荷の多さが忍ばれます。
うう、ほんといつもありがとうございます・・・

すぐにどれならできる、というのがなくて申し訳ないのですけど、
ファンアート的なものはこれかも描いていって
盛り上げていけたらと思います。

**Comment by snext1220** [comment]
May Updateの対応を完了しました。
https://github.com/snext1220/stext/milestone/8
お手数ですが、動作テストのご対応をお願いいたします＞スタッフの皆さま

＃画像作成／加工にご協力いただきました @toki-sor1 さん、ありがとうございました！

今回は、Issue整理のため、wontfix案件が多くなっています。もし「これは消さないで」などあれば、コメント戴けますと。
＃特に「デバッグモード」などはやや気になっています。

**Comment by snext1220** [comment]
SText、Twitterカード対応しています。
現在の表示状況は、こんな感じです（正確にはブログ上なのでTwitterカードではないですが^^;）。
https://sorcerian.hateblo.jp/entry/2019/03/31/000000
https://sorcerian.hateblo.jp/entry/2019/04/01/000000
https://sorcerian.hateblo.jp/entry/2019/04/02/101343
https://sorcerian.hateblo.jp/entry/2019/03/30/000000
＃紹介文は暫定で、改めて文章加筆の予定です。

intro要素のkeywords／descriptionを入れて戴くと、見栄えもかなり高まると思うので、（任意ではありますが）是非シナリオデータを更新してやってください。
＃そして、是非ご自分のブログ、Twitterなどでもご活用いただければとm(_ _)m

@Salvadors-cabin さん＞お手数ですが、ゲストの皆さまにもご連絡をお願いできますと幸いです。

@cocotori さん＞お手数ですが、引き続き王さまbotのURL更新、どうぞよろしくお願いいたします（ただ、画像があると、Twitterカードが無視されるかもなので、要調整かも）。

**Comment by Salvadors-cabin** [comment]
intro要素keywords,desctiptionについて、賢治さん、ちゃなさん、RYUさん、咲華さんに連絡しておきました。
自シナもおいおい対応していきますー

**Comment by snext1220** [comment]
お忙しいところ、ありがとうございます！
自シナ＞よろしくお願いいたします～
