### ISSUE TITLE
雑談＆作業報告スレ

### ISSUE THREAD

**Issue by snext1220** [snext1220/snext-management#7]
雑談用にどうぞ。
スレを立てるほどでない話題、簡単な作業報告などもこちらでしていただくと、個別のスレが極端に長くなるのを避けられるかもしれません。まあ、適当にｗ

**Comment by snext1220** [comment]
掲示板（https://sorcerian.progoo.com/bbs/sorcerian_tree_r_1844.html ）から移動しています。

ときのじさん：おつありでした！

寂しい＞そうですよね...最初の投稿が2012年ですから、足掛け8年ですか...感慨深いとだけでは言い表せないものがありますよ^^;

掲示板サービスは、この1月で一気にそちこちで廃止になっているようですね。同じ会社が運営していたのか、元サービスが消えて、その影響が各サービスに波及したのかは、よく判らないのですが；、セミクローズな議論の場はLineやSlackなどに移動しているのだと思います（いずれも長い書き込みには向かないので、そういう議論はどこへ移動しているんだろう？？^^;）。

今までの記録＞こちらについてはCSVでデータをダウンロードできましたので、以下に貼っておきますね。正直、可読性には欠ける＆あえて読みやすいようにする気にもならないのでｗ、記念品程度かもしれませんが；
[data_sorcerian_20190118105139.zip](https://github.com/snext1220/snext-management/files/2771309/data_sorcerian_20190118105139.zip)

ということで、改めて新天地（Issue）でこちらこそよろしくお願いします！

**Comment by Salvadors-cabin** [comment]
いろいろな思い出が詰まった掲示板でしたねー。
それにしても、こうした活動がこんなに長く続いているのはスゴイと思います。
この原動力はみなさんの情熱だとホントに感じます！

「寂しい」つながりでいくつか閉鎖ネタを。
Yahoo!ジオシティーズ( https://geocities.yahoo.co.jp/ )が３月末でサービス終了です。
で、私の個人サイト( http://www.salvadors-cabin.net/ )がこのジオシティーズのサイト構築ツールを使っていまして、サービス終了とともに更新が困難になってしまいました。
いったん閉鎖して、また機会があれば別の形で復活させようと思っています。
（私のサイトのアドレスはダミーサイトに繋いでリンク切れにはしないつもりです）

あと、ソーサリアンオンライン記念Wikiサイト( http://meghummer.game.coocan.jp/index.php?SorcerianOnline )も、長らく運営をされている方から２月～５月の間で閉鎖すると連絡がありました。
ソーサリアンオンラインもサービス終了から６年経ち、まあ閉鎖も仕方ないですね。
iOS版もオンライン版も、もうほとんど痕跡がなくなってしまったのは寂しい限りです。

新掲示板でもよろしくおねがいします！

**Comment by snext1220** [comment]
Salvador-cabin、記念wikiいずれも閉鎖ですか。。
いずれも「新時代の～」からリンクさせていただいていましたが、ますます寂しくなりますね。。以前「ドラスレラボ」が消えて、いよいよソーサリアンを主に扱ったサイトはデータルームさんとNextサイト位になってしまうのでしょうか。
＃Salvador-cabin、史料としても貴重だと思うので、是非ともまた復活させてやってください～

SNextチーム、元々0401企画のための集まりだったのが、足掛け8年ですから、振り返ってみたら、いつの間にか歴史のようなものが積み上げられていた、という感じですねｗ
さまざまな形で関わってくださった皆様には、本当に感謝しかありません。

個人的には、ここまで来たら、はい に なるまでやってるつもりなので、宜しければ引き続きお付き合いくださいませ。

**Comment by Salvadors-cabin** [comment]
>＃Salvador-cabin、史料としても貴重だと思うので、是非ともまた復活させてやってください～

そう言ってもらえると嬉しいです。いずれ復活したいです。

ところで、この掲示板(issue)ってどうやってファイル添付するんですかね。
リンクは貼り付けられるみたいですが、、

**Comment by snext1220** [comment]
是非！

添付＞ファイルのD＆Dでいけるはずです～（ファイル種類は限定されるようですが）

**Comment by Salvadors-cabin** [comment]
>添付＞ファイルのD＆Dでいけるはずです～（ファイル種類は限定されるようですが）

ドラッグ＆ドロップでいけるんですね。なるほどー、ありがとうございます。
調べてみたところ、添付可能なファイル種類がGIF, JPEG,JPG,PNG,DOCX,GZ,LOG,PDF,PPTX,TXT,XLSX,ZIPだけに制限されるのと、サイズは10MBまでのようでした。

**Comment by snext1220** [comment]
お疲れ様です。
遅まきながら、#11 での若干話題になっていた新規構文について補足です。

まず、`<![CDATA[～]]>`については、GBAT2SText、New Playgroundを利用される場合にはご不要です。
CDATAそのものは「&」が誤認識されることを防ぐための構文ですが、これらの環境では「`&amp;`」という代替文字（＝無害な文字）に置き換えるためです。

よって、エディターで作成されている皆さまも「&」を「`&amp;`」とした場合には、CDATAはご不要になります。

※マニュアルでは、単に「GBAT2SText、New Playgroundを利用する場合は不要」とだけ書いておいたのですが、若干混乱が起こっているようなので、補足とさせていただきますm(_ _)m

**Comment by snext1220** [comment]
旧掲示板、本日終了となります。
先の通り、バックアップは最低限とっていますが、画像などはすべて消えますし、その他、なにか気になる点がありましたら、一応、最後の確認タイミングということで、ご連絡までに。

**Comment by snext1220** [comment]
@toki-sor1 さん＞
話題が逸れつつあったので、 #10 から移動いたしました。

> それらが集約された「ここさえ見ればOK！」というページは必要ですよね；

はい～現時点で特に気になっているのが、Wikiの「シナリオの修正と調整・公開前準備のチェック項目」でして。折角まとめて戴いたテキストが、ドラモードだけのためのものになってしまうのもアレなので、なにかしらまとめていきたいなとは。
＃現時点ではマニュアルとも重複してしまうので、インデックス的なものになるのかもしれません（イマイチ、ノーアイデア^^;）

Newサイトの［Post］ページについても、実は、咲華さんにＤで諸々投稿に関するご質問を戴いていたのですが、その際の回答をまとめ直したものでした。

この辺の整備って、中々内輪だとできないので（なんとなくテキストだけが増えていく^^;）、ドラモードで沢山のゲストさんに参加頂いたこの機会になんとかしていければいいな～と。

> 今後は上記Issueを活用＆ゲスト様にご案内できればと思います。

ありがとうございます！
Issue（デバッグモード）については、とりあえず項目を挙げているだけなので、「何を優先的に自動チェックの対象にしていくか」は、皆さまのご要望で決めていければと。すべてをチェックするのはメンテの手間的に難しいので、間違えやすいものから重点管理してまいりますので、ご要望是非よろしくお願いしますm(_ _)m

**Comment by snext1220** [comment]
STextの今後の進行について、以下Issueから移動しましたm(_ _)m
https://github.com/snext1220/stext/issues/87#issuecomment-469029409

> ミドル70祭（New Playground縛り）は良いアイデアだと思います！

ご賛同ありがとうございます！
ドラモードも本編Vol.6までは凡そ完成かなと思いましたので、新企画についても掲示板の方でスレ立てして、順次ご相談できればと思っております。
＃連作の件（ https://github.com/snext1220/stext/issues/79 ）もあるので、其々どう進めるのかは悩ましいのですが、ドラモードが結構突貫だったので、話だけでも早めにしていれば、創作時間は確保しやすくなるのかな、という思惑も^^;

> 70祭開催は11月以降を予定～～

あまり拘ってもではあるのですが、月刊がここまで続いてきたので、可能であれば、（SText続いているぜ感を出す意味でも）ある程度継続していければよいな～とは^^;（Newサイト／Playgroundを突貫したのも、やるならシナリオストックがある、狭間のここしか！という思惑がありました^^;）もちろん、あくまで目標値ですし、変な無理はしないが大前提ではあります。

> もしかしたら公開が8月にずれ込んでしまうかもしれませんが、当初の予定通り7月締切＋公開を目指して頑張ります……！

恐縮でございます（汗
私もwiki見直して、ああ、結構曖昧になっていたな～と；
こちらこそ、失礼しました；；
勿論、目標値ではございますし、難しい場合はお知らせくださいませ。。
＃ 一応、Vol.6までは内容明らかになっていますが、Vol.7が不明なので、概要だけでもそろそろ伺った方が良いですかね？？

ドラモードが大きな企画だったので、全体としての今後がやや曖昧になっていたのですが、こちらについても、またゆるゆるとお話させてくださいませm(_ _)m

**Comment by snext1220** [comment]
長くもなってきたので、スタッフＤから移動させて戴いておりますm(_ _)m

### 募集系に改善の余地あり

> wikiも募集要項などをまとめる場としては、やや見辛い印象もあったので、stext.xmlのようにサイトの一部のページを管理・編集出来るようにしてまとめるのも良いかも、と思ったりも…？

おっと、見づらかったですか^^;
stext.xmlについては勿論可能なのですが、あくまで定型文をまとめる前提で作られており、できることは限定されているので、長文＆不定形には不向き、かもしれません；
＃できることはできますが、結局、HTMLを書かなければならないか、プログラム側で作り込みをするしかないという…＞＜

一応、代替案としては「新時代～」のアカウントを開放して、そちらで募集要項を掲載＆更新、ということはできるかも？（こちらはMarkdownなので、比較的、GirHubに近い形でメンテはできるかと）

ただ、ドラ募集要項（詳細）のように長文化してしまうと、どのサイトを利用しても、相応にレイアウトに手間をかけないと、大きな改善は難しいかも、しれませんです^^;（企画案内は、言い方は悪いですが、所詮揮発性のドキュメントなので、そこに注力してしまうのは勿体なく；）

ということで、、、

> 今回のドラモードの仕様が特殊であったり、ギリギリに仕様が決定したりとバタバタしていたのもあり、外部投稿者様のフォローも余裕がなくなってしまい、事前準備の大切さを痛感しましたね…；

に対してのお返事も兼ねてしまうのですが、まずは、執筆者さんからよく出た質問などを、共通マニュアルとしてまとめ、案内そのものを短くすることを優先した方が良いのかなと^^;
＃ https://github.com/snext1220/stext/issues/76#issuecomment-471147550 とも共通の意見ですね～

おそらく純粋な企画固有の紹介に絞れれば、かなり短縮もできて、自ずと見通しもよくなる＆結果として、個別企画での負担も軽減できるのではないかと…！
如何なものでしょうか？

### 自動計算の弊害

> 確かに、手軽に遊べるようになった一方で、慎重さの欠如はあると思いますね～（ものによりますが、難しいことを考えずボタンを押しているだけで遊べるソシャゲ的な？）

そうなんですよね...実は、scene要素のhp、mp等の属性も若干そのきらいがあったので、拙作ではあまり利用していない感じでした；
システムとして、SEでダメージ表現（やられた！）を標準化するなど、検討の必要があるのかもしれません^^;（SEの再生タイミングが難しいのですが；）

> 特殊ルールの場合は特に説明には気をつけないと…と思いました；

まさに。利用していないMarkdownもあるので、「`>`」系などにレイアウト付けすることは考えてみたいと思います！

そもそも特殊ルールの配分（説明の総量）はあると思うので、その辺のバランスも、ですね^^;
トラ、ゼロはいずれも短編の中である程度の分量感をもって遊んでもらうかを目指していたので、ダイスルールを多めに配分しているのですが、ミドル企画ではシーン数にも余裕ができるので、一寸分岐（物語？）に力点を戻そうかなとは思っています。

> 「危険度に応じて式の色を変える」など~~

はい、黒（太字）、紫、赤で丁度区別もしやすいかも！

**Comment by Salvadors-cabin** [comment]
RYUさんから連絡があり、「そのスレ第三部test版1」をGitHUBテスト環境にアップしましたー。
https://snext1220.github.io/stext/index.html?id=slayer

今後公開に向けてRYUさんと調整していきたいと思います。

**Comment by snext1220** [comment]
Upありがとうございます～こちらでもDL＆確認しております。
お手数ですが、ご調整どうぞよろしくお願いいたします！

＃現在、cocoさんの協力者がstext.xml更新、GitHubのみ反映済みの状態のようなので（本番未反映）、Upの際はご注意いただいた方が良いかもしれません。

**Comment by Salvadors-cabin** [comment]
RYUさんから連絡があり、「そのスレ第三部test版2」をGitHUBテスト環境にアップしましたー。
問題なければcocotoriさんの「協力者」以降に公開する予定です。

**Comment by Salvadors-cabin** [comment]
先ほど「そのスレ第三部test版3-4」をGitHUBテスト環境にアップしました。
おそらくこれが公開版になると思われます。

５月の更新計画を連絡しておきます。
5/10 「その名はドラゴンスレイヤー」第三部更新
5/17 STextサイト「ドラゴンネゴシエーター」紹介文公開
5/25 「ドラゴンネゴシエーター」本編公開
5/31 「ゼロの創造」微修正版更新

よろしくお願いしますー

**Comment by snext1220** [comment]
反映＆ご予定のご連絡有難うございます、承知いたしました！

ドラスレの方はまだ見きれていないのですが、公開までに確認してまいりたいと思います。
お手数ですが、皆さまの方でもテストプレイよろしくお願いします～

**Comment by toki-sor1** [comment]
サルバさん、各種作業お疲れ様です！
また、「その名はドラゴンスレイヤー」第三部のテストプレイのご報告がギリギリになってしまい、申し訳ありません……！

こちら、**シナリオ専用スレッドを立てさせていただきました。**
今後は #17 をご利用いただけましたら幸いです。

**Comment by Salvadors-cabin** [comment]
「ゼロの創造」を更新しましたのでご連絡します。
主な変更点は以下です。
・マンティコア戦、町、ブザッティ戦のHP値変更の自動化
・戦闘で敗戦したときの分岐追加
・description,keywordの追加
・素材カテゴリ間違い修正

次は「ラミディア」の戦闘ダメージ計算改善を考えています。

**Comment by toki-sor1** [comment]
遅ればせながら更新お疲れ様です～！
新システム対応でシナリオが更にパワーアップしていますね！
こちらも遊ばせていただき、**一点気付いたところがありました。**

-  Scene 12007　敗戦時の分岐がないようです

次回は「ラミディア」の更新を予定されているのですね、承知しました！
よろしくお願い致します！

**Comment by Salvadors-cabin** [comment]
ときのじさん、ご指摘ありがとうございます。
テストしたつもりだったんですが、抜けてました・・
修正し、さきほど本番環境、GitHUB環境、Webサイトを更新しました。

＞ラミディア
前々からテーマとしていた、戦闘時敵HP減算の半自動化を考えています。
ときのじさんの「常闇」を参考にさせていただこうと思っておりますー

**Comment by Salvadors-cabin** [comment]
ゲームにおける著作権について気になる記事がありましたのでご紹介いたしますー
https://headlines.yahoo.co.jp/article?a=20190817-00577819-shincho-ent

これは、「小説版ドラクエ」の作者さんが「映画版ドラクエ」にキャラクターの名前を無断使用されたと訴えたという事案です。
「既存のキャラ名の使用」は、我々がグレーと呼んでいる二次創作に近いものがあります。

この訴訟の結果が出るまでは時間がかかりそうですが、記事を読む限り、
法律的にキャラクターの名前には著作権は認められないようです。
（まあ心情的には、立場の弱い小説作者さんを応援したい気持ちはありますが・・）

これを「ソーサリアン」に当てはめると、マニュアルなどに出てくる「デュエル」などの名前やユーザが考案したキャラ名にはF社の著作権は及ばないという事になるのではないかと思います。

**Comment by olreia** [comment]
ちゃなです。ご無沙汰しております。
サルバさん、ご教示ありがとうございます。

ゲーム界隈だと、D&Dの「ビホルダー」、ウィザードリーの呪文や「ワードナ」「トレボー」なんかが以前に物議を醸しましたね。著作権と商標では事情が異なりますし、国によって法規も違うので、なかなか複雑ですが……。
ちなみに拙作「金竜の陰謀」では、キングドラゴンのことをガルシスと表記しようとして、もしかして引っかかったら嫌だなあと思い、「ザ・ガルシス」→「ザガ」と呼ばせたりしています。

法律は素人なのでわかりませんが、映画制作者側に、小説版の主人公の名前を無断借用することによって視聴者を小説版の映画化と誤認させて利益を得る意図があったとしたら、それは不適切な行為かと思います。

他方、一般論としては、固有名詞に逐一著作権を認めていたら、今日び創作活動はできなくなってしまうのではという懸念があります。私も一応特徴的な名前とかは被ってないか検索かけてますけど、全部調べ尽くすのは無理ですから。心情的には小説作者を応援したいところですが、下手に勝訴して今後著作権が拡大解釈されるのも望ましくないように感じています。

いずれにせよ、クリエイターとしては、先駆者の作品に対して敬意を払うという基本をしっかり守ることが何より重要なのでしょう。著作権もそのための仕組みなのですから。
今後ともよろしくお願い申し上げます。

**Comment by Salvadors-cabin** [comment]
ちゃなさん、お久しぶりです。

>ゲーム界隈だと、D&Dの「ビホルダー」、ウィザードリーの呪文や「ワードナ」「トレボー」なんかが以前に物議を醸しましたね。

「ビホルダー」なんてザナドゥや他のゲームでもよく見かけたので、騒ぎになるまで「ゴブリン」「スケルトン」と同様の一般的なモンスター名と思っていました。

>心情的には小説作者を応援したいところですが、下手に勝訴して今後著作権が拡大解釈されるのも望ましくないように感じています。

そうですね。この事案が判決まで行くかどうかわかりませんが、少なくとも「キャラクター名には著作権は及ばない」という事が分かっただけで創作する上での指針にはなると思います。

>いずれにせよ、クリエイターとしては、先駆者の作品に対して敬意を払うという基本をしっかり守ることが何より重要なのでしょう。

この事案では「映画版ドラクエが小説版に対するリスペクトが無い」と、少なくとも小説作者さんは感じたという事でしょうね。
そのことを世間に知らしめるための提訴、といったところでしょうか。
ちょっと興味深いのは、小説版もゲームの二次創作という事ですね。執筆時にどういった契約（特に権利の範囲）をしていたのか気になるところです。

**Comment by Salvadors-cabin** [comment]
先日、SN2020公開検討のためにRPGアツマールについて調査していたところ、RPGツクールMZというMVの後継ソフトが2020年8月20日（木）に発売される事が分かりました。
https://tkool.jp/mz/how_to_buy/

考えてみればMVも発売から５年経ち、後継が現れても不思議ではないと思います。
おそらくMVはv1.6.2が最終バージョンなのでしょうね。
MVのプロジェクトをMZへコンバートする機能があったり、素材規格は変更なし、プラグインはJavaScriptのようなのである程度の互換性はあるようです。

RPGアツマールはブラウザで遊べるのが特徴ですが、スマホ操作を意識してタッチ（クリック）操作だけで遊べるようにしているお手軽なゲームが多い印象でした。
となると、キーボード操作が前提のSN2020では、スマホからアクセスしたユーザがいても遊べないという結果に・・・。

で、新製品のRPGツクールMZでは、「タッチUI追加」「オートセーブ機能追加」とありました。
また、スワイプによるスクロールもできるようになっているらしく、かなりスマホユーザ向けを意識しているようです。（２段ジャンプができるかどうかは不明）

今すぐ行うつもりはないですが、本気でWindows以外でのプレイを考えるのであればやはりスマホが中心になると思う為、MZ化も視野に入れなければならないなーという気はします。

ただ、アエリア社のiOS版のときも話題になったのですが、ソーサリアン自体がタッチ操作と親和性が悪く、なかなか浸透しなかった一因だったのですけどね。

**Comment by Salvadors-cabin** [comment]
お疲れ様ですー。
以前から個人的なテーマにしていました「ラミディアの魔法使い」のシステム改変を行っております。
GitHUBにアップしました。
https://snext1220.github.io/stext/index.html?id=ramidia

＜主な変更点＞
・ラベル変更 Free1=GP, Free2=WP, Free3=DP
・GP、WP、DPの自動計算
・鍛冶屋を出た時に武器を選択するシーンを追加し、WPを自動設定。
・戦闘ダメージ計算の自動化
・特殊戦闘ルール記述をBattleシートに移行
・intro,description属性追記

今回の改変で特殊ルールの戦闘の操作が全てクリック（タップ）で行えるようになりました！
どこかのタイミングで公開したいと思いますー

**Comment by snext1220** [comment]
MV2020共々お疲れ様です！
新機能対応でラミディアも遊びやすくなって、大幅リニューアルですね。
公開楽しみにしております～

**Comment by Salvadors-cabin** [comment]
>「ラミディアの魔法使い」

だいぶ間が空いてしまいましたが、問題無ければ今晩あたり公開したいと思いますー

**Comment by snext1220** [comment]
ありがとうございます！
STextも若干公開の間が空いてしまったので；、助かります！
どうぞ宜しくお願いいたします～

**Comment by toki-sor1** [comment]
お疲れ様です～！
本日「ラミディアの魔法使い」公開ですね、承知しました！
こちらもテストプレイを行い、ハッピーエンドまで遊べたことを確認しました！
遊び易くなっていて良いですね！
それでは、よろしくお願いいたします～！

**Comment by Salvadors-cabin** [comment]
ご確認ありがとうございます！
先ほど、本番環境更新、王様から告知、stext.xmlのGitHUB更新を完了しました。
長い時間かかりましたが、ようやく完成した感じですー

**Comment by toki-sor1** [comment]
更新ラッシュお疲れ様でした～！！
先ほどこちらもコメントを添えてRTさせていただきました～。

過去作を現在のシステムに合わせて改良するのは、大変な労力と気力が必要だと思いますが、サルバさんはじっくりと丁寧にシナリオを遊び易くされていて本当に凄いです…！
アップデートお疲れ様でした～！！
