### ISSUE TITLE
STextシナリオ「ドラゴンネゴシエーター」

### ISSUE THREAD

**Issue by Salvadors-cabin** [snext1220/snext-management#8]
サルバです。
「ドラゴンネゴシエーター」第一稿をGitHUBにアップしました。
フォルダ名は"negotiator"です。
https://snext1220.github.io/stext/index.html?id=negotiator

今回は、ドラゴンモードということで難易度にこだわってみました。
理不尽な難しさもソーサリアン（というか昔のゲームの）の特性でしたからね。
といいつづ、書いてるうちについついヒントを入れてしまうという・・・

今後、以下の点を追加予定です。
・挿絵（ソーサリアンOriginalからキャプチャ予定）
・難易度の調整
・解放条件の挿入（現在はテストのため入れてません）

よろしくお願いします。

**Comment by snext1220** [comment]
お疲れ様です～拝読させて戴きます！

**Comment by cocotori** [comment]
プレイさせてもらいました。
難しくはありますが、「軽はずみな行動はしない」という
ルールに気づけば自ずとクリアできるところ、いいですね。

倒すべき敵としてではないドラゴンも、新鮮味あって好きです。
人とのいろんな関係性を作り上げるドラゴンは、
単なる魔物と違う、複雑な営みや歴史を感じさせていいですね・・・

**Comment by Salvadors-cabin** [comment]
cocotoriさん、早速の感想ありがとうございます！
ドラゴンって、ファンタジー世界では中立のキャラも多いんですよね。
あと、人知を超えた存在という使われ方もよくされます。
そういった部分を出してみたかったのですが、なかなか難しかったです。
幸いドラモードにゲストさんも多数参加していただいて公開まで時間ができたので可能な改善はしていきたいと思っています！

**Comment by toki-sor1** [comment]
「ドラゴンネゴシエーター」ご執筆お疲れ様でした！
タイトルが発表された時から「格好良くてクールなタイトル！」と感激し、
どういう感じの物語なのかなと想像を巡らせていたので、今回一足早く
プレイさせていただけてウキウキです！

今作はMD版ソーサリアンの舞台やアイテム、エピソードも含まれていましたね。
プロローグの王さまの一言に驚いたのですが、その後に続く話になるほど納得ｗ
そして気になるキャラ「ヴィーグ」が登場し、ソーサリアンの仲間になりますが、
立場上踏み入れられない場所があることが分かり、そこで改めてヴィーグの
境遇に「あぁ、そうかぁ……」と寂しい気持ちに……。

その後、ペンタウァとレムス山を往復しますが、ペンタウァに帰還する
タイミングや交渉の進め方によってどんどんと情報が開示されてゆくのが
とても楽しいですね！（王さまがどもってるところにクスッとしてしまったりｗ）

そして、得た情報やアイテムを手に、どのタイミングでどの交渉のカードを
切るのが良いのか、と考えるところも武力での制圧とは違い、
平和的に問題を解決できる「交渉」ならではの難しさや面白さがあって、
とても良かったです！（鱗を粉砕した時の反応が意外で笑ってしまいましたｗ）

交渉成功後は「クリアでは、ない！？」と驚き、「まさか最後に何かが……」と
ヒヤヒヤしていたのですが、エンディングに辿り着いた時、今作のタイトルが
何故「ドラゴンネゴシエーター」なのか、その答えを得ることができて
納得すると共に、ドラゴンと人との関わり方について考えさせられました！

（今作をプレイして＆サルバさんのご返信を拝見し、ファルコムバイブルに
書かれていたドラゴンスレイヤーシリーズに出てくるドラゴンの解説を
思い出しました～。ドラゴン、本当に奥深いテーマですね！）

今作は戦闘がなく、気軽に遊べる長さなので「交渉」と「情報収集」に
集中できる構成も良かったですし、バッドエンドになっても気軽に
再スタートが切れるところも良いなぁと感じました！
（ペンタウァとの行き来で時間経過するところもメリハリがあって
良いなと思った勿論のこと、まさに原作という感じなのもGOODでした！）

今作の「ドラゴンを斃さずに問題を解決する」という平和な道が
選べるところも、SText版ドラゴンモードの醍醐味ですね！

そして、自シナリオではシャドードラゴンを滅していたので、
改めて「ドラゴンの在り方」について考える切っ掛けになり、
また、とても良い刺激になりました！
素敵なシナリオをご執筆いただき、本当にありがとうございます！！

シナリオを遊ばせていただき、下記に気付いたことをまとめました。
既に修正済みのものや、サルバさんの方針に合わない意見等は
スルーしてやってくださいませ～。

それでは、引き続きよろしくお願い致します！

---

- シナリオのタイトル名が未入力のようです。

- シナリオの中にシナリオ解放条件である「鉄腕の吸血姫」と「ラミディアの魔法使い」の要素（それぞれ一文だけでもOK）を含めていただけましたら助かります。

- 個人的に、ヒントが沢山あって親切なことと、シナリオがサックリと遊べる長さということもあり、もう少し難しくても大丈夫かな、と感じました。

- 現在実績は1つなのですが、今作は試行錯誤が楽しいシナリオという印象でしたので、その過程で他にも実績が得られると、更に遊びが増えて良いかも、と感じました。

- Scene 2
Scene 11からScene 2に進むと、BGMが最初からの再生になる（仕様でしたらスルーしてください～）。

- Scene 11
「ご主人様、私はドラ『コ』ノイドのヴィーグでございます。何なりとご指示を」

- Scene 15
アイスドラゴンは眠り始めると１か月ほ『と』目覚めない事があります。

- Scene 17
つまり・・・自らこの土地にやって『きいた』という事でしょう。

- Scene 34
「アイスドラゴンは祭礼を復活させる事が目的『だったじゃ。』

**Comment by snext1220** [comment]
遅まきながら、プレイ＆クリア致しました。
以下感想＆気付いた点です。

+ Scene単位の文章量が絞られているため、非常に読みやすく、ゲームブック本来の「行動の選択」に集中できたように思えました（自分自身、文章を書きこんでしまうので強く見習いたいと）。

+ 皆さんも書かれているように、中立の立場のドラゴンという存在が、ドラゴンモード全体の中でもアクセントとなっていますよね。戦闘を敢えて封じたという点も、ある意味、ソーサリアンらしいなと感じました。

+ 難易度については、個人的には丁度良いのではないかと感じました。ゲームオーバー原因から実際のゲームオーバーまで若干間隔がある時があるので、その辺、ストレスに感じる人もいるかも?しれませんが、短編なので恐らく大丈夫ではあるかと。

+ free3が内部的なフラグとなっていますが、ステータス画面から見えているので、経過月のようなラベルを付与しても良いかもしれません（プレイヤーさんによっては気になりそう）。
＃ そもそも、こうした見せたくない?数値パラメーターとして、不可視版FreeNのニーズってありますでしょうか？

+ 実績については、 @toki-sor1 さんも書かれていますが、バッドエンド中心にもう少しあると、収集の楽しみがあるかも？（個人的にはまずバッドエンドから探っていくので、実績が立つとちょっと嬉しくなりますｗ）
＃ https://github.com/snext1220/stext/issues/82 （まだ議論途中ですが）でも実績数でポイント換算するため、心持ち多めに実績は大目に設けて戴くと助かる、という事情もあります^^;

**Comment by Salvadors-cabin** [comment]
ときのじさん、リオさん、感想＆アドバイスありがとうございました！
いつも細かいところまで見ていただき、たいへん助かります。

>今作の「ドラゴンを斃さずに問題を解決する」という平和な道が
選べるところも、SText版ドラゴンモードの醍醐味ですね！

>皆さんも書かれているように、中立の立場のドラゴンという存在が、ドラゴンモード全体の中でもアクセントとなっていますよね。

ドラゴンって知的な生き物という一面もある事から、戦闘を好まないヤツもいたんじゃないかな、と思ったわけです。
そういった事が今回のシナリオの出発点でした。

あと、私は名古屋出身のためか(?)、「ドラゴン」が倒されると心が痛むのです。

>free3が内部的なフラグとなっていますが、ステータス画面から見えているので、経過月のようなラベルを付与しても良いかもしれません

そうですね。「label要素」活用したいと思います。

>＃ そもそも、こうした見せたくない?数値パラメーターとして、不可視版FreeNのニーズってありますでしょうか？

経過月は隠しパラメータではないので、このシナリオではFree欄で問題ないです。

不可視の数値パラメータって、ツクールMVでいうところの「変数」ですね。
ツクールMVの「スイッチ」がフラグに当たるものなので、「変数」もあったら使えるとは思います。
例えば、シナリオの進行状況を「フェイズ(=変数)」で管理するような使い方ができると思います。
ただ、有効活用できるのは大規模なシナリオでしょうね。

>実績について

実績については追加を検討します。

>難易度について

みなさん、割と簡単だった印象ですね。
「面白さ」とのバランスが難しいところです。
もうちょっと考えてみます。

**Comment by Salvadors-cabin** [comment]
「ドラゴンネゴシエーター」を更新しました。
https://snext1220.github.io/stext/index.html?id=negotiator

主な変更点は以下です。
・解放条件の追加
・実績の追加
・挿絵の導入
・BGMの追加
・Free3欄に名称を入れた
・誤字脱字修正

難易度についてはいろいろ考えましたが変更していません。
追加した実績を収集することに挑戦すると結構難しいかも、と思いまして。

**Comment by toki-sor1** [comment]
お返事が大変遅くなり、申し訳ありません……！
シナリオ更新お疲れ様です！

PC環境でプレイしましたが、正常に動作しました！
最新版「ネゴシエーター」ですが、メインとしては難易度の変更はなく、しかし、実績コンプを目指すと難易度が上がるというのがいいですね！
難易度というとついシナリオ全体で制御しがちで、そうすると全体的にシナリオの難易度が上がってしまうのですが、「ネゴシエーター」はその難易度設定がメインとやり込み要素できっちり分けられているので、ストレスフリーでとても遊び易いと感じました！

BGMが追加されたことで、ペンタウァとレムス山との場面切り替えがはっきりとして良いですね！
また、挿絵が追加されたので、よりペンタウァをイメージし易くなったように感じました！

最新版でさらに遊び易さや歯ごたえが増してとってもGOODでした！
そこでプレイしていて一点だけ気になった箇所がありましたので、下記にまとめました～。

---

- Free3について

現在では「Free3がレムス登山回数であること」がステータスを確認しなければ分からないので、何処かのシーンで「Free3がレムス登山回数であることの説明」があると良いかも、と思いました～（例：レムス往復について説明が書かれているScene 11など）。

**Comment by Salvadors-cabin** [comment]
GitHUBテスト環境の「ドラゴンネゴシエーター」を更新しました。
https://snext1220.github.io/stext/index.html?id=negotiator

主な修正は下記です。
・挿絵の変更
・Free3欄の説明追加（シーン11)
・description/keywordの追加
・細かい不具合修正

問題無ければこれを公開したいと思いますー

**Comment by toki-sor1** [comment]
「ドラゴンネゴシエーター」更新＆修正お疲れ様でした！
GitHub環境にてテストプレイを行い、正常に遊べることを確認しました！
Free3欄の説明追加もありがとうございました～！

今回のテストプレイで気付いたことと、スケジュールについて確認したいことがあります。
お手数をお掛けして申し訳ありませんが、お手隙の際にご確認＆ご返信よろしくお願い致します～。

---

### シナリオ中に使用されているアイスドラゴンの画像について
画像にサインがあったので少々気になり調べてみたところ、下記サイトが作者様が作品を公開しているサイトのようです（作者様の個人サイトURL追記）。
https://www.deviantart.com/deligaris/art/Ice-Dragon-255510772?offset=200#comments
https://www.deviantart.com/deligaris
www.deligaris.com

翻訳を通したので私の勘違いがありましたら申し訳ありませんが（大汗）、

 **「オリジナルの作成者へのそれぞれのクレジットを伴って、個人的な、非商業的な使用のためである限り、あなたは素材を表示、公的に実行、配布、またはその他の方法で自由に使用することができます（©Nick Deligaris - www.deligaris.com ）。または各アートワークの元の作品へのリンクを提供します。」**

とありましたので、**scenario.xmlのlicenceについては**、上記の情報に差し替えていただいた方が良さそうかな、と思いました。

### シナリオ公開日について

> 5/17 STextサイト「ドラゴンネゴシエーター」紹介文公開
5/25 「ドラゴンネゴシエーター」本編公開

こちら、https://github.com/snext1220/snext-management/issues/7#issuecomment-488215313 のスケジュールから曜日の確認が遅れて申し訳ありません；
**5月25日は土曜日**なのですが、公開日はこの日で大丈夫でしょうか？
今までのシナリオ公開日もアクセス数やTLの流れの関係で平日にズラしていたので、念のための確認でございます～。

---
それでは、引き続きよろしくお願い致します！

**Comment by Salvadors-cabin** [comment]
ときのじさん、どうもありがとうございます！

>画像にサインがあったので少々気になり調べてみたところ、下記サイトが作者様が作品を公開しているサイトのようです（作者様の個人サイトURL追記）。

私が見つけたサイトがその絵を二次利用していたのですね。
原作者の方の調査までしていただき、恐縮です。
恥ずかしながら、私はサインから名前が読み取れませんでした・・
アドレスを更新したファイルをGitHUBにアップしておきました。

>5月25日は土曜日なのですが、公開日はこの日で大丈夫でしょうか？

正直そこまで頭が回っていなかったのですが、25日、26日は私用が入りそうなので、
公開日は5月27日（月）にしたいと思います。
明日、Webサイト更新予定なのでそのようにしておきますー

**Comment by toki-sor1** [comment]
サルバさん、早速のご対応＆ご返信ありがとうございます！

> 私が見つけたサイトがその絵を二次利用していたのですね。
原作者の方の調査までしていただき、恐縮です。
恥ずかしながら、私はサインから名前が読み取れませんでした・・
アドレスを更新したファイルをGitHUBにアップしておきました。

はい～、どうやらそのようですね。
私の場合、フリー素材であそこまで目立つサインを入れるというのはなかなか無いと思ったので、「あれ？」と引っ掛かりました。
サインもデザインされたものなので、私も最初は名前を読み取ることができず、なんとなくそれっぽい文字を入れて検索していましたｗ

修正ありがとうございます！　ばっちりです！

> 正直そこまで頭が回っていなかったのですが、25日、26日は私用が入りそうなので、
公開日は5月27日（月）にしたいと思います。
明日、Webサイト更新予定なのでそのようにしておきますー

Webサイトの更新お疲れ様でした！
**「ネゴシエーター」の公開日は5月27日（月）** に決定ですね！　承知しました！

> あーすみません。いまさらながらですが「進行有利」と「関連性」の意味を取り違えていたようです。ちょっと考えてみます。（※DMから引用）

いえいえいえ……！；；
こちらこそ、自分で考えたルールにもかかわらずチェックが甘く、シナリオ公開日間近になってから本編に大いに関係する部分の修正をお願いする事態を招いてしまい、本当に申し訳ありません……！！
本当にさらりと一文のみでも大丈夫ですので、大変恐縮ではございますが、ご無理のない範囲で、よ、よろしくお願い致します；；

**Comment by Salvadors-cabin** [comment]
連絡遅くなりましたがGitHUB、本番環境共に「ネゴシエーター」を更新しました。
・公開条件シナリオの「関連性」追加（シーン20、21）
・細かい修正
予定通り、明日(5/27)の夜にstext.xmlを更新予定です。
よろしくお願いしますー

**Comment by toki-sor1** [comment]
サルバさん、更新お疲れ様です！
シナリオの修正ありがとうございました！
**関連性追加のSceneも内容ばっちりでした！**

また、先程GitHub版にて**正常に動作しているのを確認しました！**
公開日間近の修正依頼でお手数をお掛けしてしまい、本当に申し訳ありませんでした……！m(_ _;)m

公開日についても承知しました！
お疲れのところ大変恐縮ですが、引き続きよろしくお願い致します！

**Comment by Salvadors-cabin** [comment]
さきほど「ネゴシエーター」を公開しましたー。
このスレも明日ぐらいにクローズしたいと思います。
長期間に渡るアドバイス、サポートありがとうございました！

**Comment by snext1220** [comment]
お疲れ様でした！

**Comment by toki-sor1** [comment]
「ドラゴンネゴシエーター」の公開おめでとうございます！
告知や更新作業等もお疲れ様でした！

こちらこそ、至らないところが多く、色々とお手間を掛けてしまいましたが（大汗）、その度にご丁寧にご対応いただき、感謝感謝でございます！　本当にありがとうございました！m(_ _)m
私も「ネゴシエーター」から学ぶことが沢山あり、とても勉強になりました～！

クローズタイミングも承知しました！
改めて、シナリオをご執筆いただき、どうもありがとうございました～！！

**Comment by Salvadors-cabin** [comment]
皆さん、ありがとうございましたー
