### ISSUE TITLE
STextシナリオ「時を越えた協力者」

### ISSUE THREAD

**Issue by snext1220** [snext1220/snext-management#9]
掲示板（https://sorcerian.progoo.com/bbs/sorcerian_tree_p_1788.html ）からの引継ぎでIssueを立てさせていただきました。

***

遅まきながら、プレイ＆無事にクリア致しました！

@toki-sor1 さんも仰ってたるように、過去／現在の設定が若干難しめで、状況把握に戸惑いながらの探索でしたが、終わってみると、そこがむしろこのシナリオの味だったのかなと感じています。現状を理解できないもどかしさが、悪夢の中を彷徨い歩くような感覚で。気づいてみたら、何周もプレイしてしまっていました^^; 過去作の中でも最も没頭させられてしまったように思えます（してやられたｗ）
＃ゲームオーバー時にヒントがあるのも良いですね。将来的により長いシナリオを作成する際には、badendシーンごとにランダム移動でヒントを表示させるようなアプローチもありかと思えました。

ドラゴン戦の迫力は況やですが、ヘビやフクロウなど独特の癖を持つ脇役たちが、迷宮の雰囲気にマッチしていたのも印象的でした。

また、以前Ｄでもお伝えしたかもしれませんが、最初と最後で、「終焉のゼロ」にも自然に繋いでいただいて。投げっぱなしの序章のバトンを受けて戴いてありがとうございます^^;

以下は細部で気づいた点です。

---

item
i12　破れた⇒敗れた　

flag
f01 利用していない？

enemy
name：「ゴブリン？」など、具体的な名前の方が良いように思えました。
drop：「戦闘結果」は不要かと思うので、カットでお願いします（現在は動作していますが、将来的にエラー原因になるかも）
#text：トーストが空になってしまうので、なにかしらのテキストをお願いします（「幻、なのだろうか？」とか？？）

result
r15 名前と取得条件が逆でしょうか？

id37
その魂＜が＞救われることはないだろう。

id42
＜一拍＞置いて

id48
変化＜が＞あることだろう。

---

**Comment by cocotori** [comment]
すみません、気づくのが遅くなってしまいました・・・！

プレイありがとうございます。
かなり不親切な作りだったかと思いますが、
無事クリアされたようでほっとしています。
手強さを出したいのですが一歩間違えば理不尽、に
なってしまうので調整が難しいですね！

何度もプレイした、というお言葉が
何よりの励みになります。

--

item
i12　破れた⇒敗れた　
修正しました！

flag
f01 利用していない？
削除しました。

enemy
name：「ゴブリン？」など、具体的な名前の方が良いように思えました。
drop：「戦闘結果」は不要かと思うので、カットでお願いします（現在は動作していますが、将来的にエラー原因になるかも）
#text：トーストが空になってしまうので、なにかしらのテキストをお願いします（「幻、なのだろうか？」とか？？）

戦闘ですが、これはちょっとしたこだわりでして・・・
あくまで、個別の敵と戦った、というよりは
さまざまな行動の結果、ダメージを負ってしまった感を出したかったので
このような作りになっています。
ただ、他のシナリオとの整合性もありますし、
修正したほうがよいという意見が多ければ、修正しようかと思います。

drop、text、修正しました。（順番を勘違いしていました）


result
r15 名前と取得条件が逆でしょうか？

見直したところr15は問題なさそうでしたので、r01でしょうか？
こちら、確かに条件と名前が逆のような気がしましたので、
修正しました。

id37
その魂＜が＞救われることはないだろう。
id42
＜一拍＞置いて
id48
変化＜が＞あることだろう。

指摘ありがとうございます。修正しました！

**Comment by cocotori** [comment]
内容をわずかに調整して、あと背景画像を追加しました。
githubにUPしてあります。

基本的にはこれで完成です。
お時間ありましたら見てもらえたら嬉しいです。

**Comment by toki-sor1** [comment]
「時を越えた協力者」更新お疲れ様です！
早速、最新版をGitHub環境にて遊ばせていただきました～！
https://snext1220.github.io/stext/index.html?id=helper

重要なキーワードの色替えでルールやヒントが更に把握し易くなり、重要な台詞など追加で装飾されていて更に強く印象に残りました。
また、シーンの分け方も一部変わっていて、読み易さと演出がパワーアップですね！
様々なご配慮ありがとうございます！

旧版テストプレイ時は私の理解力が至らず、過去と現在を把握するのに時間が掛かってしまったのですが、エンディングを知った上で周回していると、クリア前までは気が付かなかった部分にも目が行くようになったり、理解が難しかったところも理解できるようになるところが楽しかったです！
周回プレイがとても捗りました！

選択肢の違いによる展開を楽しむ周回もあれば、今作のようにストーリーをより深く理解し楽しむ周回もあるのだと、とても勉強になりました！

挿絵が全てモノクロというところもシナリオの雰囲気に合致していて、シナリオとの一体感を強く感じました！
そして、エンディング前にも挿絵が追加され、内容も加筆されていましたが、うぉおおお……旧版でも感動していたところが、ますます素晴らしい演出になっていて、見た瞬間に胸にぐわぁっときました……！！
描き下ろしお疲れ様でした！！すごく感動です……ッ！！

動作確認やドラモード設定については、どちらも問題ありませんでした～。
シナリオ拝見中に**2点だけ気付いた点**がありましたので、お手隙の際にご確認のほどよろしくお願い致します～。

***
●Scene17
「だが、君は選択を誤った。
　すべては終わった、**過去こと**」

●Scene33
術符を鎖のように首に**巻き付けた数多く巻き付けた**ドラゴン。

***
「時を越えた協力者」の公開日は、4月20日は土曜日なので、**25日の木曜日辺りかな**と考えていますが、如何でしょう？
シナリオの公開に向けて、ココさんのご都合の良いタイミングに**stext.xmlの「シナリオページ」と「今後のリリース予定」の編集**をお願い致します～。

**Comment by cocotori** [comment]
>ときさん

さっそくありがとうございます！
いつもいつも素早いレスポンス、ほんと助かってます。

挿絵へのコメントもありがとうございます。
盛り上げる一端を担ってくれたらいいなと思います！

誤字脱字の指摘、ありがとうございます！
修正しておきます。
（巻き付けすぎ！）

公開日についてですが、25日で問題ありません！
シナリオページと今後のリリース予定の編集についても承知しました。

**Comment by toki-sor1** [comment]
ココさん、お疲れ様です～！
ご返信＆シナリオ修正の件、どうもありがとうございます！！
（巻き付けすぎ！　のツッコミに笑ってしまいましたｗ）

シナリオ公開日は、**4月25日に決定**ですね！　承知しました！

ああっ……！　す、すみません、公開準備について失念していたことが一点ございます；
スタッフさんのシナリオは、ご自身で王さまbotから告知を行うことになっておりましたので、追加のお願いになってしまい申し訳ありませんが、**「シナリオ公開日に流す王さまbot告知ツイート」のご用意もお願い致します……！**

お忙しいところ恐縮ですが、引き続きよろしくお願い致します～！

**Comment by Salvadors-cabin** [comment]
遅ればせながら、遊ばせていただきました。

記憶を失っていた主人公が記憶を取り戻すたびに正しい選択ができるようになるという展開が面白いですね。
繰り返し同じシーンをたどる展開よってシーン数を抑えながらボリューム感が出せており、こんなやり方もあるんだと感心しました！

いよいよ公開ですね。楽しみにしておりますー

**Comment by cocotori** [comment]
>サルバさん

プレイありがとうございます！

同じ展開の繰り返しの中に、少しの変化。
それに気づくことで少しずつ道と視界が開けていく、
みたいな展開を目指してみました！
